import { supabase } from "../integrations/supabase/client";
const db=supabase as any;

export type Requirement={weight:number;status:"missing"|"in_progress"|"met"|"not_applicable"};
export function calculateWeightedReadiness(rows:Requirement[]){const applicable=rows.filter(r=>r.status!=="not_applicable");const total=applicable.reduce((s,r)=>s+Math.max(0,Number(r.weight)||0),0);const met=applicable.filter(r=>r.status==="met").reduce((s,r)=>s+Math.max(0,Number(r.weight)||0),0);return total?Math.max(0,Math.min(100,met/total*100)):0;}
export function calculateChecklistProgress(rows:Array<{status:string}>){if(!rows.length)return 0;const done=rows.filter(r=>r.status==="complete"||r.status==="not_applicable").length;return done/rows.length*100;}
export function buildCofounderAgreement(input:{company:string;founders:string[];equity:string;roles:string;vesting:string;ip:string;decisions:string;exit:string;disputes:string;noticeDays:number}){return `CO-FOUNDER AGREEMENT\n\nCompany: ${input.company}\nFounders: ${input.founders.join(", ")}\n\n1. PURPOSE AND ROLES\n${input.roles}\n\n2. EQUITY\n${input.equity}\n\n3. VESTING / EARNING OF EQUITY\n${input.vesting}\n\n4. INTELLECTUAL PROPERTY\n${input.ip}\n\n5. DECISION RIGHTS\n${input.decisions}\n\n6. FOUNDER EXIT / TRANSFER\n${input.exit}\n\n7. DISPUTES\n${input.disputes}\n\n8. TERMINATION NOTICE\n${Math.max(0,input.noticeDays||0)} days where termination by notice applies.\n\n9. GOVERNING LAW\nSouth Africa.\n\nThis builder creates a working draft for review. It is not a substitute for legal advice and does not determine enforceability.`;}
export function buildContractDraft(input:{title:string;parties:string;scope:string;fees:string;term:string;confidentiality:string;ip:string;termination:string;disputes:string}){return `${input.title.toUpperCase()}\n\nPARTIES\n${input.parties}\n\n1. SCOPE\n${input.scope}\n\n2. FEES AND PAYMENT\n${input.fees}\n\n3. TERM\n${input.term}\n\n4. CONFIDENTIALITY\n${input.confidentiality}\n\n5. INTELLECTUAL PROPERTY\n${input.ip}\n\n6. TERMINATION\n${input.termination}\n\n7. DISPUTES\n${input.disputes}\n\n8. GOVERNING LAW\nSouth Africa.\n\nDraft for review only. Parties should confirm the final terms and applicable legal requirements before signature.`;}

async function actor(){return (await supabase.auth.getUser()).data.user?.id||null;}
export async function loadLegalWorkspace(organizationId:string){const calls=await Promise.all([
  db.from("legal_setup_items").select("*").eq("organization_id",organizationId).order("category").order("title"),
  db.from("legal_obligations").select("*").eq("organization_id",organizationId).order("due_date",{ascending:true,nullsFirst:false}),
  db.from("legal_documents").select("*").eq("organization_id",organizationId).order("updated_at",{ascending:false}),
  db.from("legal_contracts").select("*").eq("organization_id",organizationId).order("updated_at",{ascending:false}),
  db.from("legal_signature_requests").select("*").eq("organization_id",organizationId).order("updated_at",{ascending:false}),
  db.from("legal_signature_recipients").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false}),
  db.from("legal_tender_assessments").select("*").eq("organization_id",organizationId).order("closing_at",{ascending:true,nullsFirst:false}),
  db.from("legal_tender_requirements").select("*").eq("organization_id",organizationId),
  db.from("legal_supplier_assessments").select("*").eq("organization_id",organizationId).order("updated_at",{ascending:false}),
  db.from("legal_supplier_requirements").select("*").eq("organization_id",organizationId),
  db.from("legal_due_diligence_shares").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false}),
  db.from("company_verification_records").select("*").eq("organization_id",organizationId).order("updated_at",{ascending:false}),
  db.from("ops_renewals").select("*").eq("organization_id",organizationId).order("due_date",{ascending:true}).limit(100),
  db.rpc("legal_compliance_summary",{org_id:organizationId}),
]);for(const c of calls)if(c.error)throw c.error;const [setup,obligations,documents,contracts,signatureRequests,signatureRecipients,tenders,tenderRequirements,supplierAssessments,supplierRequirements,shares,verification,renewals,summary]=calls;return {setup:setup.data||[],obligations:obligations.data||[],documents:documents.data||[],contracts:contracts.data||[],signatureRequests:signatureRequests.data||[],signatureRecipients:signatureRecipients.data||[],tenders:tenders.data||[],tenderRequirements:tenderRequirements.data||[],supplierAssessments:supplierAssessments.data||[],supplierRequirements:supplierRequirements.data||[],shares:shares.data||[],verification:verification.data||[],renewals:renewals.data||[],summary:summary.data||{}};}

const DEFAULT_SETUP=[
  ["company_registration","Company registration evidence","company"],["tax_registration","Tax registration evidence","tax"],["beneficial_ownership","Beneficial ownership information","company"],["bee_documentation","B-BBEE evidence","bee"],["banking","Business bank account evidence","company"],["popia","Privacy / POPIA operating documents","privacy"],["contracts","Core customer / supplier contracts","contract"],["employment","Employment / contractor documentation","employment"],["insurance","Applicable business insurance","insurance"],["procurement_pack","Supplier / procurement pack","procurement"],
] as const;
export async function ensureDefaultLegalSetup(org:string){const uid=await actor();const rows=DEFAULT_SETUP.map(([item_key,title,category])=>({organization_id:org,item_key,title,category,status:"not_started",created_by:uid}));const {error}=await db.from("legal_setup_items").upsert(rows,{onConflict:"organization_id,item_key",ignoreDuplicates:true});if(error)throw error;}
export async function updateSetupItem(id:string,values:Record<string,unknown>){const {data,error}=await db.from("legal_setup_items").update({...values,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function createObligation(org:string,values:Record<string,unknown>){const {data,error}=await db.from("legal_obligations").insert({organization_id:org,...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function uploadLegalDocument(org:string,file:File,meta:{title:string;document_type:string;public_safe_label?:string;expiry_date?:string}){const uid=await actor();if(!uid)throw new Error("Sign in required");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${org}/${uid}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from("legal-documents").upload(path,file,{upsert:false,contentType:file.type||undefined});if(uploadError)throw uploadError;const {data,error}=await db.from("legal_documents").insert({organization_id:org,title:meta.title,document_type:meta.document_type,storage_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,public_safe_label:meta.public_safe_label||null,expiry_date:meta.expiry_date||null,uploaded_by:uid}).select("*").single();if(error){await supabase.storage.from("legal-documents").remove([path]);throw error;}return data;}
export async function createContract(org:string,values:Record<string,unknown>){const {data,error}=await db.from("legal_contracts").insert({organization_id:org,...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function createSignatureRequest(org:string,contractId:string,title:string,recipient:{name:string;email:string},expiresAt?:string){const uid=await actor();const {data:req,error}=await db.from("legal_signature_requests").insert({organization_id:org,contract_id:contractId,title,expires_at:expiresAt||null,status:"sent",created_by:uid}).select("*").single();if(error)throw error;const {data:rec,error:rerr}=await db.from("legal_signature_recipients").insert({organization_id:org,request_id:req.id,full_name:recipient.name,email:recipient.email,status:"sent"}).select("*").single();if(rerr)throw rerr;await db.from("legal_signature_events").insert({organization_id:org,request_id:req.id,recipient_id:rec.id,event_type:"sent",actor_type:"workspace_user",actor_id:uid});return {request:req,recipient:rec};}
export async function createTender(org:string,values:Record<string,unknown>){const {data,error}=await db.from("legal_tender_assessments").insert({organization_id:org,...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function addTenderRequirement(org:string,assessmentId:string,values:Record<string,unknown>){const {data,error}=await db.from("legal_tender_requirements").insert({organization_id:org,assessment_id:assessmentId,...values}).select("*").single();if(error)throw error;return data;}
export async function createSupplierAssessment(org:string,targetCustomer:string){const {data,error}=await db.from("legal_supplier_assessments").insert({organization_id:org,target_customer:targetCustomer||null,created_by:await actor()}).select("*").single();if(error)throw error;const defaults=[['registration','Company registration',15],['tax','Tax registration / required tax status',15],['bee','B-BBEE evidence',15],['bank','Bank confirmation',10],['insurance','Applicable insurance',10],['references','Customer / supplier references',10],['policies','Required business policies',10],['capacity','Delivery capability evidence',15]];await db.from("legal_supplier_requirements").insert(defaults.map(([requirement_key,title,weight])=>({organization_id:org,assessment_id:data.id,requirement_key,title,weight,status:"missing"})));return data;}
export async function updateRequirement(table:"legal_tender_requirements"|"legal_supplier_requirements",id:string,values:Record<string,unknown>){const {data,error}=await db.from(table).update({...values,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function createDueDiligenceShare(org:string,name:string,documentIds:string[],expiresAt:string,maxViews?:number){const {data,error}=await db.from("legal_due_diligence_shares").insert({organization_id:org,name,allowed_document_ids:documentIds,expires_at:expiresAt,max_views:maxViews||null,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
