import { supabase } from "../integrations/supabase/client";
const db=supabase as any;
export function calculateFundingRound(preMoney:number,raise:number){const pre=Math.max(0,Number(preMoney)||0),amount=Math.max(0,Number(raise)||0),post=pre+amount,investor=post>0?amount/post*100:0;return{preMoney:pre,raiseAmount:amount,postMoney:post,newInvestorOwnership:investor,existingHolderOwnership:100-investor};}
export function calculateDilutedCapTable(entries:Array<{holder_name:string;ownership_percent:number}>,newInvestorPercent:number){const p=Math.max(0,Math.min(100,Number(newInvestorPercent)||0)),scale=(100-p)/100;return [...entries.map(e=>({holder_name:e.holder_name,ownership_percent:Math.max(0,Number(e.ownership_percent)||0)*scale})),{holder_name:"New investor",ownership_percent:p}];}
export function revenueMultipleValuation(annualRevenue:number,multiple:number){const revenue=Math.max(0,Number(annualRevenue)||0),m=Math.max(0,Number(multiple)||0);return revenue*m;}
export function targetOwnershipValuation(raise:number,targetPercent:number){const amount=Math.max(0,Number(raise)||0),pct=Math.max(.01,Math.min(99.99,Number(targetPercent)||0));const post=amount/(pct/100),pre=Math.max(0,post-amount);return{preMoney:pre,postMoney:post};}
export function scoreFundingOpportunity(input:{stage?:string;industry?:string;location?:string;amount?:number},opportunity:any){let score=15;const match=(value:string,arr:any[])=>!arr?.length?0:arr.some(v=>String(v).toLowerCase().includes(value.toLowerCase()))?1:0;if(input.stage)score+=match(input.stage,opportunity.stages||[])*25;else score+=12.5;if(input.industry)score+=match(input.industry,opportunity.industries||[])*25;else score+=12.5;if(input.location)score+=match(input.location,opportunity.locations||[])*15;else score+=7.5;if(input.amount&&Number(input.amount)>0){const amount=Number(input.amount),min=Number(opportunity.min_amount||0),max=Number(opportunity.max_amount||0);score+=(min&&amount<min)||(max&&amount>max)?0:20;}else score+=10;return Math.max(0,Math.min(100,Math.round(score)));}
async function actor(){return (await supabase.auth.getUser()).data.user?.id||null;}
export async function loadFundingWorkspace(org:string){const calls=await Promise.all([
  db.from("funding_opportunities").select("*").order("deadline",{ascending:true,nullsFirst:false}).limit(200),
  db.from("funding_saved_opportunities").select("*").eq("organization_id",org).order("updated_at",{ascending:false}),
  db.from("funding_investors").select("*").eq("organization_id",org).order("updated_at",{ascending:false}),
  db.from("funding_investor_contacts").select("*").eq("organization_id",org).order("updated_at",{ascending:false}),
  db.from("funding_investor_interactions").select("*").eq("organization_id",org).order("occurred_at",{ascending:false}).limit(100),
  db.from("funding_pitch_decks").select("*").eq("organization_id",org).order("updated_at",{ascending:false}),
  db.from("funding_pitch_slides").select("*").eq("organization_id",org).order("position"),
  db.from("funding_data_rooms").select("*").eq("organization_id",org).order("updated_at",{ascending:false}),
  db.from("funding_data_room_items").select("*").eq("organization_id",org).order("position"),
  db.from("funding_data_room_shares").select("*").eq("organization_id",org).order("created_at",{ascending:false}),
  db.from("funding_rounds").select("*").eq("organization_id",org).order("updated_at",{ascending:false}),
  db.from("funding_round_scenarios").select("*").eq("organization_id",org).order("created_at",{ascending:false}),
  db.from("funding_cap_table_entries").select("*").eq("organization_id",org).order("ownership_percent",{ascending:false}),
  db.from("funding_valuation_scenarios").select("*").eq("organization_id",org).order("created_at",{ascending:false}),
  db.from("funding_offers").select("*").eq("organization_id",org).order("received_at",{ascending:false}),
  db.from("legal_documents").select("id,title,document_type,status,verification_status").eq("organization_id",org).eq("status","current").order("updated_at",{ascending:false}),
  db.rpc("funding_readiness_summary",{org_id:org}),
]);for(const c of calls)if(c.error)throw c.error;const [opportunities,saved,investors,contacts,interactions,decks,slides,rooms,roomItems,roomShares,rounds,roundScenarios,capTable,valuations,offers,documents,readiness]=calls;return{opportunities:opportunities.data||[],saved:saved.data||[],investors:investors.data||[],contacts:contacts.data||[],interactions:interactions.data||[],decks:decks.data||[],slides:slides.data||[],rooms:rooms.data||[],roomItems:roomItems.data||[],roomShares:roomShares.data||[],rounds:rounds.data||[],roundScenarios:roundScenarios.data||[],capTable:capTable.data||[],valuations:valuations.data||[],offers:offers.data||[],documents:documents.data||[],readiness:readiness.data||{}};}
export async function createFundingOpportunity(org:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_opportunities").insert({organization_id:org,source_scope:"workspace",...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function saveFundingOpportunity(org:string,opportunityId:string,score:number){const {data,error}=await db.from("funding_saved_opportunities").upsert({organization_id:org,opportunity_id:opportunityId,match_score:Math.round(score),status:"saved",owner_id:await actor(),updated_at:new Date().toISOString()},{onConflict:"organization_id,opportunity_id"}).select("*").single();if(error)throw error;return data;}
export async function createInvestor(org:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_investors").insert({organization_id:org,...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function addInvestorContact(org:string,investorId:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_investor_contacts").insert({organization_id:org,investor_id:investorId,...values}).select("*").single();if(error)throw error;return data;}
export async function addInvestorInteraction(org:string,investorId:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_investor_interactions").insert({organization_id:org,investor_id:investorId,...values,actor_id:await actor()}).select("*").single();if(error)throw error;return data;}
const DEFAULT_SLIDES=[['cover','Company & investment thesis'],['problem','Problem'],['solution','Solution'],['market','Market opportunity'],['product','Product'],['business_model','Business model'],['go_to_market','Go-to-market'],['traction','Traction'],['competition','Competition'],['financials','Financials'],['team','Team'],['ask','The ask']];
export async function createPitchDeck(org:string,title:string){const {data,error}=await db.from("funding_pitch_decks").insert({organization_id:org,title,created_by:await actor()}).select("*").single();if(error)throw error;await db.from("funding_pitch_slides").insert(DEFAULT_SLIDES.map(([slide_type,slideTitle],position)=>({organization_id:org,deck_id:data.id,position,slide_type,title:slideTitle,body:""})));return data;}
export async function updatePitchSlide(id:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_pitch_slides").update({...values,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function snapshotReadiness(org:string,readiness:any){const {data,error}=await db.from("funding_readiness_snapshots").insert({organization_id:org,overall_score:readiness.overall_score||0,governance_score:readiness.governance_score||0,financial_score:readiness.financial_score||0,traction_score:readiness.traction_score||0,materials_score:readiness.materials_score||0,data_room_score:readiness.data_room_score||0,risk_penalty:readiness.risk_penalty||0,evidence:readiness.evidence||{},gaps:readiness.gaps||[],created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function createDataRoom(org:string,name:string,description:string){const {data,error}=await db.from("funding_data_rooms").insert({organization_id:org,name,description,status:"ready",created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function addDataRoomItem(org:string,roomId:string,documentId:string,title:string,category:string){const {data,error}=await db.from("funding_data_room_items").insert({organization_id:org,room_id:roomId,legal_document_id:documentId,title,category}).select("*").single();if(error)throw error;return data;}
export async function createDataRoomShare(org:string,roomId:string,name:string,expiresAt:string,maxViews?:number,allowDownload=false){const {data,error}=await db.from("funding_data_room_shares").insert({organization_id:org,room_id:roomId,name,expires_at:expiresAt,max_views:maxViews||null,allow_download:allowDownload,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function createFundingRound(org:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_rounds").insert({organization_id:org,...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function saveRoundScenario(org:string,roundId:string|null,name:string,pre:number,raise:number){const calc=calculateFundingRound(pre,raise);const {data,error}=await db.from("funding_round_scenarios").insert({organization_id:org,round_id:roundId,name,pre_money_valuation:calc.preMoney,raise_amount:calc.raiseAmount,post_money_valuation:calc.postMoney,new_investor_ownership:calc.newInvestorOwnership,existing_holder_ownership:calc.existingHolderOwnership,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function addCapTableEntry(org:string,values:Record<string,unknown>){const {data,error}=await db.from("funding_cap_table_entries").insert({organization_id:org,...values,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function saveValuationScenario(org:string,values:{name:string;method:string;annual_revenue?:number;multiple?:number;raise_amount?:number;target_investor_percent?:number;assumptions?:string}){let pre=0,post=0;if(values.method==="revenue_multiple"){pre=revenueMultipleValuation(values.annual_revenue||0,values.multiple||0);post=pre+(values.raise_amount||0);}else if(values.method==="target_ownership"){const v=targetOwnershipValuation(values.raise_amount||0,values.target_investor_percent||10);pre=v.preMoney;post=v.postMoney;}const {data,error}=await db.from("funding_valuation_scenarios").insert({organization_id:org,...values,estimated_pre_money:pre,estimated_post_money:post,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
