import { supabase } from "../integrations/supabase/client";
const db=supabase as any;
export type DeterministicCommand={kind:"navigate"|"draft_task"|"unknown";label:string;path?:string;task?:string};
export function parseDeterministicCommand(input:string):DeterministicCommand{const text=input.trim().toLowerCase();const routes:[string,string][]=[["revenue","/app/revenue"],["growth","/app/growth"],["operations","/app/operations"],["compliance","/app/compliance"],["funding","/app/funding"],["opportunities","/app/opportunities"],["website studio","/app/website-studio-v6"]];if(text.startsWith("open ")){const hit=routes.find(([name])=>text.includes(name));if(hit)return{kind:"navigate",label:`Open ${hit[0]}`,path:hit[1]};}if(text.startsWith("create task:"))return{kind:"draft_task",label:"Draft task",task:input.slice(input.indexOf(":")+1).trim()};return{kind:"unknown",label:"No deterministic command matched"};}
export function buildSeoMetadata(input:{name:string;offering:string;location?:string;keyword?:string}){const base=[input.offering,input.location].filter(Boolean).join(" in ");const title=`${base||input.offering} | ${input.name}`.slice(0,60);const description=`Discover ${input.offering}${input.location?` in ${input.location}`:""} from ${input.name}. ${input.keyword?`Focused on ${input.keyword}. `:""}Learn more, compare options and get in touch.`.slice(0,155);return{title,description};}
export function buildBusinessPlanOutline(company:string){return["Executive Summary","Problem & Customer","Solution & Value Proposition","Market & Competition","Business Model","Go-to-Market","Operations","Team & Governance","Financial Assumptions","Risks & Mitigations","Milestones & Funding Need"].map((section,i)=>({order:i+1,section,prompt:`Draft ${section} for ${company} using verified workspace facts only. Mark assumptions explicitly.`}));}
export function buildPitchNarrative(problem:string,solution:string,traction:string){return{problem:`Problem: ${problem}`,solution:`Solution: ${solution}`,traction:`Traction: ${traction}`,disclosure:"Narrative draft — verify all metrics and claims against workspace evidence before publishing."};}
export function automationSafety(rule:{requires_approval?:boolean;action_type?:string}){const risky=new Set(["webhook","draft_content"]);return{requiresApproval:rule.requires_approval!==false||risky.has(String(rule.action_type||"")),canAutoApply:false};}
async function actor(){return (await supabase.auth.getUser()).data.user?.id||null;}
export async function loadIntelligenceWorkspace(org:string){const calls=await Promise.all([db.from("intelligence_threads").select("*").eq("organization_id",org).order("updated_at",{ascending:false}).limit(30),db.from("intelligence_next_actions").select("*").eq("organization_id",org).order("priority",{ascending:false}).limit(100),db.from("intelligence_automation_rules").select("*").eq("organization_id",org).order("updated_at",{ascending:false}).limit(100),db.from("intelligence_change_sets").select("*").eq("organization_id",org).order("created_at",{ascending:false}).limit(100),db.from("intelligence_localisation_jobs").select("*").eq("organization_id",org).order("updated_at",{ascending:false}).limit(100),db.from("intelligence_audit_log").select("*").eq("organization_id",org).order("created_at",{ascending:false}).limit(100),db.rpc("intelligence_next_best_actions",{org_id:org})]);for(const c of calls)if(c.error)throw c.error;return{threads:calls[0].data||[],actions:calls[1].data||[],rules:calls[2].data||[],changes:calls[3].data||[],localisations:calls[4].data||[],audit:calls[5].data||[],liveActions:calls[6].data||[]};}
export async function createThread(org:string,title:string,mode:string){const {data,error}=await db.from("intelligence_threads").insert({organization_id:org,title,mode,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function createAutomationRule(org:string,values:Record<string,unknown>){const safety=automationSafety(values);const {data,error}=await db.from("intelligence_automation_rules").insert({organization_id:org,...values,requires_approval:safety.requiresApproval,is_enabled:false,created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function createLocalisationJob(org:string,source:string,target:string,text:string){const {data,error}=await db.from("intelligence_localisation_jobs").insert({organization_id:org,source_locale:source,target_locale:target,source_text:text,status:"draft",created_by:await actor()}).select("*").single();if(error)throw error;return data;}
export async function approveChangeSet(id:string){const {data,error}=await db.rpc("intelligence_approve_change_set",{change_id:id});if(error)throw error;return Boolean(data);}
export async function requestAssistant(org:string,mode:string,prompt:string,threadId?:string){const {data,error}=await supabase.functions.invoke("startup-os-assistant",{body:{organizationId:org,mode,prompt,threadId}});if(error)throw error;return data as {ok:boolean;response:string;provider?:string;changeSet?:unknown;disclosure?:string};}
