import { createWebsiteDraft, normalizeWebsiteDraft, type BusinessCategoryKey, type WebsiteStudioDraft } from "./website-studio";

export type StudioTemplatePreset = {
  key: string;
  name: string;
  category: BusinessCategoryKey;
  family: string;
  description: string;
  tags: string[];
  preview: { primary: string; secondary: string; accent: string; surface: string; mood: "light" | "dark" | "editorial" | "vivid" };
  brand: Partial<WebsiteStudioDraft["brand"]>;
  site: Partial<WebsiteStudioDraft["site"]>;
};

const p = (
  key: string,
  name: string,
  category: BusinessCategoryKey,
  family: string,
  description: string,
  preview: StudioTemplatePreset["preview"],
  brand: StudioTemplatePreset["brand"],
  site: StudioTemplatePreset["site"],
  tags: string[] = [],
): StudioTemplatePreset => ({ key, name, category, family, description, preview, brand, site, tags });

export const studioTemplates: StudioTemplatePreset[] = [
  p("pulse-saas", "Pulse SaaS", "technology", "SaaS & AI", "High-conversion software landing system with polished glass UI and product-first hierarchy.", { primary: "#5b5cf0", secondary: "#11112b", accent: "#44e6c1", surface: "#f4f3ff", mood: "vivid" }, { primary: "#5b5cf0", secondary: "#11112b", accent: "#44e6c1", surface: "#f4f3ff", text: "#151526", fontFamily: "Inter", heroStyle: "split", navStyle: "glass", cardStyle: "glass", buttonStyle: "pill", radius: 24 }, { headline: "Software people understand in seconds.", tagline: "Show the problem, product and proof with a premium SaaS experience built to convert." }, ["saas", "app", "startup", "ai"]),
  p("neon-foundry", "Neon Foundry", "technology", "Developer tools", "Dark developer-product layout for APIs, platforms, infrastructure and technical startups.", { primary: "#8cff47", secondary: "#090c10", accent: "#27d8ff", surface: "#10151b", mood: "dark" }, { primary: "#8cff47", secondary: "#090c10", accent: "#27d8ff", surface: "#f2f5f5", text: "#0a1115", fontFamily: "DM Sans", heroStyle: "split", navStyle: "dark", cardStyle: "bordered", buttonStyle: "square", radius: 10 }, { headline: "Ship faster. Operate with confidence.", tagline: "A technical product site that makes complex infrastructure feel clear, credible and ready to scale." }, ["developer", "api", "cloud", "cyber"]),
  p("orbit-ai", "Orbit AI", "technology", "AI company", "Cinematic AI startup composition with soft depth, oversized type and premium investor-ready polish.", { primary: "#6d4aff", secondary: "#0b0a23", accent: "#f05cff", surface: "#f7f3ff", mood: "vivid" }, { primary: "#6d4aff", secondary: "#0b0a23", accent: "#f05cff", surface: "#f7f3ff", text: "#161127", fontFamily: "Manrope", heroStyle: "centered", navStyle: "glass", cardStyle: "elevated", buttonStyle: "pill", radius: 28 }, { headline: "Intelligence that moves work forward.", tagline: "Position an AI product with clarity, proof and the confidence serious buyers and investors expect." }, ["ai", "machine learning", "automation"]),
  p("studio-north", "Studio North", "professional-services", "Creative agency", "Editorial agency system with strong type, restrained colour and premium portfolio energy.", { primary: "#ff4e2f", secondary: "#171717", accent: "#ffcf4a", surface: "#f4f0e9", mood: "editorial" }, { primary: "#ff4e2f", secondary: "#171717", accent: "#ffcf4a", surface: "#f4f0e9", text: "#1b1b1b", fontFamily: "Manrope", heroStyle: "minimal", navStyle: "clean", cardStyle: "bordered", buttonStyle: "square", radius: 8 }, { headline: "Ideas made impossible to ignore.", tagline: "A sharp agency site for strategy, design, campaigns and creative work that needs presence." }, ["agency", "design", "creative", "portfolio"]),
  p("boldfolio", "Boldfolio", "professional-services", "Portfolio", "Personal brand and studio portfolio with expressive type and highly visual work presentation.", { primary: "#1a1a1a", secondary: "#050505", accent: "#ff6bd6", surface: "#fff5fb", mood: "editorial" }, { primary: "#1a1a1a", secondary: "#050505", accent: "#ff6bd6", surface: "#fff5fb", text: "#171717", fontFamily: "DM Sans", heroStyle: "centered", navStyle: "clean", cardStyle: "elevated", buttonStyle: "pill", radius: 30 }, { headline: "Selected work. Clear point of view.", tagline: "A premium personal portfolio for creators, strategists, designers and independent professionals." }, ["portfolio", "creator", "designer"]),
  p("counsel-prime", "Counsel Prime", "professional-services", "Legal", "Executive legal-services template with authoritative typography, measured spacing and trust-led conversion.", { primary: "#b69255", secondary: "#101a2d", accent: "#d8c190", surface: "#f8f5ef", mood: "light" }, { primary: "#b69255", secondary: "#101a2d", accent: "#d8c190", surface: "#f8f5ef", text: "#151b25", fontFamily: "Manrope", heroStyle: "split", navStyle: "dark", cardStyle: "bordered", buttonStyle: "square", radius: 8 }, { headline: "Serious counsel for consequential decisions.", tagline: "Present legal capability, sectors and client confidence with a disciplined professional experience." }, ["legal", "law", "consulting"]),
  p("ledger-house", "Ledger House", "professional-services", "Finance & accounting", "Clean financial-services template with data-forward credibility and conversion-focused service cards.", { primary: "#0c6f62", secondary: "#082b31", accent: "#8fd8b8", surface: "#eff8f5", mood: "light" }, { primary: "#0c6f62", secondary: "#082b31", accent: "#8fd8b8", surface: "#eff8f5", text: "#102a2c", fontFamily: "Inter", heroStyle: "split", navStyle: "clean", cardStyle: "elevated", buttonStyle: "soft", radius: 18 }, { headline: "Financial clarity for better decisions.", tagline: "Accounting, advisory and finance services presented with the trust and precision clients expect." }, ["finance", "accounting", "advisory"]),
  p("vertex-build", "Vertex Build", "construction", "Construction", "Bold industrial layout for contractors, engineers and project businesses with strong project authority.", { primary: "#ffb000", secondary: "#171717", accent: "#ff5b35", surface: "#f3f1eb", mood: "editorial" }, { primary: "#ffb000", secondary: "#171717", accent: "#ff5b35", surface: "#f3f1eb", text: "#1a1a1a", fontFamily: "DM Sans", heroStyle: "split", navStyle: "dark", cardStyle: "bordered", buttonStyle: "square", radius: 6 }, { headline: "Built to deliver. Proven on site.", tagline: "Show capability, projects, safety discipline and commercial readiness without the usual corporate clutter." }, ["construction", "engineering", "industrial"]),
  p("habitat-property", "Habitat Property", "property", "Real estate", "Modern property-marketing site with high-trust visuals, enquiry conversion and clean listing-style rhythm.", { primary: "#1f6a5d", secondary: "#132b28", accent: "#d9a85f", surface: "#f4f7f3", mood: "light" }, { primary: "#1f6a5d", secondary: "#132b28", accent: "#d9a85f", surface: "#f4f7f3", text: "#1a2926", fontFamily: "Manrope", heroStyle: "split", navStyle: "glass", cardStyle: "elevated", buttonStyle: "soft", radius: 18 }, { headline: "Property discovery without the friction.", tagline: "A premium real-estate experience for listings, enquiries, developments and trusted property services." }, ["property", "real estate", "rental"]),
  p("campus-living", "Campus Living", "property", "Student accommodation", "Youthful accommodation template built for residences, bookings, applications and campus proximity.", { primary: "#3b56e8", secondary: "#111a4e", accent: "#23c9a5", surface: "#f2f5ff", mood: "vivid" }, { primary: "#3b56e8", secondary: "#111a4e", accent: "#23c9a5", surface: "#f2f5ff", text: "#151b35", fontFamily: "Poppins", heroStyle: "split", navStyle: "glass", cardStyle: "elevated", buttonStyle: "pill", radius: 24 }, { headline: "A better place to live, study and belong.", tagline: "Show rooms, amenities, location and application steps in one student-friendly experience." }, ["student", "accommodation", "campus"]),
  p("table-flame", "Table & Flame", "restaurant", "Restaurant", "Warm restaurant template with premium hospitality tone, bold menu storytelling and booking-first CTAs.", { primary: "#b6412e", secondary: "#2b1712", accent: "#e7aa5f", surface: "#fbf5ed", mood: "editorial" }, { primary: "#b6412e", secondary: "#2b1712", accent: "#e7aa5f", surface: "#fbf5ed", text: "#2b201c", fontFamily: "DM Sans", heroStyle: "split", navStyle: "dark", cardStyle: "elevated", buttonStyle: "soft", radius: 16 }, { headline: "Food worth planning your day around.", tagline: "A hospitality-led restaurant experience for menus, reservations, private events and loyal customers." }, ["restaurant", "food", "cafe"]),
  p("freshcart", "FreshCart", "retail", "Ecommerce", "Bright ecommerce starter with product-focused sections, fast hierarchy and friendly conversion cues.", { primary: "#2fa866", secondary: "#103b2a", accent: "#ffcc33", surface: "#f3fbf5", mood: "vivid" }, { primary: "#2fa866", secondary: "#103b2a", accent: "#ffcc33", surface: "#f3fbf5", text: "#153025", fontFamily: "Poppins", heroStyle: "split", navStyle: "clean", cardStyle: "elevated", buttonStyle: "pill", radius: 22 }, { headline: "Products people want. Shopping that flows.", tagline: "A modern retail storefront for products, collections, delivery and high-converting customer journeys." }, ["shop", "ecommerce", "retail"]),
  p("atelier-mode", "Atelier Mode", "retail", "Fashion", "High-fashion editorial storefront using sharp monochrome structure and understated luxury detailing.", { primary: "#111111", secondary: "#000000", accent: "#d7c6b2", surface: "#f5f3ef", mood: "editorial" }, { primary: "#111111", secondary: "#000000", accent: "#d7c6b2", surface: "#f5f3ef", text: "#111111", fontFamily: "Manrope", heroStyle: "minimal", navStyle: "clean", cardStyle: "bordered", buttonStyle: "square", radius: 4 }, { headline: "A collection with a point of view.", tagline: "Editorial commerce for fashion, accessories and brands where visual identity leads the sale." }, ["fashion", "apparel", "luxury"]),
  p("glow-beauty", "Glow Beauty", "healthcare", "Beauty & wellness", "Soft premium beauty template for salons, skincare, spa and personal care brands.", { primary: "#d77b98", secondary: "#5b3040", accent: "#f2c7d6", surface: "#fff6f8", mood: "light" }, { primary: "#d77b98", secondary: "#5b3040", accent: "#f2c7d6", surface: "#fff6f8", text: "#3d2a31", fontFamily: "Poppins", heroStyle: "centered", navStyle: "glass", cardStyle: "elevated", buttonStyle: "pill", radius: 28 }, { headline: "Feel good in the skin you are in.", tagline: "A calm, premium wellness experience for services, bookings, treatments and customer trust." }, ["beauty", "salon", "spa", "wellness"]),
  p("medica-clinic", "Medica Clinic", "healthcare", "Clinic", "Calm healthcare template with accessible information architecture and booking-focused service presentation.", { primary: "#197c86", secondary: "#153a4a", accent: "#60c8c5", surface: "#f1f8f9", mood: "light" }, { primary: "#197c86", secondary: "#153a4a", accent: "#60c8c5", surface: "#f1f8f9", text: "#17353c", fontFamily: "Inter", heroStyle: "split", navStyle: "clean", cardStyle: "bordered", buttonStyle: "soft", radius: 16 }, { headline: "Professional care made easier to access.", tagline: "A clear healthcare website for services, appointments, patient information and trusted contact." }, ["clinic", "doctor", "medical", "health"]),
  p("edulaunch", "EduLaunch", "education", "Education", "Modern training and academy template for programmes, outcomes, admissions and learner progression.", { primary: "#3855d6", secondary: "#14204f", accent: "#f3b741", surface: "#f4f6ff", mood: "vivid" }, { primary: "#3855d6", secondary: "#14204f", accent: "#f3b741", surface: "#f4f6ff", text: "#17203d", fontFamily: "Poppins", heroStyle: "split", navStyle: "glass", cardStyle: "elevated", buttonStyle: "pill", radius: 22 }, { headline: "Learning designed to move people forward.", tagline: "Present programmes, applications, outcomes and student support in a clear modern education experience." }, ["education", "academy", "training"]),
  p("tiny-futures", "Tiny Futures", "education", "Early learning", "Playful but polished preschool and early-learning system with friendly shape language and bright trust cues.", { primary: "#6a59dd", secondary: "#383068", accent: "#ffb93f", surface: "#fff9ec", mood: "vivid" }, { primary: "#6a59dd", secondary: "#383068", accent: "#ffb93f", surface: "#fff9ec", text: "#342f4b", fontFamily: "Poppins", heroStyle: "centered", navStyle: "clean", cardStyle: "elevated", buttonStyle: "pill", radius: 32 }, { headline: "A bright start for curious minds.", tagline: "A joyful digital home for programmes, parent information, enrolment and early-learning community." }, ["school", "kids", "kindergarten"]),
  p("summit-travel", "Summit Travel", "events", "Travel", "Adventure-led travel template with cinematic hierarchy, itinerary storytelling and booking energy.", { primary: "#1b7f72", secondary: "#14334a", accent: "#f39b42", surface: "#f3f8f5", mood: "vivid" }, { primary: "#1b7f72", secondary: "#14334a", accent: "#f39b42", surface: "#f3f8f5", text: "#1b3137", fontFamily: "Manrope", heroStyle: "split", navStyle: "glass", cardStyle: "elevated", buttonStyle: "pill", radius: 24 }, { headline: "Go somewhere worth remembering.", tagline: "A destination-first experience for tours, itineraries, bookings and travel brands built around discovery." }, ["travel", "tour", "adventure"]),
  p("eventspark", "EventSpark", "events", "Events", "High-energy event and activation template for tickets, lineups, partners and audience conversion.", { primary: "#ff4a65", secondary: "#21102f", accent: "#9d65ff", surface: "#fff2f5", mood: "vivid" }, { primary: "#ff4a65", secondary: "#21102f", accent: "#9d65ff", surface: "#fff2f5", text: "#28172f", fontFamily: "Poppins", heroStyle: "centered", navStyle: "dark", cardStyle: "glass", buttonStyle: "pill", radius: 26 }, { headline: "Turn attention into attendance.", tagline: "An energetic event site for programmes, tickets, sponsors, activations and everything audiences need before arrival." }, ["event", "festival", "tickets"]),
  p("secureline", "SecureLine", "security", "Security", "High-trust security-services template with disciplined colour, strong proof blocks and clear response pathways.", { primary: "#2059b6", secondary: "#071627", accent: "#36c0dd", surface: "#f1f5f9", mood: "dark" }, { primary: "#2059b6", secondary: "#071627", accent: "#36c0dd", surface: "#f1f5f9", text: "#13212e", fontFamily: "Inter", heroStyle: "split", navStyle: "dark", cardStyle: "bordered", buttonStyle: "square", radius: 8 }, { headline: "Protection built around the real risk.", tagline: "Security capability, response, compliance and service scope communicated with professional authority." }, ["security", "guarding", "safety"]),
  p("civic-impact", "Civic Impact", "institution", "Institution & NGO", "Public-value template for programmes, initiatives, resources and institutional credibility.", { primary: "#2458a6", secondary: "#17345d", accent: "#eea83a", surface: "#f5f7fa", mood: "light" }, { primary: "#2458a6", secondary: "#17345d", accent: "#eea83a", surface: "#f5f7fa", text: "#1e2d3f", fontFamily: "Inter", heroStyle: "split", navStyle: "clean", cardStyle: "bordered", buttonStyle: "soft", radius: 14 }, { headline: "Purpose, programmes and impact in one place.", tagline: "Make services, public value, partnerships and resources easier for communities and stakeholders to access." }, ["ngo", "institution", "public sector"]),
  p("newsroom-pro", "Newsroom Pro", "institution", "Editorial & media", "Editorial-first information template for publications, media companies and content-led organisations.", { primary: "#d82929", secondary: "#111111", accent: "#f5b43a", surface: "#f5f4f1", mood: "editorial" }, { primary: "#d82929", secondary: "#111111", accent: "#f5b43a", surface: "#f5f4f1", text: "#171717", fontFamily: "DM Sans", heroStyle: "minimal", navStyle: "dark", cardStyle: "bordered", buttonStyle: "square", radius: 4 }, { headline: "Stories with context. Information with weight.", tagline: "A publication-style experience for editorial teams, media brands and information-led organisations." }, ["news", "media", "publication"]),
  p("autodrive", "AutoDrive", "retail", "Automotive", "Performance automotive template for dealerships, workshops, mobility brands and premium vehicle services.", { primary: "#e73535", secondary: "#101216", accent: "#5f6671", surface: "#f3f4f5", mood: "dark" }, { primary: "#e73535", secondary: "#101216", accent: "#5f6671", surface: "#f3f4f5", text: "#17191d", fontFamily: "Manrope", heroStyle: "split", navStyle: "dark", cardStyle: "elevated", buttonStyle: "square", radius: 8 }, { headline: "Performance starts before the first drive.", tagline: "A high-impact automotive experience for vehicles, servicing, enquiries and premium mobility brands." }, ["automotive", "cars", "dealer"]),
  p("block-ledger", "Block Ledger", "technology", "Web3 & fintech", "Dark fintech/Web3 template with sharp interface styling, data confidence and investor-ready positioning.", { primary: "#7057ff", secondary: "#0c0d12", accent: "#32e0a1", surface: "#f3f2ff", mood: "dark" }, { primary: "#7057ff", secondary: "#0c0d12", accent: "#32e0a1", surface: "#f3f2ff", text: "#15151d", fontFamily: "Inter", heroStyle: "centered", navStyle: "dark", cardStyle: "glass", buttonStyle: "pill", radius: 20 }, { headline: "Financial infrastructure for the next layer of the internet.", tagline: "A credible product experience for fintech, digital assets, payments and emerging financial technology." }, ["fintech", "web3", "crypto", "payments"]),
  p("homecraft", "HomeCraft", "property", "Interior & architecture", "Refined architecture/interior template with calm typography, premium spacing and project-led storytelling.", { primary: "#8b6a50", secondary: "#2c2925", accent: "#c6a886", surface: "#f5f1ec", mood: "editorial" }, { primary: "#8b6a50", secondary: "#2c2925", accent: "#c6a886", surface: "#f5f1ec", text: "#2c2824", fontFamily: "Manrope", heroStyle: "minimal", navStyle: "clean", cardStyle: "bordered", buttonStyle: "square", radius: 6 }, { headline: "Spaces designed around how life is lived.", tagline: "An understated premium portfolio for interiors, architecture, furniture and property design studios." }, ["interior", "architecture", "design"]),
  p("sportforge", "SportForge", "healthcare", "Fitness & sport", "Energetic fitness template for gyms, coaches, sports brands and performance programmes.", { primary: "#ff5a1f", secondary: "#111317", accent: "#d8ff45", surface: "#f5f5f2", mood: "vivid" }, { primary: "#ff5a1f", secondary: "#111317", accent: "#d8ff45", surface: "#f5f5f2", text: "#17191b", fontFamily: "DM Sans", heroStyle: "split", navStyle: "dark", cardStyle: "elevated", buttonStyle: "square", radius: 10 }, { headline: "Train with intent. Perform with confidence.", tagline: "A high-energy site for memberships, coaching, programmes and performance-focused communities." }, ["fitness", "gym", "sport"]),
];

export const templateFamilies = ["All", ...Array.from(new Set(studioTemplates.map((template) => template.family)))] as const;

export function applyStudioTemplate(template: StudioTemplatePreset, businessName = "Your Business"): WebsiteStudioDraft {
  const base = createWebsiteDraft(businessName, template.category);
  return normalizeWebsiteDraft({
    ...base,
    templateKey: template.key as WebsiteStudioDraft["templateKey"],
    brand: { ...base.brand, ...template.brand },
    site: {
      ...base.site,
      ...template.site,
      announcement: `${template.name} premium starter · customise every section in Website Studio.`,
      showAnnouncement: false,
    },
    seo: {
      ...base.seo,
      description: `${template.site.tagline || base.site.tagline} Built with the ${template.name} Website Studio system.`,
      keywords: `${template.tags.join(", ")}, ${businessName.toLowerCase()}, south africa`,
    },
  });
}
