import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.3";
import { getWebsiteStudioProviderCredential } from "../_shared/website-studio-provider-credential.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
async function vercel(path:string,init:RequestInit,token:string,teamId?:string){const sep=path.includes("?")?"&":"?";const response=await fetch(`https://api.vercel.com${path}${teamId?`${sep}teamId=${encodeURIComponent(teamId)}`:""}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init.headers||{})}});const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{}if(!response.ok){const error=new Error(`VERCEL_${response.status}`);(error as any).status=response.status;throw error}return data}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);const url=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRole)return json({error:"Service unavailable"},503);const access=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();const admin=createClient(url,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}});const{data:userData}=await admin.auth.getUser(access);if(!userData.user)return json({error:"Authentication required"},401);let body:any;try{body=await req.json()}catch{return json({error:"Invalid request"},400)}const projectId=String(body?.projectId||""),domainId=String(body?.domainId||""),action=String(body?.action||"check");if(!projectId||!domainId)return json({error:"Project and domain required"},400);
 const[{data:project},{data:domain},{data:roles},{data:integration}]=await Promise.all([admin.from("website_studio_projects").select("id,owner_id,slug,integration_config").eq("id",projectId).single(),admin.from("website_studio_domains").select("*").eq("id",domainId).eq("project_id",projectId).single(),admin.from("user_roles").select("role").eq("user_id",userData.user.id),admin.from("website_studio_integrations").select("config,external_project_id").eq("project_id",projectId).eq("provider","vercel").maybeSingle()]);if(!project||!domain)return json({error:"Domain not found"},404);const isAdmin=(roles||[]).some((row:any)=>["admin","super_admin"].includes(String(row.role)));if(project.owner_id!==userData.user.id&&!isAdmin)return json({error:"Not authorized"},403);
 const config={...((project.integration_config||{}).vercel||{}),...(integration?.config||{})};const projectName=String(integration?.external_project_id||config.projectName||project.slug);const teamId=String(config.teamId||Deno.env.get("VERCEL_TEAM_ID")||"").trim()||undefined;const token=Deno.env.get("VERCEL_TOKEN")||await getWebsiteStudioProviderCredential(admin,serviceRole,projectId,"vercel");if(!token){await admin.from("website_studio_domains").update({status:"ready",dns_config:{guide:"Connect Vercel in Website Studio Integrations, then retry."},updated_at:new Date().toISOString()}).eq("id",domainId);return json({status:"ready",message:"Connect Vercel in Website Studio Integrations to automate this domain."},202)}
 try{
  if(action==="remove"){try{await vercel(`/v9/projects/${encodeURIComponent(projectName)}/domains/${encodeURIComponent(domain.hostname)}`,{method:"DELETE"},token,teamId)}catch(error){if((error as any)?.status!==404)throw error}await admin.from("website_studio_domains").update({status:"removed",ssl_status:"inactive",last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",domainId);return json({status:"removed"})}
  if(action==="connect"){try{await vercel(`/v10/projects/${encodeURIComponent(projectName)}/domains`,{method:"POST",body:JSON.stringify({name:domain.hostname})},token,teamId)}catch(error){if(![400,409].includes((error as any)?.status))throw error}}
  let projectDomain:any={};try{projectDomain=await vercel(`/v9/projects/${encodeURIComponent(projectName)}/domains/${encodeURIComponent(domain.hostname)}`,{method:"GET"},token,teamId)}catch{}let domainConfig:any={};try{domainConfig=await vercel(`/v6/domains/${encodeURIComponent(domain.hostname)}/config`,{method:"GET"},token,teamId)}catch{}
  const verified=Boolean(projectDomain?.verified);const misconfigured=Boolean(domainConfig?.misconfigured);const status=verified&&!misconfigured?"connected":action==="connect"?"pending_dns":"checking";const sslStatus=verified&&!misconfigured?"active":"pending";const dnsConfig={verified,misconfigured,configuredBy:domainConfig?.configuredBy||null,recommendedIPv4:domainConfig?.recommendedIPv4||null,recommendedCNAME:domainConfig?.recommendedCNAME||null,verification:projectDomain?.verification||[]};await admin.from("website_studio_domains").update({status,ssl_status:sslStatus,dns_config:dnsConfig,provider_config:{projectName,teamId:teamId||null},last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",domainId);return json({status,sslStatus,dnsConfig,message:verified&&!misconfigured?"Domain is connected and SSL-ready.":"Domain added. Follow the DNS values shown in your domain registrar, then choose Check again."});
 }catch(error){console.error("Website Studio domain operation failed",error);await admin.from("website_studio_domains").update({status:"error",last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",domainId);return json({status:"error",message:"The domain could not be updated. Check the Vercel connection and DNS, then retry."},502)}
});
