import { createFileRoute, Link } from "@tanstack/react-router";
import { BadgeCheck, Building2, CheckCircle2, ClipboardCheck, FileCheck2, FileSignature, FolderLock, Gavel, RefreshCw, Scale, ShieldCheck, Upload, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { AppShell } from "../../components/app-shell";
import { AuthDeferred } from "../../components/live-data-ui";
import { supabase } from "../../integrations/supabase/client";
import { listStartupWorkspaces, type StartupWorkspace } from "../../lib/startup-os-foundation";
import { addTenderRequirement, buildCofounderAgreement, buildContractDraft, calculateChecklistProgress, calculateWeightedReadiness, createContract, createDueDiligenceShare, createObligation, createSignatureRequest, createSupplierAssessment, createTender, ensureDefaultLegalSetup, loadLegalWorkspace, updateRequirement, updateSetupItem, uploadLegalDocument } from "../../lib/startup-os-phase7";
import "../../startup-os-phase7.css";

export const Route=createFileRoute("/app/compliance")({component:CompliancePage});
type Tab="overview"|"setup"|"documents"|"cofounder"|"contracts"|"esign"|"tenders"|"supplier"|"deadlines"|"verification"|"sharing";
const tabs:Array<{key:Tab;label:string}>=[{key:"overview",label:"Compliance Dashboard"},{key:"setup",label:"Company Setup"},{key:"documents",label:"Document Vault"},{key:"cofounder",label:"Co-founder Agreement"},{key:"contracts",label:"Contracts"},{key:"esign",label:"E-sign"},{key:"tenders",label:"Tender Readiness"},{key:"supplier",label:"Supplier Readiness"},{key:"deadlines",label:"Statutory Deadlines"},{key:"verification",label:"Verification Centre"},{key:"sharing",label:"Due Diligence"}];
const empty:any={setup:[],obligations:[],documents:[],contracts:[],signatureRequests:[],signatureRecipients:[],tenders:[],tenderRequirements:[],supplierAssessments:[],supplierRequirements:[],shares:[],verification:[],renewals:[],summary:{}};
function activeWorkspace(rows:StartupWorkspace[]){const stored=typeof window!=="undefined"?localStorage.getItem("start-to-up-active-workspace")||"":"";return rows.some(r=>r.organization_id===stored)?stored:rows[0]?.organization_id||"";}
const dt=(v:any)=>v?new Date(v).toLocaleDateString():"—";

function CompliancePage(){
  const [ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(true),[workspaces,setWorkspaces]=useState<StartupWorkspace[]>([]),[workspaceId,setWorkspaceId]=useState(""),[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<any>(empty),[notice,setNotice]=useState("");
  const setupProgress=useMemo(()=>calculateChecklistProgress(data.setup||[]),[data.setup]);
  useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSignedIn(Boolean(data.session));setReady(true)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(Boolean(s)));return()=>data.subscription.unsubscribe();},[]);
  async function refresh(id=workspaceId){if(!id)return;setBusy(true);try{await ensureDefaultLegalSetup(id);setData(await loadLegalWorkspace(id));}catch{setNotice("Compliance data could not be refreshed. Check your company access and try again.");}finally{setBusy(false)}}
  useEffect(()=>{if(!ready||!signedIn)return;void listStartupWorkspaces().then(rows=>{setWorkspaces(rows);const id=activeWorkspace(rows);setWorkspaceId(id);if(id)void refresh(id);else setBusy(false)}).catch(()=>{setNotice("No company workspace could be loaded.");setBusy(false)});},[ready,signedIn]);
  function changeWorkspace(id:string){setWorkspaceId(id);localStorage.setItem("start-to-up-active-workspace",id);void refresh(id);}
  async function submit(event:FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<any>,ok:string){event.preventDefault();if(!workspaceId)return;const form=event.currentTarget;setNotice("Saving…");try{await fn(new FormData(form));form.reset();setNotice(ok);await refresh();}catch{setNotice("That change could not be saved. Review the information and your workspace permission, then try again.");}}
  if(!ready||busy&&signedIn&&!workspaceId)return <AppShell title="Compliance Centre" eyebrow="PHASE 7 · LEGAL & COMPLIANCE"><div className="legal-loading"><RefreshCw className="spin"/> Restoring secure company records…</div></AppShell>;
  if(!signedIn)return <AppShell title="Compliance Centre" eyebrow="PHASE 7 · LEGAL & COMPLIANCE"><AuthDeferred/></AppShell>;
  const summary=data.summary||{},tenderReq=(id:string)=>data.tenderRequirements.filter((r:any)=>r.assessment_id===id),supplierReq=(id:string)=>data.supplierRequirements.filter((r:any)=>r.assessment_id===id);
  return <AppShell title="Compliance Centre" eyebrow="PHASE 7 · LEGAL, COMPLIANCE & ADMINISTRATION" action={<Link to="/app/operations" className="button button-secondary">Operations</Link>}>
    <section className="legal-toolbar"><div><span>ACTIVE COMPANY</span><select value={workspaceId} onChange={e=>changeWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.organization_id} value={w.organization_id}>{w.name}</option>)}</select></div><button onClick={()=>void refresh()}><RefreshCw size={16}/> Refresh</button></section>
    {notice?<p className="legal-notice" role="status">{notice}</p>:null}
    <nav className="legal-tabs" aria-label="Compliance tools">{tabs.map(t=><button key={t.key} className={tab===t.key?"active":""} onClick={()=>setTab(t.key)}>{t.label}</button>)}</nav>

    {tab==="overview"?<><section className="legal-kpis"><article><ShieldCheck/><div><span>Compliance health</span><strong>{Number(summary.score||0)}%</strong><small>derived from workspace records</small></div></article><article><ClipboardCheck/><div><span>Company setup</span><strong>{Math.round(setupProgress)}%</strong><small>{summary.setup_complete||0}/{summary.setup_total||0} completed</small></div></article><article><FolderLock/><div><span>Current documents</span><strong>{summary.current_documents||0}</strong><small>{summary.expiring_documents||0} private dates need attention</small></div></article><article><FileSignature/><div><span>Signature workflows</span><strong>{summary.open_signature_requests||0}</strong><small>open requests</small></div></article></section><div className="legal-grid"><section className="legal-panel"><header><Scale/><div><span>PRIVATE-BY-DEFAULT</span><h2>Your compliance operating record.</h2></div></header><p>Legal and verification documents stay private. Dates, private identifiers and uploaded evidence are workspace records—not public website content.</p><div className="legal-flow"><b>Evidence</b><i>→</i><b>Compliance</b><i>→</i><b>Contracts</b><i>→</i><b>Signatures</b><i>→</i><b>Due diligence</b></div></section><section className="legal-panel"><header><Gavel/><div><span>IMPORTANT</span><h2>Drafting assistance, not legal advice.</h2></div></header><p>The agreement and contract builders create structured working drafts. Founders remain responsible for confirming legal, tax, employment, procurement and regulatory requirements that apply to their company and transaction.</p></section></div></>:null}

    {tab==="setup"?<div className="legal-grid"><section className="legal-panel"><h2>Company Setup Checklist</h2><p>Reusable South Africa-first checklist. Evidence can be linked privately without publishing certificate or registration dates.</p><div className="legal-checklist">{data.setup.map((x:any)=><article key={x.id}><div><strong>{x.title}</strong><span>{x.category}</span></div><select value={x.status} onChange={e=>void updateSetupItem(x.id,{status:e.target.value,completed_at:e.target.value==="complete"?new Date().toISOString():null}).then(()=>refresh())}><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="complete">Complete</option><option value="not_applicable">N/A</option></select></article>)}</div></section><section className="legal-panel"><h2>Progress</h2><div className="legal-score-ring"><strong>{Math.round(setupProgress)}%</strong><span>setup readiness</span></div><p>Complete only items that are actually evidenced. “Not applicable” removes an item from your operational to-do list; it is not a verification claim.</p></section></div>:null}

    {tab==="documents"?<div className="legal-grid"><section className="legal-panel"><h2>Private Document Vault</h2><form className="legal-form" onSubmit={e=>void submit(e,async fd=>{const file=fd.get("file");if(!(file instanceof File)||!file.size)throw new Error("file");await uploadLegalDocument(workspaceId,file,{title:String(fd.get("title")),document_type:String(fd.get("type")),public_safe_label:String(fd.get("label")||""),expiry_date:String(fd.get("expiry")||"")||undefined});},"Document uploaded to the private company vault.")}><label>Document title<input name="title" required/></label><label>Type<select name="type"><option value="company_registration">Company registration</option><option value="tax">Tax</option><option value="bee">B-BBEE</option><option value="financial">Financial</option><option value="bank">Bank</option><option value="insurance">Insurance</option><option value="policy">Policy</option><option value="contract">Contract</option><option value="tender">Tender</option><option value="supplier">Supplier</option><option value="other">Other</option></select></label><label>Public-safe label<input name="label" placeholder="e.g. Tax registration confirmed"/></label><label>Private expiry/reminder date<input type="date" name="expiry"/></label><label className="wide file-field"><Upload size={18}/> File<input type="file" name="file" required/></label><button className="button button-primary wide">Upload securely</button></form></section><section className="legal-panel"><h2>Documents</h2><div className="legal-list">{data.documents.map((d:any)=><article key={d.id}><FileCheck2/><div><strong>{d.title}</strong><span>{d.document_type} · {d.verification_status}</span></div><b>{d.status}</b></article>)}{!data.documents.length?<p>No private documents uploaded yet.</p>:null}</div></section></div>:null}

    {tab==="cofounder"?<section className="legal-panel"><header><UsersRound/><div><span>CO-FOUNDER AGREEMENT BUILDER</span><h2>Structure the founder relationship before it becomes a dispute.</h2></div></header><form className="legal-form" onSubmit={e=>void submit(e,async fd=>{const title=String(fd.get("title")||"Co-founder Agreement");const body=buildCofounderAgreement({company:String(fd.get("company")),founders:String(fd.get("founders")).split(",").map(x=>x.trim()).filter(Boolean),equity:String(fd.get("equity")),roles:String(fd.get("roles")),vesting:String(fd.get("vesting")),ip:String(fd.get("ip")),decisions:String(fd.get("decisions")),exit:String(fd.get("exit")),disputes:String(fd.get("disputes")),noticeDays:Number(fd.get("notice")||30)});await createContract(workspaceId,{title,contract_type:"cofounder",body,termination_notice_days:Number(fd.get("notice")||30)});},"Co-founder agreement draft saved for review.")}><label>Draft title<input name="title" defaultValue="Co-founder Agreement"/></label><label>Company<input name="company" required/></label><label className="wide">Founders, comma separated<input name="founders" required/></label><label className="wide">Equity arrangement<textarea name="equity" required/></label><label className="wide">Roles and responsibilities<textarea name="roles" required/></label><label className="wide">Vesting / earning terms<textarea name="vesting" required/></label><label className="wide">Intellectual property<textarea name="ip" required/></label><label className="wide">Decision rights<textarea name="decisions" required/></label><label className="wide">Founder exit / transfer<textarea name="exit" required/></label><label className="wide">Dispute process<textarea name="disputes" required/></label><label>Notice days<input type="number" name="notice" min="0" defaultValue="30"/></label><button className="button button-primary wide">Create review draft</button></form></section>:null}

    {tab==="contracts"?<div className="legal-grid"><section className="legal-panel"><h2>Contract Builder</h2><form className="legal-form" onSubmit={e=>void submit(e,async fd=>{const title=String(fd.get("title"));const body=buildContractDraft({title,parties:String(fd.get("parties")),scope:String(fd.get("scope")),fees:String(fd.get("fees")),term:String(fd.get("term")),confidentiality:String(fd.get("confidentiality")),ip:String(fd.get("ip")),termination:String(fd.get("termination")),disputes:String(fd.get("disputes"))});await createContract(workspaceId,{title,contract_type:String(fd.get("type")),body});},"Contract draft saved.")}><label>Title<input name="title" required/></label><label>Type<select name="type"><option>services</option><option>nda</option><option>partnership</option><option>contractor</option><option>employment</option><option>supplier</option><option>licence</option><option>other</option></select></label><label className="wide">Parties<textarea name="parties" required/></label><label className="wide">Scope<textarea name="scope" required/></label><label className="wide">Fees & payment<textarea name="fees" required/></label><label className="wide">Term<textarea name="term" required/></label><label className="wide">Confidentiality<textarea name="confidentiality"/></label><label className="wide">IP<textarea name="ip"/></label><label className="wide">Termination<textarea name="termination" required/></label><label className="wide">Disputes<textarea name="disputes"/></label><button className="button button-primary wide">Save contract draft</button></form></section><section className="legal-panel"><h2>Contracts</h2><div className="legal-list">{data.contracts.map((c:any)=><article key={c.id}><FileSignature/><div><strong>{c.title}</strong><span>{c.contract_type} · v{c.version}</span></div><b>{c.status}</b></article>)}</div></section></div>:null}

    {tab==="esign"?<div className="legal-grid"><section className="legal-panel"><h2>E-signature Workflow</h2><p>Create an auditable signing request. The signer uses a unique token; consent, signature hash, time and access events are recorded.</p><form className="legal-form" onSubmit={e=>void submit(e,fd=>createSignatureRequest(workspaceId,String(fd.get("contract")),String(fd.get("title")),{name:String(fd.get("name")),email:String(fd.get("email"))},String(fd.get("expires")||"")||undefined),"Signature request created.")}><label>Contract<select name="contract" required><option value="">Select</option>{data.contracts.map((c:any)=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>Request title<input name="title" required/></label><label>Signer name<input name="name" required/></label><label>Signer email<input type="email" name="email" required/></label><label>Expires<input type="datetime-local" name="expires"/></label><button className="button button-primary wide">Create signing request</button></form></section><section className="legal-panel"><h2>Requests</h2><div className="legal-list">{data.signatureRequests.map((r:any)=><article key={r.id}><FileSignature/><div><strong>{r.title}</strong><span>{r.expires_at?`private expiry ${dt(r.expires_at)}`:"no expiry set"}</span></div><b>{r.status}</b></article>)}</div></section></div>:null}

    {tab==="tenders"?<div className="legal-grid"><section className="legal-panel"><h2>Tender Readiness Tool</h2><form className="legal-form" onSubmit={e=>void submit(e,fd=>createTender(workspaceId,{tender_name:String(fd.get("name")),issuer:String(fd.get("issuer")||""),reference:String(fd.get("reference")||""),source_url:String(fd.get("url")||"")||null,closing_at:String(fd.get("closing")||"")||null}),"Tender assessment created.")}><label>Tender name<input name="name" required/></label><label>Issuer<input name="issuer"/></label><label>Reference<input name="reference"/></label><label>Source URL<input type="url" name="url"/></label><label>Closing date<input type="datetime-local" name="closing"/></label><button className="button button-primary wide">Create assessment</button></form>{data.tenders[0]?<form className="legal-form add-requirement" onSubmit={e=>void submit(e,fd=>addTenderRequirement(workspaceId,String(fd.get("assessment")),{requirement:String(fd.get("requirement")),category:String(fd.get("category")||"document"),weight:Number(fd.get("weight")||10)}),"Tender requirement added.")}><label>Assessment<select name="assessment">{data.tenders.map((t:any)=><option value={t.id} key={t.id}>{t.tender_name}</option>)}</select></label><label>Requirement<input name="requirement" required/></label><label>Category<input name="category" defaultValue="document"/></label><label>Weight<input type="number" min="1" max="100" name="weight" defaultValue="10"/></label><button className="button button-secondary wide">Add requirement</button></form>:null}</section><section className="legal-panel"><h2>Assessments</h2>{data.tenders.map((t:any)=>{const rows=tenderReq(t.id),score=calculateWeightedReadiness(rows);return <article className="legal-readiness" key={t.id}><header><div><strong>{t.tender_name}</strong><span>{t.issuer||"Issuer not set"}</span></div><b>{Math.round(score)}%</b></header>{rows.map((r:any)=><div className="requirement-row" key={r.id}><span>{r.requirement}</span><select value={r.status} onChange={e=>void updateRequirement("legal_tender_requirements",r.id,{status:e.target.value}).then(()=>refresh())}><option>missing</option><option>in_progress</option><option>met</option><option>not_applicable</option></select></div>)}</article>})}</section></div>:null}

    {tab==="supplier"?<div className="legal-grid"><section className="legal-panel"><h2>Supplier Readiness Score</h2><form className="legal-form" onSubmit={e=>void submit(e,fd=>createSupplierAssessment(workspaceId,String(fd.get("customer")||"")),"Supplier-readiness assessment created with a standard procurement checklist.")}><label>Target customer / procurement programme<input name="customer"/></label><button className="button button-primary wide">Start supplier assessment</button></form><p>Readiness is weighted from actual requirements marked met, not self-declared company quality.</p></section><section className="legal-panel"><h2>Assessments</h2>{data.supplierAssessments.map((a:any)=>{const rows=supplierReq(a.id),score=calculateWeightedReadiness(rows);return <article className="legal-readiness" key={a.id}><header><div><strong>{a.name}</strong><span>{a.target_customer||"General supplier pack"}</span></div><b>{Math.round(score)}%</b></header>{rows.map((r:any)=><div className="requirement-row" key={r.id}><span>{r.title}</span><select value={r.status} onChange={e=>void updateRequirement("legal_supplier_requirements",r.id,{status:e.target.value}).then(()=>refresh())}><option>missing</option><option>in_progress</option><option>met</option><option>not_applicable</option></select></div>)}</article>})}</section></div>:null}

    {tab==="deadlines"?<div className="legal-grid"><section className="legal-panel"><h2>Compliance & Statutory Deadlines</h2><form className="legal-form" onSubmit={e=>void submit(e,fd=>createObligation(workspaceId,{title:String(fd.get("title")),authority:String(fd.get("authority")||""),category:String(fd.get("category")),due_date:String(fd.get("due")||"")||null,recurrence:String(fd.get("recurrence")),reminder_days:Number(fd.get("reminder")||30),source_url:String(fd.get("source")||"")||null}),"Compliance obligation added.")}><label>Obligation<input name="title" required/></label><label>Authority / source<input name="authority"/></label><label>Category<select name="category"><option>company</option><option>tax</option><option>bee</option><option>privacy</option><option>employment</option><option>licence</option><option>insurance</option><option>procurement</option><option>compliance</option><option>other</option></select></label><label>Private due date<input type="date" name="due"/></label><label>Recurrence<select name="recurrence"><option>once</option><option>monthly</option><option>quarterly</option><option>biannual</option><option>annual</option><option>custom</option></select></label><label>Reminder days<input type="number" name="reminder" min="0" max="365" defaultValue="30"/></label><label className="wide">Official/source URL<input type="url" name="source"/></label><button className="button button-primary wide">Track obligation</button></form></section><section className="legal-panel"><h2>Private deadline register</h2><div className="legal-list">{[...data.obligations,...data.renewals].map((x:any)=><article key={`${x.id}-${x.title||x.name}`}><CheckCircle2/><div><strong>{x.title||x.name}</strong><span>{x.category||x.authority||"obligation"}</span></div><b>{dt(x.due_date)}</b></article>)}</div><p className="privacy-note">Dates in this workspace are operational reminders only. Start To Up’s public company pages do not publish registration dates, certificate issue dates or certificate expiry dates.</p></section></div>:null}

    {tab==="verification"?<section className="legal-panel"><header><BadgeCheck/><div><span>VERIFICATION-DOCUMENT CENTRE</span><h2>Separate public trust from private evidence.</h2></div></header><div className="legal-list">{data.verification.map((v:any)=><article key={v.id}><BadgeCheck/><div><strong>{v.label||v.kind||"Verification record"}</strong><span>{v.public_label||"Private evidence record"}</span></div><b>{v.status}</b></article>)}</div><p>Only neutral Start To Up trust labels belong on public surfaces. Regulator/public-body logos remain controlled by the Phase 0 permission registry and cannot be enabled merely because a certificate exists.</p></section>:null}

    {tab==="sharing"?<div className="legal-grid"><section className="legal-panel"><h2>Private Due-Diligence Sharing</h2><p>Create an expiring, auditable share. The public token exposes only the documents explicitly selected for that share and uses short-lived signed file URLs.</p><form className="legal-form" onSubmit={e=>void submit(e,fd=>createDueDiligenceShare(workspaceId,String(fd.get("name")),fd.getAll("documents").map(String),String(fd.get("expires")),Number(fd.get("views")||0)||undefined),"Private due-diligence share created.")}><label>Name<input name="name" required/></label><label>Expires<input type="datetime-local" name="expires" required/></label><label>Maximum views<input type="number" min="1" name="views"/></label><fieldset className="wide"><legend>Documents</legend>{data.documents.map((d:any)=><label className="doc-choice" key={d.id}><input type="checkbox" name="documents" value={d.id}/>{d.title}</label>)}</fieldset><button className="button button-primary wide">Create private share</button></form></section><section className="legal-panel"><h2>Active shares</h2><div className="legal-list">{data.shares.map((s:any)=><article key={s.id}><FolderLock/><div><strong>{s.name}</strong><span>{s.view_count} views · {s.revoked_at?"revoked":"active"}</span></div><a href={`/due-diligence?token=${s.public_token}`} target="_blank" rel="noreferrer">Open</a></article>)}</div></section></div>:null}
  </AppShell>;
}
