import { createFileRoute, Link } from "@tanstack/react-router";
import { BarChart3, CalendarDays, ExternalLink, Gauge, Link2, Megaphone, RefreshCw, Search, Target, TestTube2, TrendingUp, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { AppShell } from "../../components/app-shell";
import { AuthDeferred } from "../../components/live-data-ui";
import { supabase } from "../../integrations/supabase/client";
import { listStartupWorkspaces, type StartupWorkspace } from "../../lib/startup-os-foundation";
import { addContentItem, addExperiment, addKpi, addPaidMediaSnapshot, addSeoTarget, calculateCampaignEfficiency, calculateMarketingBudget, calculateRetention, createCampaign, createUtmLink, loadGrowthWorkspace, recordKpi, recordRetention } from "../../lib/startup-os-phase5";
import "../../startup-os-phase5.css";

export const Route=createFileRoute("/app/growth")({component:GrowthPage});
type Tab="overview"|"campaigns"|"budget"|"content"|"utm"|"seo"|"experiments"|"kpis"|"retention"|"attribution"|"paid";
const tabs:Array<{key:Tab;label:string}>=[
  {key:"overview",label:"Overview"},{key:"campaigns",label:"Campaign Planner"},{key:"budget",label:"Budget"},{key:"content",label:"Content Calendar"},{key:"utm",label:"UTM Builder"},{key:"seo",label:"SEO Growth"},{key:"experiments",label:"Experiments"},{key:"kpis",label:"KPI Dashboard"},{key:"retention",label:"Retention"},{key:"attribution",label:"Attribution"},{key:"paid",label:"Paid Media"},
];
const empty:any={campaigns:[],content:[],utms:[],seoTargets:[],seoAudits:[],experiments:[],kpis:[],kpiMeasurements:[],retention:[],paidMedia:[],attribution:[]};
const n=(fd:FormData,k:string)=>Number(fd.get(k)||0)||0;
function activeWorkspace(rows:StartupWorkspace[]){const stored=typeof window!=="undefined"?localStorage.getItem("start-to-up-active-workspace")||"":"";return rows.some(r=>r.organization_id===stored)?stored:rows[0]?.organization_id||"";}

function GrowthPage(){
  const [ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(true); const [workspaces,setWorkspaces]=useState<StartupWorkspace[]>([]),[workspaceId,setWorkspaceId]=useState(""),[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<any>(empty),[notice,setNotice]=useState("");
  const [budgetTotal,setBudgetTotal]=useState(10000),[budgetMeta,setBudgetMeta]=useState(40),[budgetGoogle,setBudgetGoogle]=useState(30),[budgetContent,setBudgetContent]=useState(20),[budgetOther,setBudgetOther]=useState(10);
  const budget=useMemo(()=>calculateMarketingBudget(budgetTotal,[{channel:"Meta",percent:budgetMeta},{channel:"Google / Search",percent:budgetGoogle},{channel:"Content",percent:budgetContent},{channel:"Other",percent:budgetOther}]),[budgetTotal,budgetMeta,budgetGoogle,budgetContent,budgetOther]);
  const latestRetention=data.retention?.[0];
  const totals=useMemo(()=>{const attrs=data.attribution||[];return{spend:attrs.reduce((s:any,r:any)=>s+Number(r.actual_spend||0),0),revenue:attrs.reduce((s:any,r:any)=>s+Number(r.invoice_value||0),0),leads:attrs.reduce((s:any,r:any)=>s+Number(r.leads||0),0)};},[data.attribution]);
  const efficiency=calculateCampaignEfficiency(totals.spend,totals.revenue,totals.leads,0);

  useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSignedIn(Boolean(data.session));setReady(true)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(Boolean(s)));return()=>data.subscription.unsubscribe();},[]);
  async function refresh(id=workspaceId){if(!id)return;setBusy(true);try{setData(await loadGrowthWorkspace(id));}catch{setNotice("Growth workspace could not be refreshed. Check your workspace access and try again.");}finally{setBusy(false)}}
  useEffect(()=>{if(!ready||!signedIn)return;void listStartupWorkspaces().then(rows=>{setWorkspaces(rows);const id=activeWorkspace(rows);setWorkspaceId(id);if(id)void refresh(id);}).catch(()=>{setNotice("No company workspace could be loaded.");setBusy(false)});},[ready,signedIn]);
  function changeWorkspace(id:string){setWorkspaceId(id);localStorage.setItem("start-to-up-active-workspace",id);void refresh(id);}
  async function submit(event:FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<any>,ok:string){event.preventDefault();if(!workspaceId)return;const el=event.currentTarget;setNotice("Saving…");try{await fn(new FormData(el));el.reset();setNotice(ok);await refresh();}catch{setNotice("That change could not be saved. Review the fields and your workspace permission, then try again.");}}

  if(!ready||busy&&signedIn&&!workspaceId)return <AppShell title="Growth" eyebrow="PHASE 5 · MARKETING & GROWTH"><div className="growth-loading"><RefreshCw className="spin"/> Restoring growth workspace…</div></AppShell>;
  if(!signedIn)return <AppShell title="Growth" eyebrow="PHASE 5 · MARKETING & GROWTH"><AuthDeferred/></AppShell>;

  return <AppShell title="Growth" eyebrow="PHASE 5 · MARKETING & GROWTH" action={<Link to="/app/integrations" className="button button-secondary">Integrations</Link>}>
    <section className="growth-toolbar"><div><span>ACTIVE COMPANY</span><select value={workspaceId} onChange={e=>changeWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.organization_id} value={w.organization_id}>{w.name}</option>)}</select></div><button onClick={()=>void refresh()}><RefreshCw size={16}/> Refresh</button></section>
    {notice?<p className="growth-notice" role="status">{notice}</p>:null}
    <nav className="growth-tabs" aria-label="Growth tools">{tabs.map(t=><button key={t.key} className={tab===t.key?"active":""} onClick={()=>setTab(t.key)}>{t.label}</button>)}</nav>

    {tab==="overview"?<><section className="growth-kpis"><article><Megaphone/><div><span>Campaigns</span><strong>{data.campaigns.length}</strong><small>{data.campaigns.filter((c:any)=>c.status==="active").length} active</small></div></article><article><TrendingUp/><div><span>Attributed revenue</span><strong>R {Math.round(totals.revenue).toLocaleString()}</strong><small>linked campaign value</small></div></article><article><BarChart3/><div><span>ROAS</span><strong>{efficiency.roas===null?"—":`${efficiency.roas.toFixed(2)}×`}</strong><small>revenue ÷ recorded spend</small></div></article><article><UsersRound/><div><span>Retention</span><strong>{latestRetention?`${Number(latestRetention.retention_rate||0).toFixed(1)}%`:"—"}</strong><small>latest measured period</small></div></article></section><div className="growth-grid"><section className="growth-panel"><header><Target/><div><span>REVENUE-CONNECTED MARKETING</span><h2>Campaigns should end in CRM outcomes.</h2></div></header><p>Use one campaign ID from planning through UTM links, content, leads, opportunities and invoices. Attribution remains evidence-labelled rather than invented.</p><div className="growth-flow"><b>Campaign</b><i>→</i><b>UTM</b><i>→</i><b>Lead</b><i>→</i><b>Opportunity</b><i>→</i><b>Invoice</b></div></section><section className="growth-panel"><header><Gauge/><div><span>NEXT ACTIONS</span><h2>Keep the growth loop measurable.</h2></div></header><ul><li>Create an active campaign before publishing content.</li><li>Use generated UTM links on every measurable campaign CTA.</li><li>Record paid-media metrics as verified only when owner-connected.</li><li>Link won revenue back to the originating campaign.</li></ul></section></div></>:null}

    {tab==="campaigns"?<div className="growth-grid"><section className="growth-panel"><h2>Campaign Planner</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>createCampaign(workspaceId,{name:String(fd.get("name")),objective:String(fd.get("objective")),status:String(fd.get("status")),audience:String(fd.get("audience")||""),offer:String(fd.get("offer")||""),primary_channel:String(fd.get("channel")||""),budget:n(fd,"budget"),start_date:fd.get("start")||null,end_date:fd.get("end")||null}),"Campaign saved.")}><label>Name<input name="name" required/></label><label>Objective<select name="objective"><option value="awareness">Awareness</option><option value="traffic">Traffic</option><option value="leads">Leads</option><option value="sales">Sales</option><option value="retention">Retention</option><option value="launch">Launch</option></select></label><label>Status<select name="status"><option>draft</option><option>planned</option><option>active</option><option>paused</option><option>completed</option></select></label><label>Primary channel<input name="channel" placeholder="Meta, Search, TikTok, Email…"/></label><label>Audience<input name="audience"/></label><label>Offer<input name="offer"/></label><label>Budget<input type="number" min="0" step="0.01" name="budget"/></label><label>Start<input type="date" name="start"/></label><label>End<input type="date" name="end"/></label><button className="button button-primary wide">Create campaign</button></form></section><section className="growth-panel"><h2>Campaigns</h2><div className="growth-list">{data.campaigns.map((c:any)=><article key={c.id}><div><strong>{c.name}</strong><span>{c.objective} · {c.primary_channel||"multi-channel"}</span></div><b>{c.status}</b><small>R {Number(c.budget||0).toLocaleString()}</small></article>)}{!data.campaigns.length?<p>No campaigns yet.</p>:null}</div></section></div>:null}

    {tab==="budget"?<section className="growth-panel"><header><BarChart3/><div><span>MARKETING BUDGET CALCULATOR</span><h2>Allocate before spending.</h2></div></header><div className="budget-layout"><div className="growth-form"><label>Total budget<input type="number" value={budgetTotal} onChange={e=>setBudgetTotal(Number(e.target.value)||0)}/></label><label>Meta %<input type="number" value={budgetMeta} onChange={e=>setBudgetMeta(Number(e.target.value)||0)}/></label><label>Google / Search %<input type="number" value={budgetGoogle} onChange={e=>setBudgetGoogle(Number(e.target.value)||0)}/></label><label>Content %<input type="number" value={budgetContent} onChange={e=>setBudgetContent(Number(e.target.value)||0)}/></label><label>Other %<input type="number" value={budgetOther} onChange={e=>setBudgetOther(Number(e.target.value)||0)}/></label></div><div className="budget-results"><strong>{budget.allocatedPercent.toFixed(1)}% allocated</strong>{budget.rows.map(r=><article key={r.channel}><span>{r.channel}</span><b>R {Math.round(r.amount).toLocaleString()}</b></article>)}<p className={Math.abs(budget.unallocatedPercent)<0.01?"good":"warn"}>{Math.abs(budget.unallocatedPercent)<0.01?"Budget fully allocated.":`${budget.unallocatedPercent.toFixed(1)}% remains/unbalances the plan.`}</p></div></div></section>:null}

    {tab==="content"?<div className="growth-grid"><section className="growth-panel"><h2>Content Calendar</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>addContentItem(workspaceId,{campaign_id:fd.get("campaign_id")||null,title:String(fd.get("title")),content_type:String(fd.get("type")),channel:String(fd.get("channel")||""),status:String(fd.get("status")),publish_at:fd.get("publish_at")||null,brief:String(fd.get("brief")||"")}),"Content item added.")}><label>Title<input name="title" required/></label><label>Campaign<select name="campaign_id"><option value="">No campaign</option>{data.campaigns.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Type<select name="type"><option>social</option><option>video</option><option>blog</option><option>email</option><option>landing_page</option><option>ad</option><option>event</option></select></label><label>Channel<input name="channel"/></label><label>Status<select name="status"><option>idea</option><option>draft</option><option>review</option><option>scheduled</option><option>published</option></select></label><label>Publish at<input type="datetime-local" name="publish_at"/></label><label className="wide">Brief<textarea name="brief"/></label><button className="button button-primary wide">Add to calendar</button></form></section><section className="growth-panel"><h2>Upcoming</h2><div className="growth-list">{data.content.map((x:any)=><article key={x.id}><CalendarDays/><div><strong>{x.title}</strong><span>{x.channel||x.content_type}</span></div><b>{x.status}</b></article>)}</div></section></div>:null}

    {tab==="utm"?<div className="growth-grid"><section className="growth-panel"><h2>UTM Campaign Builder</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>createUtmLink(workspaceId,{campaign_id:String(fd.get("campaign_id")||"")||null,name:String(fd.get("name")),destination_url:String(fd.get("url")),source:String(fd.get("source")),medium:String(fd.get("medium")),campaign:String(fd.get("campaign")),term:String(fd.get("term")||""),content:String(fd.get("content")||"")}),"Tracked campaign link created.")}><label>Name<input name="name" required/></label><label>Destination URL<input type="url" name="url" required/></label><label>Campaign record<select name="campaign_id"><option value="">None</option>{data.campaigns.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>utm_source<input name="source" required placeholder="facebook"/></label><label>utm_medium<input name="medium" required placeholder="paid_social"/></label><label>utm_campaign<input name="campaign" required/></label><label>utm_term<input name="term"/></label><label>utm_content<input name="content"/></label><button className="button button-primary wide">Generate & save</button></form></section><section className="growth-panel"><h2>Tracked links</h2><div className="growth-list">{data.utms.map((u:any)=><article key={u.id}><Link2/><div><strong>{u.name}</strong><a href={u.final_url} target="_blank" rel="noreferrer">{u.final_url}<ExternalLink size={12}/></a></div><b>{u.clicks} clicks</b></article>)}</div></section></div>:null}

    {tab==="seo"?<div className="growth-grid"><section className="growth-panel"><h2>SEO Growth Centre</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>addSeoTarget(workspaceId,{keyword:String(fd.get("keyword")),target_url:String(fd.get("target_url")||""),location:String(fd.get("location")||""),intent:String(fd.get("intent")),priority:n(fd,"priority"),evidence_confidence:"owner_entered"}),"SEO target saved.")}><label>Keyword<input name="keyword" required/></label><label>Target URL<input type="url" name="target_url"/></label><label>Location<input name="location" placeholder="Pretoria, South Africa"/></label><label>Intent<select name="intent"><option>commercial</option><option>transactional</option><option>informational</option><option>local</option><option>navigational</option></select></label><label>Priority<input type="number" name="priority" min="0" max="100" defaultValue="60"/></label><button className="button button-primary wide">Add SEO target</button></form><p className="growth-disclosure">Search volume, difficulty and ranking data must remain <b>Estimated</b> unless a connected provider supplies verified owner data.</p></section><section className="growth-panel"><h2>Keyword targets</h2><div className="growth-list">{data.seoTargets.map((s:any)=><article key={s.id}><Search/><div><strong>{s.keyword}</strong><span>{s.location||s.intent}</span></div><b>{s.priority}/100</b><small>{s.evidence_confidence}</small></article>)}</div></section></div>:null}

    {tab==="experiments"?<div className="growth-grid"><section className="growth-panel"><h2>Growth Experiment Tracker</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>addExperiment(workspaceId,{campaign_id:fd.get("campaign_id")||null,name:String(fd.get("name")),hypothesis:String(fd.get("hypothesis")),metric:String(fd.get("metric")),baseline:n(fd,"baseline"),target:n(fd,"target"),status:"planned"}),"Experiment created.")}><label>Name<input name="name" required/></label><label>Campaign<select name="campaign_id"><option value="">None</option>{data.campaigns.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Metric<input name="metric" required/></label><label>Baseline<input type="number" step="0.01" name="baseline"/></label><label>Target<input type="number" step="0.01" name="target"/></label><label className="wide">Hypothesis<textarea name="hypothesis" required placeholder="If we… then… because…"/></label><button className="button button-primary wide">Create experiment</button></form></section><section className="growth-panel"><h2>Experiment backlog</h2><div className="growth-list">{data.experiments.map((x:any)=><article key={x.id}><TestTube2/><div><strong>{x.name}</strong><span>{x.metric} · target {x.target??"—"}</span></div><b>{x.status}</b></article>)}</div></section></div>:null}

    {tab==="kpis"?<div className="growth-grid"><section className="growth-panel"><h2>KPI Dashboard Builder</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>addKpi(workspaceId,{name:String(fd.get("name")),category:String(fd.get("category")||"growth"),unit:String(fd.get("unit")||"number"),target:n(fd,"target"),direction:String(fd.get("direction")),source:"manual"}),"KPI added.")}><label>Name<input name="name" required/></label><label>Category<input name="category" defaultValue="growth"/></label><label>Unit<select name="unit"><option>number</option><option>percent</option><option>ZAR</option><option>ratio</option></select></label><label>Target<input type="number" step="0.01" name="target"/></label><label>Direction<select name="direction"><option>up</option><option>down</option><option>maintain</option></select></label><button className="button button-primary wide">Add KPI</button></form></section><section className="growth-panel"><h2>Metrics</h2><div className="growth-list">{data.kpis.map((k:any)=>{const latest=data.kpiMeasurements.find((m:any)=>m.kpi_id===k.id);return <article key={k.id}><Gauge/><div><strong>{k.name}</strong><span>Target {k.target??"—"} {k.unit}</span></div><b>{latest?latest.value:"—"}</b><button onClick={async()=>{const raw=prompt(`Record ${k.name}`);if(raw!==null&&Number.isFinite(Number(raw))){await recordKpi(workspaceId,k.id,Number(raw));await refresh();}}}>Record</button></article>})}</div></section></div>:null}

    {tab==="retention"?<div className="growth-grid"><section className="growth-panel"><h2>Churn / Retention Tracker</h2><form className="growth-form" onSubmit={e=>void submit(e,fd=>recordRetention(workspaceId,{period_start:String(fd.get("start")),period_end:String(fd.get("end")),starting_customers:n(fd,"starting"),new_customers:n(fd,"new"),ending_customers:n(fd,"ending")}),"Retention period saved.")}><label>Period start<input type="date" name="start" required/></label><label>Period end<input type="date" name="end" required/></label><label>Starting customers<input type="number" min="0" name="starting" required/></label><label>New customers<input type="number" min="0" name="new" required/></label><label>Ending customers<input type="number" min="0" name="ending" required/></label><button className="button button-primary wide">Calculate & save</button></form></section><section className="growth-panel"><h2>Periods</h2><div className="growth-list">{data.retention.map((r:any)=><article key={r.id}><UsersRound/><div><strong>{Number(r.retention_rate||0).toFixed(1)}% retention</strong><span>{r.period_start} → {r.period_end}</span></div><b>{Number(r.churn_rate||0).toFixed(1)}% churn</b></article>)}</div></section></div>:null}

    {tab==="attribution"?<section className="growth-panel"><header><TrendingUp/><div><span>CAMPAIGN ATTRIBUTION</span><h2>Follow recorded evidence to revenue.</h2></div></header><p className="growth-disclosure">Attribution only includes revenue explicitly linked through campaign touchpoints. It does not infer hidden ad-platform conversions.</p><div className="attribution-table"><div className="head"><b>Campaign</b><b>Spend</b><b>Leads</b><b>Opportunities</b><b>Revenue</b><b>ROAS</b></div>{data.attribution.map((a:any)=><div key={a.campaign_id}><span>{a.campaign_name}</span><span>R {Number(a.actual_spend||0).toLocaleString()}</span><span>{a.leads}</span><span>{a.opportunities}</span><span>R {Number(a.invoice_value||0).toLocaleString()}</span><span>{a.roas?`${Number(a.roas).toFixed(2)}×`:"—"}</span></div>)}</div></section>:null}

    {tab==="paid"?<div className="growth-grid"><section className="growth-panel"><h2>Paid-media integration centre</h2><p>Connect owner-authorised Meta, Google Analytics and Search Console data through the global Integration Centre. Record imported/manual campaign snapshots here with an evidence label.</p><Link to="/app/integrations" className="button button-primary">Open integrations</Link><form className="growth-form spaced" onSubmit={e=>void submit(e,fd=>addPaidMediaSnapshot(workspaceId,{campaign_id:fd.get("campaign_id")||null,provider:String(fd.get("provider")),spend:n(fd,"spend"),impressions:n(fd,"impressions"),clicks:n(fd,"clicks"),leads:n(fd,"leads"),conversions:n(fd,"conversions"),revenue:n(fd,"revenue"),evidence_confidence:String(fd.get("confidence"))}),"Paid-media snapshot saved.")}><label>Campaign<select name="campaign_id"><option value="">None</option>{data.campaigns.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Provider<select name="provider"><option>Meta</option><option>Google Ads</option><option>TikTok Ads</option><option>Other</option></select></label><label>Spend<input type="number" name="spend"/></label><label>Impressions<input type="number" name="impressions"/></label><label>Clicks<input type="number" name="clicks"/></label><label>Leads<input type="number" name="leads"/></label><label>Conversions<input type="number" name="conversions"/></label><label>Revenue<input type="number" name="revenue"/></label><label>Evidence<select name="confidence"><option value="owner_entered">Owner-entered</option><option value="verified">Verified connected source</option><option value="estimated">Estimated</option></select></label><button className="button button-primary wide">Save snapshot</button></form></section><section className="growth-panel"><h2>Paid-media snapshots</h2><div className="growth-list">{data.paidMedia.map((p:any)=>{const e=calculateCampaignEfficiency(p.spend,p.revenue,p.leads,p.conversions);return <article key={p.id}><Megaphone/><div><strong>{p.provider}</strong><span>{p.evidence_confidence} · spend R {Number(p.spend||0).toLocaleString()}</span></div><b>{e.roas===null?"—":`${e.roas.toFixed(2)}× ROAS`}</b></article>})}</div></section></div>:null}
  </AppShell>;
}
