import { createFileRoute, Link } from "@tanstack/react-router";
import { Bot, FileText, Gauge, Languages, RefreshCw, Search, Sparkles, WandSparkles, Workflow } from "lucide-react";
import { useEffect,useMemo,useState,type FormEvent } from "react";
import { AppShell } from "../../components/app-shell";
import { AuthDeferred } from "../../components/live-data-ui";
import { supabase } from "../../integrations/supabase/client";
import { listStartupWorkspaces,type StartupWorkspace } from "../../lib/startup-os-foundation";
import { approveChangeSet,buildBusinessPlanOutline,buildPitchNarrative,buildSeoMetadata,createAutomationRule,createLocalisationJob,loadIntelligenceWorkspace,parseDeterministicCommand,requestAssistant } from "../../lib/startup-os-phase10";
import "../../startup-os-phase10.css";
export const Route=createFileRoute("/app/intelligence")({component:IntelligencePage});
type Tab="overview"|"assistant"|"plan"|"seo"|"narrative"|"translate"|"actions"|"automations"|"changes"|"audit";
const tabs:Array<{key:Tab;label:string}>=[{key:"overview",label:"Command intelligence"},{key:"assistant",label:"Safe assistant"},{key:"plan",label:"Business plan"},{key:"seo",label:"SEO assistant"},{key:"narrative",label:"Proposal & pitch"},{key:"translate",label:"Localise"},{key:"actions",label:"Next actions"},{key:"automations",label:"Automations"},{key:"changes",label:"Change review"},{key:"audit",label:"Audit"}];
const empty={threads:[],actions:[],rules:[],changes:[],localisations:[],audit:[],liveActions:[]};
function active(rows:StartupWorkspace[]){const stored=typeof window!=="undefined"?localStorage.getItem("start-to-up-active-workspace")||"":"";return rows.some(r=>r.organization_id===stored)?stored:rows[0]?.organization_id||"";}
function IntelligencePage(){
 const[ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(true),[workspaceId,setWorkspaceId]=useState(""),[workspaces,setWorkspaces]=useState<StartupWorkspace[]>([]),[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<any>(empty),[notice,setNotice]=useState(""),[command,setCommand]=useState(""),[assistantPrompt,setAssistantPrompt]=useState(""),[assistantMode,setAssistantMode]=useState("general"),[assistantReply,setAssistantReply]=useState(""),[seo,setSeo]=useState<any>(null),[plan,setPlan]=useState<any[]>([]),[narrative,setNarrative]=useState<any>(null);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSignedIn(Boolean(data.session));setReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(Boolean(s)));return()=>data.subscription.unsubscribe();},[]);
 async function refresh(id=workspaceId){if(!id)return;setBusy(true);try{setData(await loadIntelligenceWorkspace(id));}catch{setNotice("Intelligence workspace could not be refreshed. Check your company access and try again.");}finally{setBusy(false)}}
 useEffect(()=>{if(!ready||!signedIn)return;void listStartupWorkspaces().then(rows=>{setWorkspaces(rows);const id=active(rows);setWorkspaceId(id);if(id)void refresh(id);else setBusy(false)}).catch(()=>setBusy(false));},[ready,signedIn]);
 function switchWorkspace(id:string){setWorkspaceId(id);localStorage.setItem("start-to-up-active-workspace",id);void refresh(id)}
 async function submit(e:FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<unknown>,ok:string){e.preventDefault();const form=e.currentTarget;setNotice("Saving…");try{await fn(new FormData(form));form.reset();setNotice(ok);await refresh();}catch{setNotice("That action could not be saved. Review the fields and permissions.");}}
 const commandResult=useMemo(()=>parseDeterministicCommand(command),[command]);
 if(!ready||busy&&signedIn&&!workspaceId)return <AppShell title="Intelligence & automation" eyebrow="PHASE 10 · INTELLIGENCE"><div className="intel-loading"><RefreshCw className="spin"/> Restoring intelligence workspace…</div></AppShell>;
 if(!signedIn)return <AppShell title="Intelligence & automation" eyebrow="PHASE 10 · INTELLIGENCE"><AuthDeferred/></AppShell>;
 return <AppShell title="Intelligence & automation" eyebrow="PHASE 10 · SAFE ASSISTANCE & AUTOMATION" action={<Link to="/app/integrations" className="button button-secondary">AI integrations</Link>}>
  <section className="intel-toolbar"><div><span>ACTIVE COMPANY</span><select value={workspaceId} onChange={e=>switchWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.organization_id} value={w.organization_id}>{w.name}</option>)}</select></div><button onClick={()=>void refresh()}><RefreshCw size={16}/> Refresh</button></section>{notice?<p className="intel-notice">{notice}</p>:null}
  <nav className="intel-tabs">{tabs.map(t=><button key={t.key} className={tab===t.key?"active":""} onClick={()=>setTab(t.key)}>{t.label}</button>)}</nav>
  {tab==="overview"?<><section className="intel-kpis"><article><Sparkles/><div><span>Live next actions</span><strong>{data.liveActions.length}</strong></div></article><article><Workflow/><div><span>Automation rules</span><strong>{data.rules.length}</strong></div></article><article><FileText/><div><span>Proposed changes</span><strong>{data.changes.filter((x:any)=>x.status==="proposed").length}</strong></div></article><article><Gauge/><div><span>Audit events</span><strong>{data.audit.length}</strong></div></article></section><div className="intel-grid"><section className="intel-panel"><header><Bot/><div><span>SAFE INTELLIGENCE LAYER</span><h2>Assist the founder without silently running the company.</h2></div></header><p>Assistant output is advisory and auditable. Structured business records are never silently overwritten. High-impact changes remain proposed until an authorised workspace member explicitly approves them.</p><div className="intel-flow"><b>Evidence</b><i>→</i><b>Suggestion</b><i>→</i><b>Review</b><i>→</i><b>Approval</b><i>→</i><b>Apply / Revert</b></div></section><section className="intel-panel"><header><WandSparkles/><div><span>DETERMINISTIC BUILDER COMMANDS</span><h2>Fast commands without an AI dependency.</h2></div></header><input className="intel-input" value={command} onChange={e=>setCommand(e.target.value)} placeholder="Try: open revenue or create task: call 5 leads"/><div className="command-result"><strong>{commandResult.label}</strong>{commandResult.path?<a href={commandResult.path}>Open workspace</a>:null}{commandResult.task?<span>Draft only: {commandResult.task}</span>:null}</div><p>No command can bypass workspace permissions or approval gates.</p></section></div></>:null}
  {tab==="assistant"?<section className="intel-panel"><header><Bot/><div><span>SAFE AI ASSISTANCE</span><h2>Draft from workspace evidence.</h2></div></header><div className="intel-assistant"><select value={assistantMode} onChange={e=>setAssistantMode(e.target.value)}><option value="general">General business</option><option value="business_plan">Business plan</option><option value="seo">SEO</option><option value="proposal">Proposal</option><option value="pitch">Pitch</option><option value="translation">Translation</option><option value="workflow">Workflow</option></select><textarea value={assistantPrompt} onChange={e=>setAssistantPrompt(e.target.value)} placeholder="Ask for a draft, summary or structured recommendation…"/><button className="button button-primary" onClick={()=>{if(!assistantPrompt.trim())return;setAssistantReply("Working from the workspace evidence…");void requestAssistant(workspaceId,assistantMode,assistantPrompt).then(r=>{setAssistantReply(`${r.response}\n\n${r.disclosure||""}`);void refresh()}).catch(()=>setAssistantReply("The assistant provider could not complete this request. No workspace data was changed."));}}>Generate suggestion</button></div>{assistantReply?<pre className="assistant-reply">{assistantReply}</pre>:null}<p className="intel-disclosure">External AI is optional and server-side. Provider secrets are never shipped to the browser. Suggestions require human review.</p></section>:null}
  {tab==="plan"?<div className="intel-grid"><section className="intel-panel"><h2>Business-plan drafting assistant</h2><form className="intel-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setPlan(buildBusinessPlanOutline(String(fd.get("company")||"your company")))}}><label className="wide">Company<input name="company" required/></label><button className="button button-primary wide">Build evidence-first outline</button></form><p>Each section instructs the assistant to use verified workspace facts and explicitly mark assumptions.</p></section><section className="intel-panel"><h2>Outline</h2><div className="intel-list">{plan.map(x=><article key={x.order}><b>{x.order}</b><div><strong>{x.section}</strong><span>{x.prompt}</span></div></article>)}</div></section></div>:null}
  {tab==="seo"?<div className="intel-grid"><section className="intel-panel"><header><Search/><div><span>SEO METADATA ASSISTANCE</span><h2>Deterministic metadata before AI.</h2></div></header><form className="intel-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setSeo(buildSeoMetadata({name:String(fd.get("name")),offering:String(fd.get("offering")),location:String(fd.get("location")||""),keyword:String(fd.get("keyword")||"")}))}}><label>Name<input name="name" required/></label><label>Offering<input name="offering" required/></label><label>Location<input name="location"/></label><label>Keyword<input name="keyword"/></label><button className="button button-primary wide">Generate metadata</button></form><p>SEO suggestions are not ranking guarantees.</p></section><section className="intel-panel"><h2>Preview</h2>{seo?<><label>Title<textarea readOnly value={seo.title}/></label><label>Description<textarea readOnly value={seo.description}/></label></>:<p>Generate a title and description to preview them here.</p>}</section></div>:null}
  {tab==="narrative"?<div className="intel-grid"><section className="intel-panel"><h2>Proposal & pitch narrative assistant</h2><form className="intel-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);setNarrative(buildPitchNarrative(String(fd.get("problem")),String(fd.get("solution")),String(fd.get("traction"))))}}><label className="wide">Problem<textarea name="problem" required/></label><label className="wide">Solution<textarea name="solution" required/></label><label className="wide">Verified traction<textarea name="traction" required/></label><button className="button button-primary wide">Create narrative scaffold</button></form></section><section className="intel-panel"><h2>Draft scaffold</h2>{narrative?<pre className="assistant-reply">{`${narrative.problem}\n\n${narrative.solution}\n\n${narrative.traction}\n\n${narrative.disclosure}`}</pre>:null}</section></div>:null}
  {tab==="translate"?<div className="intel-grid"><section className="intel-panel"><header><Languages/><div><span>TRANSLATION & LOCALISATION</span><h2>Queue text for provider-assisted localisation.</h2></div></header><form className="intel-form" onSubmit={e=>void submit(e,fd=>createLocalisationJob(workspaceId,String(fd.get("source")),String(fd.get("target")),String(fd.get("text"))),"Localisation draft queued for review.")}><label>Source locale<input name="source" defaultValue="en-ZA"/></label><label>Target locale<input name="target" placeholder="zu-ZA" required/></label><label className="wide">Text<textarea name="text" required/></label><button className="button button-primary wide">Create localisation job</button></form><p>Machine-assisted localisation requires human review before publication.</p></section><section className="intel-panel"><h2>Jobs</h2><div className="intel-list">{data.localisations.map((x:any)=><article key={x.id}><Languages/><div><strong>{x.source_locale} → {x.target_locale}</strong><span>{x.status}</span></div></article>)}</div></section></div>:null}
  {tab==="actions"?<section className="intel-panel"><header><Gauge/><div><span>NEXT-BEST-ACTION ENGINE</span><h2>Recommendations derived from actual workspace records.</h2></div></header><div className="intel-list">{data.liveActions.map((x:any,i:number)=><article key={`${x.module}-${i}`}><b>{x.priority}</b><div><strong>{x.title}</strong><span>{x.module} · evidence: {JSON.stringify(x.evidence||{})}</span></div><a href={x.path}>Open</a></article>)}{!data.liveActions.length?<p>No urgent derived actions were found from the currently available workspace evidence.</p>:null}</div></section>:null}
  {tab==="automations"?<div className="intel-grid"><section className="intel-panel"><header><Workflow/><div><span>WORKFLOW AUTOMATIONS</span><h2>Approval-first rules.</h2></div></header><form className="intel-form" onSubmit={e=>void submit(e,fd=>createAutomationRule(workspaceId,{name:String(fd.get("name")),trigger_type:String(fd.get("trigger")),trigger_config:{description:String(fd.get("trigger_detail")||"")},action_type:String(fd.get("action")),action_config:{description:String(fd.get("action_detail")||"")},requires_approval:true}),"Automation rule saved disabled. Review it before enabling.")}><label className="wide">Name<input name="name" required/></label><label>Trigger<select name="trigger"><option>schedule</option><option>record_change</option><option>deadline</option><option>threshold</option><option>manual</option></select></label><label>Action<select name="action"><option>create_task</option><option>create_next_action</option><option>send_notification</option><option>draft_content</option><option>webhook</option></select></label><label className="wide">Trigger detail<input name="trigger_detail"/></label><label className="wide">Action detail<input name="action_detail"/></label><button className="button button-primary wide">Save disabled rule</button></form><p>New rules default to disabled and approval-required. They cannot silently overwrite structured records.</p></section><section className="intel-panel"><h2>Rules</h2><div className="intel-list">{data.rules.map((r:any)=><article key={r.id}><Workflow/><div><strong>{r.name}</strong><span>{r.trigger_type} → {r.action_type} · {r.is_enabled?"enabled":"disabled"} · approval {r.requires_approval?"required":"configured"}</span></div></article>)}</div></section></div>:null}
  {tab==="changes"?<section className="intel-panel"><header><FileText/><div><span>REVERSIBLE CHANGE REVIEW</span><h2>No silent structured-data overwrite.</h2></div></header><div className="intel-list">{data.changes.map((c:any)=><article key={c.id}><div><strong>{c.title}</strong><span>{c.target_type} · {c.status}</span><small>Previous values retained for audit/revert workflows.</small></div>{c.status==="proposed"?<button onClick={()=>void approveChangeSet(c.id).then(()=>refresh())}>Approve proposal</button>:null}</article>)}</div></section>:null}
  {tab==="audit"?<section className="intel-panel"><h2>Intelligence audit log</h2><div className="intel-list">{data.audit.map((a:any)=><article key={a.id}><div><strong>{a.event_type}</strong><span>{a.entity_type||"workspace"}</span><small>{new Date(a.created_at).toLocaleString()}</small></div></article>)}</div></section>:null}
 </AppShell>;
}
