import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, BriefcaseBusiness, CalendarClock, CheckCircle2, ClipboardList, FileText, Gauge, RefreshCw, ShieldAlert, Target, UsersRound, UserSearch, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { AppShell } from "../../components/app-shell";
import { AuthDeferred } from "../../components/live-data-ui";
import { supabase } from "../../integrations/supabase/client";
import { listStartupWorkspaces, type StartupWorkspace } from "../../lib/startup-os-foundation";
import { addCandidate, addKeyResult, addRenewal, addRisk, addVendor, commandNextActions, createHiringPlan, createJobDescription, createMeeting, createOkr, daysUntil, loadOperatingWorkspace, recordDecision, riskLevel, saveCommandSnapshot } from "../../lib/startup-os-phase6";
import "../../startup-os-phase6.css";

export const Route=createFileRoute("/app/operations")({component:OperationsPage});
type Tab="command"|"okrs"|"decisions"|"risks"|"hiring"|"jobs"|"candidates"|"vendors"|"meetings"|"renewals";
const tabs:Array<{key:Tab;label:string}>=[{key:"command",label:"Command Centre"},{key:"okrs",label:"OKRs"},{key:"decisions",label:"Decision Log"},{key:"risks",label:"Risk Register"},{key:"hiring",label:"Hiring Planner"},{key:"jobs",label:"Job Descriptions"},{key:"candidates",label:"Applicants"},{key:"vendors",label:"Vendors"},{key:"meetings",label:"Meetings"},{key:"renewals",label:"Renewals"}];
const empty:any={okrs:[],keyResults:[],decisions:[],risks:[],hiring:[],jobs:[],candidates:[],candidateEvents:[],vendors:[],engagements:[],meetings:[],meetingActions:[],renewals:[],command:{}};
const n=(fd:FormData,key:string)=>Number(fd.get(key)||0)||0;
const textList=(value:FormDataEntryValue|null)=>String(value||"").split("\n").map(v=>v.trim()).filter(Boolean);
function activeWorkspace(rows:StartupWorkspace[]){const stored=typeof window!=="undefined"?localStorage.getItem("start-to-up-active-workspace")||"":"";return rows.some(r=>r.organization_id===stored)?stored:rows[0]?.organization_id||"";}

function OperationsPage(){
  const [ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(true);const [workspaces,setWorkspaces]=useState<StartupWorkspace[]>([]),[workspaceId,setWorkspaceId]=useState(""),[tab,setTab]=useState<Tab>("command"),[data,setData]=useState<any>(empty),[notice,setNotice]=useState("");
  const command=data.command||{};const nextActions=useMemo(()=>commandNextActions(command),[command]);
  useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSignedIn(Boolean(data.session));setReady(true)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(Boolean(s)));return()=>data.subscription.unsubscribe();},[]);
  async function refresh(id=workspaceId){if(!id)return;setBusy(true);try{setData(await loadOperatingWorkspace(id));}catch{setNotice("Operations workspace could not be refreshed. Check your workspace access and try again.");}finally{setBusy(false)}}
  useEffect(()=>{if(!ready||!signedIn)return;void listStartupWorkspaces().then(rows=>{setWorkspaces(rows);const id=activeWorkspace(rows);setWorkspaceId(id);if(id)void refresh(id);}).catch(()=>{setNotice("No company workspace could be loaded.");setBusy(false)});},[ready,signedIn]);
  function changeWorkspace(id:string){setWorkspaceId(id);localStorage.setItem("start-to-up-active-workspace",id);void refresh(id);}
  async function submit(event:FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<any>,ok:string){event.preventDefault();if(!workspaceId)return;const el=event.currentTarget;setNotice("Saving…");try{await fn(new FormData(el));el.reset();setNotice(ok);await refresh();}catch{setNotice("That change could not be saved. Review the fields and your workspace permission, then try again.");}}
  if(!ready||busy&&signedIn&&!workspaceId)return <AppShell title="Operations" eyebrow="PHASE 6 · OPERATIONS, TEAMS & EXECUTION"><div className="ops-loading"><RefreshCw className="spin"/> Restoring operating company workspace…</div></AppShell>;
  if(!signedIn)return <AppShell title="Operations" eyebrow="PHASE 6 · OPERATIONS, TEAMS & EXECUTION"><AuthDeferred/></AppShell>;
  return <AppShell title="Operations" eyebrow="PHASE 6 · OPERATIONS, TEAMS & EXECUTION" action={<Link to="/app/startup-os" className="button button-secondary">Company workspace</Link>}>
    <section className="ops-toolbar"><div><span>ACTIVE COMPANY</span><select value={workspaceId} onChange={e=>changeWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.organization_id} value={w.organization_id}>{w.name}</option>)}</select></div><button onClick={()=>void refresh()}><RefreshCw size={16}/> Refresh</button></section>
    {notice?<p className="ops-notice" role="status">{notice}</p>:null}
    <nav className="ops-tabs" aria-label="Operating company tools">{tabs.map(t=><button key={t.key} className={tab===t.key?"active":""} onClick={()=>setTab(t.key)}>{t.label}</button>)}</nav>

    {tab==="command"?<><section className="ops-kpis"><article><Gauge/><div><span>Company health</span><strong>{command.company_health??0}%</strong><small>derived workspace score</small></div></article><article><WalletCards/><div><span>Weighted pipeline</span><strong>R {Math.round(Number(command.weighted_pipeline||0)).toLocaleString()}</strong><small>from Revenue OS</small></div></article><article><Target/><div><span>Execution</span><strong>{command.execution_health??0}%</strong><small>{command.active_okrs||0} active OKRs</small></div></article><article><ShieldAlert/><div><span>Risk health</span><strong>{command.risk_health??0}%</strong><small>{command.high_risks||0} high risks</small></div></article><article><Activity/><div><span>Growth</span><strong>{command.growth_health??0}%</strong><small>{command.active_campaigns||0} active campaigns</small></div></article><article><UsersRound/><div><span>People</span><strong>{command.people_health??0}%</strong><small>{command.open_hiring||0} open hires</small></div></article></section><div className="ops-grid"><section className="ops-panel"><header><Gauge/><div><span>FOUNDER COMMAND CENTRE</span><h2>One operating view from actual workspace records.</h2></div></header><p>The health model uses Revenue OS pipeline, Growth campaigns, OKR progress, workspace tasks, current risks, hiring activity, trust records and upcoming renewals. It is not a static self-assessment.</p><div className="ops-health">{[["Revenue",command.revenue_health],["Growth",command.growth_health],["Execution",command.execution_health],["People",command.people_health],["Risk",command.risk_health],["Overall",command.company_health]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{Number(value||0)}%</strong><div className="ops-scorebar"><i style={{width:`${Number(value||0)}%`}}/></div></article>)}</div><button className="button button-primary" style={{marginTop:"1rem"}} onClick={()=>void saveCommandSnapshot(workspaceId,command,nextActions).then(()=>setNotice("Command Centre snapshot saved for today.")).catch(()=>setNotice("Snapshot could not be saved."))}>Save today’s snapshot</button></section><section className="ops-panel"><header><ClipboardList/><div><span>NEXT-BEST OPERATING ACTIONS</span><h2>Work the constraints first.</h2></div></header>{nextActions.length?<ol className="ops-actions">{nextActions.map(a=><li key={a}>{a}</li>)}</ol>:<div className="ops-empty">No urgent operating gaps detected from the current records.</div>}<div className="ops-flow"><b>Validate</b><i>→</i><b>Build</b><i>→</i><b>Sell</b><i>→</i><b>Grow</b><i>→</i><b>Operate</b></div></section></div></>:null}

    {tab==="okrs"?<div className="ops-grid"><section className="ops-panel"><h2>OKR Tracker</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>createOkr(workspaceId,{title:String(fd.get("title")),description:String(fd.get("description")||""),period_label:String(fd.get("period")||""),start_date:fd.get("start")||null,end_date:fd.get("end")||null,status:String(fd.get("status"))}),"OKR created.")}><label className="wide">Objective<input name="title" required/></label><label>Period<input name="period" placeholder="Q4 2026"/></label><label>Status<select name="status"><option>active</option><option>draft</option><option>at_risk</option><option>completed</option></select></label><label>Start<input type="date" name="start"/></label><label>End<input type="date" name="end"/></label><label className="wide">Description<textarea name="description"/></label><button className="button button-primary wide">Create objective</button></form><hr/><h2>Add key result</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>addKeyResult(workspaceId,{okr_id:String(fd.get("okr_id")),title:String(fd.get("title")),metric_name:String(fd.get("metric")||""),start_value:n(fd,"start_value"),current_value:n(fd,"current_value"),target_value:n(fd,"target_value"),unit:String(fd.get("unit")||"")}),"Key result added and OKR progress refreshed.")}><label className="wide">Objective<select name="okr_id" required>{data.okrs.map((o:any)=><option value={o.id} key={o.id}>{o.title}</option>)}</select></label><label className="wide">Key result<input name="title" required/></label><label>Metric<input name="metric"/></label><label>Unit<input name="unit" placeholder="%, R, users…"/></label><label>Start<input type="number" name="start_value" defaultValue="0"/></label><label>Current<input type="number" name="current_value" defaultValue="0"/></label><label>Target<input type="number" name="target_value" defaultValue="100"/></label><button className="button button-primary wide">Add key result</button></form></section><section className="ops-panel"><h2>Objectives</h2><div className="ops-list">{data.okrs.map((o:any)=><article key={o.id}><div><strong>{o.title}</strong><span>{o.period_label||"No period"}</span><div className="ops-scorebar"><i style={{width:`${Number(o.progress||0)}%`}}/></div><small>{Number(o.progress||0).toFixed(1)}% progress</small></div><b>{o.status}</b></article>)}{!data.okrs.length?<div className="ops-empty">No objectives yet.</div>:null}</div></section></div>:null}

    {tab==="decisions"?<div className="ops-grid"><section className="ops-panel"><h2>Decision Log</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>recordDecision(workspaceId,{title:String(fd.get("title")),context:String(fd.get("context")||""),decision:String(fd.get("decision")),rationale:String(fd.get("rationale")||""),alternatives:String(fd.get("alternatives")||""),impact:String(fd.get("impact")||""),reversible:fd.get("reversible")==="yes",review_at:fd.get("review_at")||null}),"Decision recorded.")}><label className="wide">Decision title<input name="title" required/></label><label className="wide">Context<textarea name="context"/></label><label className="wide">Decision<textarea name="decision" required/></label><label className="wide">Rationale<textarea name="rationale"/></label><label className="wide">Alternatives considered<textarea name="alternatives"/></label><label className="wide">Expected impact<textarea name="impact"/></label><label>Reversible?<select name="reversible"><option value="yes">Yes</option><option value="no">No</option></select></label><label>Review at<input type="datetime-local" name="review_at"/></label><button className="button button-primary wide">Record decision</button></form></section><section className="ops-panel"><h2>Recorded decisions</h2><div className="ops-list">{data.decisions.map((d:any)=><article key={d.id}><div><strong>{d.title}</strong><span>{d.decision}</span><small>{d.reversible?"Reversible":"High-commitment decision"}</small></div><b>{d.status}</b></article>)}{!data.decisions.length?<div className="ops-empty">No decisions recorded.</div>:null}</div></section></div>:null}

    {tab==="risks"?<div className="ops-grid"><section className="ops-panel"><h2>Risk Register</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>addRisk(workspaceId,{title:String(fd.get("title")),category:String(fd.get("category")),description:String(fd.get("description")||""),likelihood:n(fd,"likelihood"),impact:n(fd,"impact"),mitigation:String(fd.get("mitigation")||""),contingency:String(fd.get("contingency")||""),review_at:fd.get("review_at")||null}),"Risk added.")}><label className="wide">Risk<input name="title" required/></label><label>Category<select name="category"><option>operational</option><option>financial</option><option>legal</option><option>security</option><option>technology</option><option>market</option><option>people</option><option>reputation</option><option>other</option></select></label><label>Likelihood 1–5<input type="number" min="1" max="5" name="likelihood" defaultValue="3"/></label><label>Impact 1–5<input type="number" min="1" max="5" name="impact" defaultValue="3"/></label><label className="wide">Description<textarea name="description"/></label><label className="wide">Mitigation<textarea name="mitigation"/></label><label className="wide">Contingency<textarea name="contingency"/></label><label>Review at<input type="datetime-local" name="review_at"/></label><button className="button button-primary wide">Add risk</button></form></section><section className="ops-panel"><h2>Current risks</h2><div className="ops-list">{data.risks.map((r:any)=>{const level=riskLevel(Number(r.risk_score||0));return <article key={r.id}><div><strong>{r.title}</strong><span>{r.category} · score {r.risk_score}/25</span><small>{r.mitigation||"No mitigation recorded"}</small></div><b className={`ops-risk-${level}`}>{level}</b></article>})}{!data.risks.length?<div className="ops-empty">No risks recorded.</div>:null}</div></section></div>:null}

    {tab==="hiring"?<div className="ops-grid"><section className="ops-panel"><h2>Hiring Planner</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>createHiringPlan(workspaceId,{role_title:String(fd.get("role")),department:String(fd.get("department")||""),employment_type:String(fd.get("type")),reason:String(fd.get("reason")||""),priority:n(fd,"priority"),target_start_date:fd.get("start")||null,salary_min:n(fd,"salary_min")||null,salary_max:n(fd,"salary_max")||null,status:String(fd.get("status"))}),"Hiring plan created.")}><label>Role<input name="role" required/></label><label>Department<input name="department"/></label><label>Type<select name="type"><option value="full_time">Full time</option><option value="part_time">Part time</option><option>contract</option><option>internship</option><option>freelance</option><option>temporary</option></select></label><label>Status<select name="status"><option>planned</option><option>approved</option><option>recruiting</option><option>on_hold</option></select></label><label>Priority 0–100<input type="number" min="0" max="100" name="priority" defaultValue="60"/></label><label>Target start<input type="date" name="start"/></label><label>Salary min<input type="number" min="0" name="salary_min"/></label><label>Salary max<input type="number" min="0" name="salary_max"/></label><label className="wide">Why is this role needed?<textarea name="reason"/></label><button className="button button-primary wide">Add hiring plan</button></form></section><section className="ops-panel"><h2>Hiring plan</h2><div className="ops-list">{data.hiring.map((h:any)=><article key={h.id}><div><strong>{h.role_title}</strong><span>{h.department||"General"} · {String(h.employment_type).replaceAll("_"," ")}</span><small>{h.salary_min||h.salary_max?`R ${Number(h.salary_min||0).toLocaleString()} – R ${Number(h.salary_max||0).toLocaleString()}`:"Compensation not set"}</small></div><b>{h.status}</b></article>)}{!data.hiring.length?<div className="ops-empty">No planned roles.</div>:null}</div></section></div>:null}

    {tab==="jobs"?<div className="ops-grid"><section className="ops-panel"><h2>Job Description Builder</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>createJobDescription(workspaceId,{hiring_plan_id:String(fd.get("hiring_plan_id")||"")||null,title:String(fd.get("title")),summary:String(fd.get("summary")||""),responsibilities:textList(fd.get("responsibilities")),requirements:textList(fd.get("requirements")),nice_to_have:textList(fd.get("nice_to_have")),location:String(fd.get("location")||""),work_mode:String(fd.get("work_mode")||"")||null,status:"draft"}),"Job description created.")}><label className="wide">Linked hiring plan<select name="hiring_plan_id"><option value="">None</option>{data.hiring.map((h:any)=><option key={h.id} value={h.id}>{h.role_title}</option>)}</select></label><label className="wide">Job title<input name="title" required/></label><label className="wide">Summary<textarea name="summary"/></label><label className="wide">Responsibilities — one per line<textarea name="responsibilities" rows={5}/></label><label className="wide">Requirements — one per line<textarea name="requirements" rows={5}/></label><label className="wide">Nice to have — one per line<textarea name="nice_to_have" rows={4}/></label><label>Location<input name="location"/></label><label>Work mode<select name="work_mode"><option value="">Not specified</option><option>onsite</option><option>hybrid</option><option>remote</option></select></label><button className="button button-primary wide">Create draft JD</button></form></section><section className="ops-panel"><h2>Job descriptions</h2><div className="ops-list">{data.jobs.map((j:any)=><article key={j.id}><div><strong>{j.title}</strong><span>{j.location||"Location not set"} · {j.work_mode||"work mode not set"}</span><small>{Array.isArray(j.requirements)?`${j.requirements.length} requirements`:""}</small></div><b>{j.status}</b></article>)}{!data.jobs.length?<div className="ops-empty">No job descriptions yet.</div>:null}</div></section></div>:null}

    {tab==="candidates"?<div className="ops-grid"><section className="ops-panel"><h2>Applicant Tracking System</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>addCandidate(workspaceId,{job_description_id:String(fd.get("job_id")||"")||null,full_name:String(fd.get("name")),email:String(fd.get("email")||"")||null,phone:String(fd.get("phone")||"")||null,source:String(fd.get("source")||"manual"),stage:String(fd.get("stage")),score:n(fd,"score")||null,notes:String(fd.get("notes")||""),consent_status:String(fd.get("consent"))}),"Candidate added.")}><label className="wide">Job<select name="job_id"><option value="">General pipeline</option>{data.jobs.map((j:any)=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Full name<input name="name" required/></label><label>Email<input type="email" name="email"/></label><label>Phone<input name="phone"/></label><label>Source<input name="source" placeholder="Referral, careers page…"/></label><label>Stage<select name="stage"><option>applied</option><option>screening</option><option>interview</option><option>assessment</option><option>offer</option><option>hired</option><option>rejected</option></select></label><label>Score<input type="number" min="0" max="100" name="score"/></label><label>Consent<select name="consent"><option>unknown</option><option>consented</option><option>withdrawn</option></select></label><label className="wide">Notes<textarea name="notes"/></label><button className="button button-primary wide">Add applicant</button></form></section><section className="ops-panel"><h2>Applicants</h2><div className="ops-list">{data.candidates.map((c:any)=><article key={c.id}><div><strong>{c.full_name}</strong><span>{c.email||c.phone||"No contact captured"}</span><small>{c.score==null?"Not scored":`Score ${c.score}/100`} · consent {c.consent_status}</small></div><b>{c.stage}</b></article>)}{!data.candidates.length?<div className="ops-empty">No applicants yet.</div>:null}</div></section></div>:null}

    {tab==="vendors"?<div className="ops-grid"><section className="ops-panel"><h2>Freelancer / Vendor Manager</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>addVendor(workspaceId,{name:String(fd.get("name")),vendor_type:String(fd.get("type")),contact_name:String(fd.get("contact")||""),email:String(fd.get("email")||"")||null,phone:String(fd.get("phone")||"")||null,website:String(fd.get("website")||"")||null,service_category:String(fd.get("category")||""),status:String(fd.get("status")),rating:n(fd,"rating")||null,notes:String(fd.get("notes")||"")}),"Vendor saved.")}><label>Name<input name="name" required/></label><label>Type<select name="type"><option>vendor</option><option>freelancer</option><option>contractor</option><option>consultant</option><option>agency</option><option>supplier</option></select></label><label>Contact<input name="contact"/></label><label>Email<input type="email" name="email"/></label><label>Phone<input name="phone"/></label><label>Website<input type="url" name="website"/></label><label>Service category<input name="category"/></label><label>Status<select name="status"><option>active</option><option>prospect</option><option>paused</option><option>blocked</option><option>archived</option></select></label><label>Rating 0–5<input type="number" min="0" max="5" step="0.1" name="rating"/></label><label className="wide">Notes<textarea name="notes"/></label><button className="button button-primary wide">Save vendor</button></form></section><section className="ops-panel"><h2>Vendors & contractors</h2><div className="ops-list">{data.vendors.map((v:any)=><article key={v.id}><div><strong>{v.name}</strong><span>{v.service_category||v.vendor_type}</span><small>{v.rating?`${Number(v.rating).toFixed(1)}/5 rating`:"Not rated"}</small></div><b>{v.status}</b></article>)}{!data.vendors.length?<div className="ops-empty">No vendors yet.</div>:null}</div></section></div>:null}

    {tab==="meetings"?<div className="ops-grid"><section className="ops-panel"><h2>Meeting Workspace</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>createMeeting(workspaceId,{title:String(fd.get("title")),meeting_type:String(fd.get("type")),starts_at:String(fd.get("starts_at")),duration_minutes:n(fd,"duration")||30,location_or_link:String(fd.get("location")||""),agenda:String(fd.get("agenda")||"")}),"Meeting scheduled.")}><label className="wide">Meeting title<input name="title" required/></label><label>Type<select name="type"><option>internal</option><option>client</option><option>investor</option><option>partner</option><option>vendor</option><option>interview</option><option>other</option></select></label><label>Starts<input type="datetime-local" name="starts_at" required/></label><label>Duration minutes<input type="number" min="5" max="1440" name="duration" defaultValue="30"/></label><label>Location / link<input name="location"/></label><label className="wide">Agenda<textarea name="agenda" rows={5}/></label><button className="button button-primary wide">Schedule meeting</button></form></section><section className="ops-panel"><h2>Meetings</h2><div className="ops-list">{data.meetings.map((m:any)=><article key={m.id}><div><strong>{m.title}</strong><span>{new Date(m.starts_at).toLocaleString()} · {m.duration_minutes} min</span><small>{m.location_or_link||m.meeting_type}</small></div><b>{m.status}</b></article>)}{!data.meetings.length?<div className="ops-empty">No meetings scheduled.</div>:null}</div></section></div>:null}

    {tab==="renewals"?<div className="ops-grid"><section className="ops-panel"><h2>Renewal & Deadline Tracker</h2><form className="ops-form" onSubmit={e=>void submit(e,fd=>addRenewal(workspaceId,{name:String(fd.get("name")),category:String(fd.get("category")),due_date:String(fd.get("due_date")),recurrence:String(fd.get("recurrence")),reminder_days:n(fd,"reminder_days"),amount:n(fd,"amount")||null,currency:String(fd.get("currency")||"ZAR"),private_detail:{notes:String(fd.get("notes")||"")}}),"Renewal/deadline saved.")}><label className="wide">Item<input name="name" required/></label><label>Category<select name="category"><option>domain</option><option>subscription</option><option>licence</option><option>contract</option><option>insurance</option><option>certificate</option><option>registration</option><option>tax</option><option>compliance</option><option>other</option></select></label><label>Due date<input type="date" name="due_date" required/></label><label>Recurrence<select name="recurrence"><option>once</option><option>monthly</option><option>quarterly</option><option>biannual</option><option>annual</option><option>custom</option></select></label><label>Reminder days<input type="number" min="0" max="365" name="reminder_days" defaultValue="30"/></label><label>Amount<input type="number" min="0" step="0.01" name="amount"/></label><label>Currency<input name="currency" defaultValue="ZAR"/></label><label className="wide">Private notes<textarea name="notes"/></label><button className="button button-primary wide">Add renewal/deadline</button></form></section><section className="ops-panel"><h2>Upcoming</h2><div className="ops-list">{data.renewals.map((r:any)=>{const days=daysUntil(r.due_date);return <article key={r.id}><div><strong>{r.name}</strong><span>{r.category} · due {r.due_date}</span><small>{days<0?`${Math.abs(days)} days overdue`:days===0?"Due today":`${days} days remaining`}</small></div><b className={days<=7?"ops-risk-high":""}>{r.status}</b></article>})}{!data.renewals.length?<div className="ops-empty">No renewal/deadline records.</div>:null}</div><div className="ops-callout"><strong>Private by default</strong><span>Renewal notes and sensitive statutory details belong in the authenticated workspace. Phase 6 does not publish certificate, registration or expiry dates to the public website.</span></div></section></div>:null}
  </AppShell>;
}
