import { createFileRoute, Link } from "@tanstack/react-router";
import { BriefcaseBusiness, Building2, Compass, Handshake, Network, RefreshCw, Rocket, Search, Store, Target, UsersRound } from "lucide-react";
import { useEffect,useMemo,useState,type FormEvent } from "react";
import { AppShell } from "../../components/app-shell";
import { AuthDeferred } from "../../components/live-data-ui";
import { supabase } from "../../integrations/supabase/client";
import { listStartupWorkspaces,type StartupWorkspace } from "../../lib/startup-os-foundation";
import { applyToOpportunity,calculateNetworkMatch,createHandoff,createOpportunity,createPartnership,createPilot,createProgram,loadEcosystemWorkspace,saveOpportunity,saveProfile } from "../../lib/startup-os-phase9";
import "../../startup-os-phase9.css";

export const Route=createFileRoute("/app/opportunities")({component:EcosystemPage});
type Tab="overview"|"profile"|"opportunities"|"programs"|"matches"|"partnerships"|"pilots"|"supplier"|"handoffs";
const tabs:Array<{key:Tab;label:string}>=[{key:"overview",label:"Overview"},{key:"profile",label:"Directory profile"},{key:"opportunities",label:"Opportunity marketplace"},{key:"programs",label:"Programs"},{key:"matches",label:"Partnership matcher"},{key:"partnerships",label:"Partnerships"},{key:"pilots",label:"Pilots"},{key:"supplier",label:"Supplier profile"},{key:"handoffs",label:"Handoffs"}];
const empty={profile:null,opportunities:[],saved:[],applications:[],matches:[],partnerships:[],programs:[],supplier:null,pilots:[],handoffs:[]};
function active(rows:StartupWorkspace[]){const stored=typeof window!=="undefined"?localStorage.getItem("start-to-up-active-workspace")||"":"";return rows.some(r=>r.organization_id===stored)?stored:rows[0]?.organization_id||"";}
const list=(v:FormDataEntryValue|null)=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean);

function EcosystemPage(){
 const[ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(true),[workspaceId,setWorkspaceId]=useState(""),[workspaces,setWorkspaces]=useState<StartupWorkspace[]>([]),[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<any>(empty),[notice,setNotice]=useState(""),[query,setQuery]=useState("");
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSignedIn(Boolean(data.session));setReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(Boolean(s)));return()=>data.subscription.unsubscribe();},[]);
 async function refresh(id=workspaceId){if(!id)return;setBusy(true);try{setData(await loadEcosystemWorkspace(id));}catch{setNotice("The ecosystem workspace could not be refreshed. Check your company access and try again.");}finally{setBusy(false)}}
 useEffect(()=>{if(!ready||!signedIn)return;void listStartupWorkspaces().then(rows=>{setWorkspaces(rows);const id=active(rows);setWorkspaceId(id);if(id)void refresh(id);else setBusy(false)}).catch(()=>setBusy(false));},[ready,signedIn]);
 async function submit(e:FormEvent<HTMLFormElement>,fn:(fd:FormData)=>Promise<unknown>,ok:string){e.preventDefault();if(!workspaceId)return;const form=e.currentTarget;setNotice("Saving…");try{await fn(new FormData(form));form.reset();setNotice(ok);await refresh();}catch{setNotice("That change could not be saved. Review the fields and your workspace permissions.");}}
 function switchWorkspace(id:string){setWorkspaceId(id);localStorage.setItem("start-to-up-active-workspace",id);void refresh(id)}
 const opportunities=useMemo(()=>data.opportunities.filter((o:any)=>!query||`${o.title} ${o.description||""} ${o.industry||""} ${o.geography||""}`.toLowerCase().includes(query.toLowerCase())),[data.opportunities,query]);
 const profile=data.profile;
 const estimatedMatches=useMemo(()=>data.opportunities.slice(0,10).map((o:any)=>{const target={industry:o.industry,stage:o.stage,geography:o.geography,capabilities:o.capabilities_needed||[],verification_score:o.evidence_confidence==="verified"?100:40};return{opportunity:o,...calculateNetworkMatch(profile||{},target)}}).sort((a:any,b:any)=>b.score-a.score),[data.opportunities,profile]);
 if(!ready||busy&&signedIn&&!workspaceId)return <AppShell title="Network & opportunities" eyebrow="PHASE 9 · ECOSYSTEM"><div className="eco-loading"><RefreshCw className="spin"/> Restoring ecosystem workspace…</div></AppShell>;
 if(!signedIn)return <AppShell title="Network & opportunities" eyebrow="PHASE 9 · ECOSYSTEM"><AuthDeferred/></AppShell>;
 return <AppShell title="Network & opportunities" eyebrow="PHASE 9 · NETWORK, PARTNERSHIPS & MARKETPLACE" action={<Link to="/app/collaboration" className="button button-secondary">Collaboration rooms</Link>}>
  <section className="eco-toolbar"><div><span>ACTIVE COMPANY</span><select value={workspaceId} onChange={e=>switchWorkspace(e.target.value)}>{workspaces.map(w=><option value={w.organization_id} key={w.organization_id}>{w.name}</option>)}</select></div><button onClick={()=>void refresh()}><RefreshCw size={16}/> Refresh</button></section>
  {notice?<p className="eco-notice" role="status">{notice}</p>:null}
  <nav className="eco-tabs">{tabs.map(t=><button key={t.key} className={tab===t.key?"active":""} onClick={()=>setTab(t.key)}>{t.label}</button>)}</nav>
  {tab==="overview"?<><section className="eco-kpis"><article><Store/><div><span>Open opportunities</span><strong>{data.opportunities.filter((x:any)=>x.status==="open").length}</strong></div></article><article><Target/><div><span>Suggested matches</span><strong>{estimatedMatches.filter((x:any)=>x.score>=50).length}</strong></div></article><article><Handshake/><div><span>Partnerships</span><strong>{data.partnerships.length}</strong></div></article><article><Rocket/><div><span>Pilots</span><strong>{data.pilots.length}</strong></div></article></section><div className="eco-grid"><section className="eco-panel"><header><Network/><div><span>STRUCTURED NETWORK</span><h2>Discovery should lead to work, not another dead-end profile.</h2></div></header><p>Profiles, opportunities, programmes and matches stay connected to your company workspace. Every discovery can be handed into CRM, collaboration, projects, tasks or Website Studio with source lineage preserved.</p><div className="eco-flow"><b>Discover</b><i>→</i><b>Match</b><i>→</i><b>Save / Apply</b><i>→</i><b>Handoff</b><i>→</i><b>Execute</b></div></section><section className="eco-panel"><header><Compass/><div><span>MATCHING EVIDENCE</span><h2>Match scores are estimated, not endorsements.</h2></div></header><p>Industry, geography, stage, capability fit and verification evidence produce deterministic suggestions. A high score does not guarantee commercial fit, funding, selection or partnership.</p></section></div></>:null}
  {tab==="profile"?<div className="eco-grid"><section className="eco-panel"><h2>Startup Directory Profile</h2><form className="eco-form" onSubmit={e=>void submit(e,fd=>saveProfile(workspaceId,{display_name:String(fd.get("name")),profile_type:String(fd.get("type")),industry:String(fd.get("industry")||""),stage:String(fd.get("stage")||""),geography:String(fd.get("geography")||""),bio:String(fd.get("bio")||""),capabilities:list(fd.get("capabilities")),needs:list(fd.get("needs")),availability:String(fd.get("availability")),is_discoverable:fd.get("discoverable")==="on"}),"Directory profile saved.")}><label>Name<input name="name" defaultValue={profile?.display_name||""} required/></label><label>Profile type<select name="type" defaultValue={profile?.profile_type||"startup"}><option>startup</option><option>supplier</option><option>service_provider</option><option>developer</option><option>creator</option><option>institution</option><option>investor</option></select></label><label>Industry<input name="industry" defaultValue={profile?.industry||""}/></label><label>Stage<input name="stage" defaultValue={profile?.stage||""}/></label><label>Geography<input name="geography" defaultValue={profile?.geography||""}/></label><label>Availability<select name="availability" defaultValue={profile?.availability||"open"}><option>open</option><option>limited</option><option>closed</option></select></label><label className="wide">Capabilities<input name="capabilities" defaultValue={(profile?.capabilities||[]).join(", ")} placeholder="web development, property, marketing"/></label><label className="wide">Needs<input name="needs" defaultValue={(profile?.needs||[]).join(", ")} placeholder="investment, supplier, developer"/></label><label className="wide">Bio<textarea name="bio" defaultValue={profile?.bio||""}/></label><label className="check wide"><input type="checkbox" name="discoverable" defaultChecked={Boolean(profile?.is_discoverable)}/> Allow authenticated Start To Up members to discover this profile</label><button className="button button-primary wide">Save profile</button></form></section><section className="eco-panel"><h2>Profile quality</h2><p>Discoverability is opt-in. Private company records, compliance files and due-diligence documents are never exposed through this directory profile.</p><div className="eco-score"><strong>{profile?.verification_score||0}%</strong><span>verification evidence score</span></div></section></div>:null}
  {tab==="opportunities"?<div className="eco-grid"><section className="eco-panel"><h2>Publish opportunity</h2><form className="eco-form" onSubmit={e=>void submit(e,fd=>createOpportunity(workspaceId,{title:String(fd.get("title")),opportunity_type:String(fd.get("type")),description:String(fd.get("description")||""),industry:String(fd.get("industry")||""),geography:String(fd.get("geography")||""),capabilities_needed:list(fd.get("capabilities")),source_url:String(fd.get("source_url")||"")||null,visibility:String(fd.get("visibility")),status:"open",evidence_confidence:"owner_entered"}),"Opportunity published.")}><label>Title<input name="title" required/></label><label>Type<select name="type"><option>partnership</option><option>supplier</option><option>pilot</option><option>tender</option><option>funding</option><option>programme</option><option>wil</option><option>contract</option><option>collaboration</option></select></label><label>Industry<input name="industry"/></label><label>Geography<input name="geography"/></label><label className="wide">Capabilities needed<input name="capabilities"/></label><label className="wide">Official/source URL<input type="url" name="source_url"/></label><label>Visibility<select name="visibility"><option value="network">Start To Up network</option><option value="private">Private</option><option value="public">Public-ready</option></select></label><label className="wide">Description<textarea name="description"/></label><button className="button button-primary wide">Publish opportunity</button></form></section><section className="eco-panel"><header><Search/><div><span>MARKETPLACE</span><h2>Find work, partnerships and programmes.</h2></div></header><input className="eco-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search industry, city, tender, pilot…"/><div className="eco-list">{opportunities.map((o:any)=><article key={o.id}><div><strong>{o.title}</strong><span>{o.opportunity_type} · {o.industry||"Any industry"} · {o.geography||"Any location"}</span><small>{o.evidence_confidence} evidence{o.source_url?" · source linked":""}</small></div><div className="eco-actions"><button onClick={()=>void saveOpportunity(workspaceId,o.id).then(()=>refresh())}>Save</button><button onClick={()=>{const pitch=window.prompt("Short pitch for this opportunity");if(pitch)void applyToOpportunity(workspaceId,o.id,pitch).then(()=>refresh())}}>Apply</button><button onClick={()=>void createHandoff(workspaceId,o.id,"crm").then(()=>window.location.assign(`/app/revenue?source=ecosystem&opportunity=${o.id}`))}>Add to CRM</button><button onClick={()=>void createHandoff(workspaceId,o.id,"collaboration").then(()=>window.location.assign(`/app/collaboration?source=ecosystem&opportunity=${o.id}`))}>Collaborate</button></div></article>)}</div></section></div>:null}
  {tab==="programs"?<div className="eco-grid"><section className="eco-panel"><h2>Institutional / enterprise programmes</h2><form className="eco-form" onSubmit={e=>void submit(e,fd=>createProgram(workspaceId,{title:String(fd.get("title")),provider_name:String(fd.get("provider")||""),program_type:String(fd.get("type")),description:String(fd.get("description")||""),geography:String(fd.get("geography")||""),source_url:String(fd.get("source_url")||"")||null,evidence_confidence:"owner_entered",status:"open"}),"Programme saved.")}><label>Programme<input name="title" required/></label><label>Provider<input name="provider"/></label><label>Type<select name="type"><option>accelerator</option><option>incubator</option><option>grant</option><option>competition</option><option>enterprise_development</option><option>supplier_development</option><option>wil</option><option>training</option><option>pilot</option></select></label><label>Geography<input name="geography"/></label><label className="wide">Source URL<input type="url" name="source_url"/></label><label className="wide">Description<textarea name="description"/></label><button className="button button-primary wide">Add programme</button></form></section><section className="eco-panel"><h2>Programmes</h2><div className="eco-list">{data.programs.map((p:any)=><article key={p.id}><div><strong>{p.title}</strong><span>{p.provider_name||"Provider"} · {p.program_type}</span><small>Verify eligibility and closing information at the official source before applying.</small></div>{p.source_url?<a href={p.source_url} target="_blank" rel="noreferrer">Official source</a>:null}</article>)}</div></section></div>:null}
  {tab==="matches"?<section className="eco-panel"><header><UsersRound/><div><span>PARTNERSHIP MATCHER</span><h2>Estimated fit from your company profile.</h2></div></header><div className="eco-list">{estimatedMatches.map((m:any)=><article key={m.opportunity.id}><div><strong>{m.opportunity.title}</strong><span>{m.reasons.join(" · ")||"Limited profile overlap"}</span><small>Estimated match — review the underlying opportunity before acting.</small></div><b>{m.score}%</b></article>)}</div></section>:null}
  {tab==="partnerships"?<div className="eco-grid"><section className="eco-panel"><h2>Structured partnership</h2><form className="eco-form" onSubmit={e=>void submit(e,fd=>createPartnership(workspaceId,{title:String(fd.get("title")),objective:String(fd.get("objective")||""),scope:String(fd.get("scope")||""),status:"proposed"}),"Partnership workspace created.")}><label className="wide">Title<input name="title" required/></label><label className="wide">Objective<textarea name="objective"/></label><label className="wide">Scope<textarea name="scope"/></label><button className="button button-primary wide">Create partnership</button></form></section><section className="eco-panel"><h2>Partnership pipeline</h2><div className="eco-list">{data.partnerships.map((p:any)=><article key={p.id}><Handshake/><div><strong>{p.title}</strong><span>{p.status}</span></div></article>)}</div></section></div>:null}
  {tab==="pilots"?<div className="eco-grid"><section className="eco-panel"><h2>Pilot request</h2><form className="eco-form" onSubmit={e=>void submit(e,fd=>createPilot(workspaceId,{title:String(fd.get("title")),problem_statement:String(fd.get("problem")),desired_outcome:String(fd.get("outcome")||""),industry:String(fd.get("industry")||""),geography:String(fd.get("geography")||""),status:"open"}),"Pilot request created.")}><label className="wide">Title<input name="title" required/></label><label>Industry<input name="industry"/></label><label>Geography<input name="geography"/></label><label className="wide">Problem<textarea name="problem" required/></label><label className="wide">Desired outcome<textarea name="outcome"/></label><button className="button button-primary wide">Create pilot request</button></form></section><section className="eco-panel"><h2>Pilots</h2><div className="eco-list">{data.pilots.map((p:any)=><article key={p.id}><Rocket/><div><strong>{p.title}</strong><span>{p.status} · {p.geography||"location open"}</span></div></article>)}</div></section></div>:null}
  {tab==="supplier"?<section className="eco-panel"><header><BriefcaseBusiness/><div><span>SUPPLIER DISCOVERY</span><h2>Connect procurement readiness to opportunity discovery.</h2></div></header><p>Supplier profiles should reuse Phase 7 readiness evidence rather than asking companies to claim compliance again. Procurement documents remain private; only readiness signals and selected capabilities are discoverable.</p><Link to="/app/compliance" className="button button-primary">Open supplier readiness</Link></section>:null}
  {tab==="handoffs"?<section className="eco-panel"><header><Building2/><div><span>CONNECTED EXECUTION</span><h2>Discovery handoffs</h2></div></header><div className="eco-list">{data.handoffs.map((h:any)=><article key={h.id}><div><strong>{h.target_type.replace("_"," ")}</strong><span>{h.payload?.title||"Opportunity handoff"}</span><small>Source lineage preserved</small></div><a href={`${h.target_path}?handoff=${h.id}`}>Open</a></article>)}</div></section>:null}
 </AppShell>;
}
