import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { decideStudioRequest, grantStudioEntitlement, isStudioAdmin, loadStudioAdminSnapshot, revokeStudioEntitlement, setStudioTemplate, setStudioUserAccess } from "../../lib/website-studio-admin";
import "../../website-studio-control.css";

export const Route = createFileRoute("/app/studio-control")({ component: StudioControlPage });
type Tab="users"|"requests"|"templates"|"projects"|"system";

function StudioControlPage(){
 const [admin,setAdmin]=useState<boolean|null>(null),[snapshot,setSnapshot]=useState<any>(null),[tab,setTab]=useState<Tab>("users"),[notice,setNotice]=useState("Studio Control ready."),[busy,setBusy]=useState("");
 const [selectedUser,setSelectedUser]=useState(""),[selectedTemplate,setSelectedTemplate]=useState("");
 async function refresh(){setBusy("refresh");try{const allowed=await isStudioAdmin();setAdmin(allowed);if(allowed)setSnapshot(await loadStudioAdminSnapshot());}catch{setAdmin(false);}finally{setBusy("")}}
 useEffect(()=>{void refresh()},[]);
 const roles=useMemo(()=>new Map((snapshot?.roles||[]).map((row:any)=>[row.user_id,(snapshot.roles||[]).filter((r:any)=>r.user_id===row.user_id).map((r:any)=>r.role).join(", ")])),[snapshot]);
 const entitlements=useMemo(()=>new Set((snapshot?.entitlements||[]).filter((row:any)=>row.status==="active").map((row:any)=>`${row.user_id}:${row.template_key}`)),[snapshot]);
 if(admin===null)return <AppShell title="Studio Control"><p>Checking administrator access…</p></AppShell>;
 if(!admin)return <AppShell title="Studio Control"><section className="studio-control-denied"><h2>Administrator access required.</h2><p>This dashboard controls user approvals, template pricing, extraction permissions and publishing access.</p><Link to="/app/home" className="button button-secondary">Return to app</Link></section></AppShell>;
 const data=snapshot||{users:[],requests:[],templates:[],projects:[],publicationJobs:[],featureFlags:[],entitlements:[],roles:[]};
 return <AppShell title="Studio Control" eyebrow="ADMIN + DEVELOPER OPERATING DASHBOARD" action={<button className="button button-secondary" onClick={()=>void refresh()} disabled={busy==="refresh"}>{busy==="refresh"?"Refreshing…":"Refresh data"}</button>}>
  <section className="studio-control-hero"><div><span>SYSTEM AUTHORITY</span><h2>Run Website Studio from the interface.</h2><p>Approve or pause accounts, control template commercial access, grant source/publishing entitlements, review projects and inspect publication state without editing database rows manually.</p></div><div className="studio-control-kpis"><article><strong>{data.users.length}</strong><span>Accounts</span></article><article><strong>{data.requests.filter((r:any)=>r.status==="pending").length}</strong><span>Pending approvals</span></article><article><strong>{data.templates.filter((t:any)=>t.is_visible).length}</strong><span>Live templates</span></article><article><strong>{data.projects.length}</strong><span>Studio projects</span></article></div></section>
  <nav className="studio-control-tabs">{(["users","requests","templates","projects","system"] as Tab[]).map((item)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  <div className="studio-control-notice">{notice}</div>
  {tab==="users"?<section className="studio-control-panel"><header><div><h3>User access</h3><p>New accounts can preview locally. Approved accounts unlock managed editing, uploads and integrations. Source/publishing still follows template entitlement.</p></div></header><div className="studio-table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Builder status</th><th>Actions</th></tr></thead><tbody>{data.users.map((user:any)=><tr key={user.id}><td><strong>{user.display_name||user.username||"Member"}</strong><small>{user.username||user.id.slice(0,8)}</small></td><td>{roles.get(user.id)||"user"}</td><td><span className={`status ${user.builder_access_status||"pending"}`}>{user.builder_access_status||"pending"}</span></td><td><div className="studio-row-actions"><button onClick={async()=>{await setStudioUserAccess(user.id,"approved","Approved from Studio Control");setNotice("Account approved.");void refresh()}}>Approve</button><button onClick={async()=>{await setStudioUserAccess(user.id,"paused","Paused from Studio Control");setNotice("Account paused.");void refresh()}}>Pause</button><button onClick={async()=>{await setStudioUserAccess(user.id,"rejected","Access rejected from Studio Control");setNotice("Account access rejected.");void refresh()}}>Reject</button><button onClick={()=>setSelectedUser(user.id)}>Entitlements</button></div></td></tr>)}</tbody></table></div>{selectedUser?<aside className="studio-entitlement-editor"><header><div><strong>Template entitlements</strong><span>{data.users.find((u:any)=>u.id===selectedUser)?.display_name||selectedUser}</span></div><button onClick={()=>setSelectedUser("")}>×</button></header><div>{data.templates.map((template:any)=>{const key=`${selectedUser}:${template.template_key}`,active=entitlements.has(key);return <article key={template.template_key}><div><strong>{template.name}</strong><span>{template.family}</span></div>{active?<button onClick={async()=>{await revokeStudioEntitlement(selectedUser,template.template_key);setNotice(`${template.name} entitlement revoked.`);void refresh()}}>Revoke</button>:<button className="primary" onClick={async()=>{await grantStudioEntitlement(selectedUser,template.template_key,true,true,"Granted from Studio Control");setNotice(`${template.name} export/publish entitlement granted.`);void refresh()}}>Grant export + publish</button>}</article>})}</div></aside>:null}</section>:null}
  {tab==="requests"?<section className="studio-control-panel"><header><div><h3>Approval queue</h3><p>Builder, template, export and publishing requests arrive here.</p></div></header><div className="studio-request-grid">{data.requests.map((request:any)=><article key={request.id}><div><span>{request.request_type}</span><b className={`status ${request.status}`}>{request.status}</b></div><strong>{data.users.find((u:any)=>u.id===request.user_id)?.display_name||request.user_id.slice(0,8)}</strong><p>{request.reason||"No reason supplied"}</p><small>{request.template_key||"General Website Studio access"}</small>{request.status==="pending"?<footer><button className="primary" onClick={async()=>{await decideStudioRequest(request,"approved","Approved from Studio Control");setNotice("Request approved.");void refresh()}}>Approve</button><button onClick={async()=>{await decideStudioRequest(request,"rejected","Rejected from Studio Control");setNotice("Request rejected.");void refresh()}}>Reject</button></footer>:null}</article>)}</div></section>:null}
  {tab==="templates"?<section className="studio-control-panel"><header><div><h3>Template commercial controls</h3><p>All templates are paid/approval-controlled by default. Set price, visibility and access rules here. Visual code remains tied to the curated template key.</p></div></header><div className="studio-template-admin-grid">{data.templates.map((template:any)=><TemplateAdminCard key={template.template_key} template={template} onSaved={async(message)=>{setNotice(message);await refresh()}} onSelect={()=>setSelectedTemplate(template.template_key)} selected={selectedTemplate===template.template_key}/>)}</div></section>:null}
  {tab==="projects"?<section className="studio-control-panel"><header><div><h3>Projects & deployments</h3><p>Review what users are building, which template they use and whether managed publication jobs are succeeding.</p></div></header><div className="studio-table-wrap"><table><thead><tr><th>Project</th><th>Template</th><th>Status</th><th>Deployment</th><th>Updated</th></tr></thead><tbody>{data.projects.map((project:any)=><tr key={project.id}><td><strong>{project.project_name||project.business_name}</strong><small>{project.owner_id?.slice(0,8)}</small></td><td>{project.template_key}</td><td>{project.status}</td><td>{project.deployment_url?<a href={project.deployment_url} target="_blank" rel="noreferrer">Open ↗</a>:"Not deployed"}</td><td>{project.updated_at?new Date(project.updated_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div><h4>Recent publication jobs</h4><div className="studio-job-grid">{data.publicationJobs.map((job:any)=><article key={job.id}><strong>{job.provider}</strong><span>{job.status}</span><small>{job.client_message||job.project_id}</small></article>)}</div></section>:null}
  {tab==="system"?<section className="studio-control-panel"><header><div><h3>System controls</h3><p>Developer-grade visibility for feature rollout and Website Studio operating state.</p></div></header><div className="studio-system-grid"><article><strong>Authentication</strong><span>Supabase Auth · persistent sessions · approval gate</span></article><article><strong>Template extraction</strong><span>Account approval + template entitlement required</span></article><article><strong>Uploads</strong><span>Signed-in approved accounts only in the editor</span></article><article><strong>Preview isolation</strong><span>Sandboxed srcDoc · link navigation intercepted by editor</span></article></div><h4>Feature flags</h4><div className="studio-job-grid">{data.featureFlags.map((flag:any)=><article key={flag.flag_key}><strong>{flag.flag_key}</strong><span>{flag.enabled_by_default?"Enabled":"Disabled"} · {flag.rollout_percent}% rollout</span><small>{flag.description}</small></article>)}</div></section>:null}
 </AppShell>;
}

function TemplateAdminCard({template,onSaved,onSelect,selected}:{template:any;onSaved:(message:string)=>Promise<void>;onSelect:()=>void;selected:boolean}){
 const [visible,setVisible]=useState(Boolean(template.is_visible)),[access,setAccess]=useState<"free"|"paid"|"private">(template.access_type||"paid"),[price,setPrice]=useState(template.price_cents==null?"":String(Number(template.price_cents)/100)),[approval,setApproval]=useState(Boolean(template.approval_required));
 return <article className={selected?"selected":""} onClick={onSelect}><header><div><span>{template.family}</span><h4>{template.name}</h4></div><b>{template.template_key}</b></header><label><span>Visible</span><input type="checkbox" checked={visible} onChange={(e)=>setVisible(e.target.checked)}/></label><label><span>Access</span><select value={access} onChange={(e)=>setAccess(e.target.value as any)}><option value="paid">Paid</option><option value="free">Free</option><option value="private">Private</option></select></label><label><span>Price (ZAR)</span><input type="number" min="0" step="1" value={price} placeholder="Set later" onChange={(e)=>setPrice(e.target.value)}/></label><label><span>Admin approval required</span><input type="checkbox" checked={approval} onChange={(e)=>setApproval(e.target.checked)}/></label><button className="button button-primary" onClick={async(e)=>{e.stopPropagation();await setStudioTemplate({templateKey:template.template_key,visible,accessType:access,priceCents:price===""?null:Math.round(Number(price)*100),currency:"ZAR",approvalRequired:approval});await onSaved(`${template.name} commercial settings updated.`)}}>Save template settings</button></article>;
}
