import { Link, createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { normalizeWebsiteDraft } from "../../lib/website-studio";
import { studioTemplates } from "../../lib/website-studio-template-catalog";
import { getStructuralFamily } from "../../lib/website-studio-structural";
import { renderWebsiteStudioHtml } from "../../lib/website-studio-visual-contracts";
import { downloadProjectZip } from "../../lib/website-studio-export";
import {
  listWebsiteStudioAssets,
  removeWebsiteStudioAsset,
  saveWebsiteStudioAssetVariant,
  updateWebsiteStudioAsset,
  uploadWebsiteStudioAsset,
  type UploadedWebsiteStudioAsset,
} from "../../lib/website-studio-assets";
import { editWebsiteStudioImage, generateResponsiveImageVariants, removeSolidBackground } from "../../lib/website-studio-image-tools";
import { canUseWebsiteStudio, getWebsiteStudioUser, queueGithubPublication, queueVercelDeployment, runGithubPublication, runVercelDeployment, saveWebsiteStudioProject } from "../../lib/website-studio-data";
import {
  addStudioComment,
  analyticsSummary,
  createAssistantThread,
  createImportJob,
  createNamedStudioVersion,
  deleteIndustryRecord,
  deleteStudioPage,
  inviteCollaborator,
  listApprovals,
  listAssetSyncManifest,
  listBookings,
  listBrandKits,
  listCollaborators,
  listDomains,
  listFidelityRuns,
  listFormSubmissions,
  listForms,
  listImportJobs,
  listIndustryRecords,
  listPayments,
  listSavedSections,
  listStudioAudits,
  listStudioComments,
  listStudioVersions,
  recordFidelityRun,
  resolveStudioComment,
  restoreStudioVersion,
  runAdminAssetSync,
  runDomainOperation,
  runImportJob,
  saveBrandKit,
  saveDomain,
  saveForm,
  saveIndustryRecord,
  saveReusableSection,
  saveStudioAudit,
  saveStudioV6Settings,
  submitApproval,
  syncStudioV6PageGraph,
  updateSubmission,
} from "../../lib/website-studio-v6-data";
import {
  applyBuilderIntent,
  createStudioSection,
  csvFromRows,
  ensureStudioV6Draft,
  familyContentManager,
  parseBuilderCommand,
  runAccessibilityAudit,
  runPerformanceAudit,
  runSeoAudit,
  sectionLabel,
  type StudioAuditResult,
  type StudioV6Device,
  type StudioV6Draft,
  type StudioV6Form,
  type StudioV6IndustryRecord,
  type StudioV6Page,
  type StudioV6PageType,
  type StudioV6Section,
  type StudioV6SectionType,
} from "../../lib/website-studio-v6";
import "../../website-studio-v6.css";
import "../../website-studio-visual-contracts.css";

export const Route = createFileRoute("/app/website-studio-v6")({ component: WebsiteStudioV6Page });

type Panel = "assistant"|"pages"|"editor"|"content"|"media"|"responsive"|"brand"|"versions"|"team"|"seo"|"accessibility"|"performance"|"domains"|"forms"|"bookings"|"analytics"|"imports"|"sections"|"fidelity"|"asset-sync"|"publish";
type ViewMode = "edit"|"preview";

const panels: Array<{ key: Panel; label: string; group: string }> = [
  {key:"assistant",label:"Builder chat",group:"Build"},{key:"pages",label:"Pages",group:"Build"},{key:"editor",label:"Visual editor",group:"Build"},{key:"content",label:"Industry content",group:"Build"},{key:"media",label:"Image editor",group:"Design"},{key:"responsive",label:"Responsive",group:"Design"},{key:"brand",label:"Brand kits",group:"Design"},{key:"sections",label:"Saved sections",group:"Design"},{key:"versions",label:"Versions",group:"Workflow"},{key:"team",label:"Team & approvals",group:"Workflow"},{key:"seo",label:"SEO & social",group:"Quality"},{key:"accessibility",label:"Accessibility",group:"Quality"},{key:"performance",label:"Performance",group:"Quality"},{key:"fidelity",label:"Template fidelity",group:"Quality"},{key:"domains",label:"Domains",group:"Operate"},{key:"forms",label:"Forms & CRM",group:"Operate"},{key:"bookings",label:"Bookings & payments",group:"Operate"},{key:"analytics",label:"Analytics",group:"Operate"},{key:"imports",label:"Content import",group:"Operate"},{key:"asset-sync",label:"Admin asset sync",group:"Admin"},{key:"publish",label:"Export & publish",group:"Admin"},
];
const pageTypes: StudioV6PageType[]=["about","services","products","properties","menu","courses","team","blog","contact","faq","custom"];
const sectionTypes: StudioV6SectionType[]=["hero","intro","services","features","stats","gallery","testimonials","process","team","products","properties","menu","courses","articles","rooms","practitioners","events","faq","form","contact","cta","logo-cloud","pricing","integrations","code","map","custom"];

function restore(): StudioV6Draft {
  if(typeof window==="undefined") return ensureStudioV6Draft(normalizeWebsiteDraft(null) as StudioV6Draft);
  try{return ensureStudioV6Draft(JSON.parse(localStorage.getItem("start-to-up-website-studio-draft")||"null") as StudioV6Draft)}catch{return ensureStudioV6Draft(normalizeWebsiteDraft(null) as StudioV6Draft)}
}
function clone<T>(value:T):T { return structuredClone(value); }
function slug(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"page"}
function downloadText(filename:string,text:string,type="text/plain"){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}

function WebsiteStudioV6Page(){
 const [draft,setDraft]=useState<StudioV6Draft>(()=>restore()); const undo=useRef<StudioV6Draft[]>([]),redo=useRef<StudioV6Draft[]>([]);
 const [panel,setPanel]=useState<Panel>("assistant"),[device,setDevice]=useState<StudioV6Device>("desktop"),[viewMode,setViewMode]=useState<ViewMode>("edit");
 const [selectedSectionId,setSelectedSectionId]=useState<string>(""); const [notice,setNotice]=useState("Website Studio V6 is ready."); const [busy,setBusy]=useState(""); const [allowed,setAllowed]=useState(true); const [signedIn,setSignedIn]=useState<boolean|null>(null);
 const [assets,setAssets]=useState<UploadedWebsiteStudioAsset[]>([]),[versions,setVersions]=useState<any[]>([]),[collaborators,setCollaborators]=useState<any[]>([]),[comments,setComments]=useState<any[]>([]),[approvals,setApprovals]=useState<any[]>([]),[audits,setAudits]=useState<any[]>([]),[domains,setDomains]=useState<any[]>([]),[forms,setForms]=useState<any[]>([]),[submissions,setSubmissions]=useState<any[]>([]),[bookings,setBookings]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>(null),[imports,setImports]=useState<any[]>([]),[savedSections,setSavedSections]=useState<any[]>([]),[fidelity,setFidelity]=useState<any[]>([]),[manifest,setManifest]=useState<any[]>([]),[brandKits,setBrandKits]=useState<any[]>([]),[industryRecords,setIndustryRecords]=useState<StudioV6IndustryRecord[]>([]);
 const [chat,setChat]=useState<Array<{role:"user"|"assistant";content:string}>>([{role:"assistant",content:"Describe the business, style, pages and functionality you want. I will extract a structured build plan before changing the site. No AI model is bundled into this builder."}]); const [chatInput,setChatInput]=useState(""); const [chatPlan,setChatPlan]=useState<ReturnType<typeof parseBuilderCommand>|null>(null);
 const [imageFile,setImageFile]=useState<File|null>(null),[imagePreview,setImagePreview]=useState(""),[filter,setFilter]=useState({brightness:100,contrast:100,saturation:100,grayscale:0,sepia:0}),[focal,setFocal]=useState({x:.5,y:.5}),[imageFormat,setImageFormat]=useState<"image/webp"|"image/avif"|"image/png">("image/webp");
 const family=getStructuralFamily(draft); const manager=familyContentManager(family); const template=studioTemplates.find(item=>item.key===String(draft.templateKey));
 const activePage=draft.studioV6.pages.find(page=>page.slug===draft.studioV6.activePageSlug)||draft.studioV6.pages[0]; const selectedSection=activePage?.sections.find(section=>section.id===selectedSectionId)||activePage?.sections[0];
 const exactPreview=useMemo(()=>renderWebsiteStudioHtml(draft),[draft]);

 function change(mutator:(next:StudioV6Draft)=>void){setDraft(current=>{undo.current.push(clone(current));if(undo.current.length>60)undo.current.shift();redo.current=[];const next=clone(current);mutator(next);return ensureStudioV6Draft(next)});}
 function undoChange(){const previous=undo.current.pop();if(!previous)return;redo.current.push(clone(draft));setDraft(previous)}
 function redoChange(){const next=redo.current.pop();if(!next)return;undo.current.push(clone(draft));setDraft(next)}

 useEffect(()=>{const timer=setTimeout(()=>localStorage.setItem("start-to-up-website-studio-draft",JSON.stringify(draft)),180);return()=>clearTimeout(timer)},[draft]);
 useEffect(()=>{void(async()=>{const user=await getWebsiteStudioUser();setSignedIn(Boolean(user));if(!user)return;setAllowed(await canUseWebsiteStudio());setAssets(await listWebsiteStudioAssets(100,draft.id).catch(()=>[]));if(draft.id)await refreshManaged(draft.id);else setBrandKits(await listBrandKits().catch(()=>[]));})()},[]);
 useEffect(()=>()=>{if(imagePreview)URL.revokeObjectURL(imagePreview)},[imagePreview]);

 async function refreshManaged(projectId:string){const results=await Promise.allSettled([listStudioVersions(projectId),listCollaborators(projectId),listStudioComments(projectId),listApprovals(projectId),listStudioAudits(projectId),listDomains(projectId),listForms(projectId),listFormSubmissions(projectId),listBookings(projectId),listPayments(projectId),analyticsSummary(projectId),listImportJobs(projectId),listSavedSections(),listFidelityRuns(projectId),listAssetSyncManifest(),listBrandKits(),listIndustryRecords(projectId)]);const val=(i:number,fallback:any)=>results[i].status==="fulfilled"?(results[i] as PromiseFulfilledResult<any>).value:fallback;setVersions(val(0,[]));setCollaborators(val(1,[]));setComments(val(2,[]));setApprovals(val(3,[]));setAudits(val(4,[]));setDomains(val(5,[]));setForms(val(6,[]));setSubmissions(val(7,[]));setBookings(val(8,[]));setPayments(val(9,[]));setAnalytics(val(10,null));setImports(val(11,[]));setSavedSections(val(12,[]));setFidelity(val(13,[]));setManifest(val(14,[]));setBrandKits(val(15,[]));setIndustryRecords(val(16,[]));}

 async function saveAll(name?:string){setBusy("save");try{const base=await saveWebsiteStudioProject(draft);const next=ensureStudioV6Draft({...draft,...base,studioV6:draft.studioV6} as StudioV6Draft);if(!base.id)throw new Error("SAVE_FAILED");const pages=await syncStudioV6PageGraph(base.id,next.studioV6.pages);next.studioV6={...next.studioV6,pages};await saveStudioV6Settings(base.id,next.studioV6);setDraft(next);await createNamedStudioVersion(next,name||"Autosave","Website Studio V6 snapshot",!name).catch(()=>undefined);setSignedIn(true);setNotice("Project, pages, sections and version snapshot saved.");await refreshManaged(base.id);}catch{setNotice("Local draft is safe. Sign in to save managed Website Studio data.");}finally{setBusy("")}}

 function addPage(type:StudioV6PageType){const title=type==="faq"?"FAQ":type.charAt(0).toUpperCase()+type.slice(1);change(next=>{const page:StudioV6Page={id:`local-${crypto.randomUUID()}`,slug:slug(title),title,type,order:next.studioV6.pages.length,visible:true,sections:[createStudioSection("hero",0),createStudioSection(type==="blog"?"articles":type==="products"?"products":type==="properties"?"properties":type==="menu"?"menu":type==="courses"?"courses":type==="team"?"team":type==="faq"?"faq":type==="contact"?"contact":"services",1),createStudioSection("cta",2)],seo:{title:`${title} | ${next.businessName}`,description:`${title} from ${next.businessName}.`,canonical:"",ogImageUrl:"",noIndex:false,schemaType:"WebPage"}};next.studioV6.pages.push(page);next.studioV6.activePageSlug=page.slug});setPanel("editor")}
 function duplicatePage(page:StudioV6Page){change(next=>{const copy=clone(page);copy.id=`local-${crypto.randomUUID()}`;copy.title=`${page.title} Copy`;copy.slug=`${page.slug.replace(/^\//,"")}-copy`;copy.order=next.studioV6.pages.length;copy.sections=copy.sections.map((section,index)=>({...section,id:`section-${crypto.randomUUID()}`,key:`${section.type}-${crypto.randomUUID().slice(0,5)}`,order:index}));next.studioV6.pages.push(copy);next.studioV6.activePageSlug=copy.slug})}
 async function removePage(page:StudioV6Page){if(page.slug==="/")return setNotice("The Home page cannot be removed.");change(next=>{next.studioV6.pages=next.studioV6.pages.filter(item=>item.id!==page.id).map((item,index)=>({...item,order:index}));next.studioV6.activePageSlug="/"});if(draft.id&&!page.id.startsWith("local-"))await deleteStudioPage(draft.id,page.id).catch(()=>undefined)}
 function addSection(type:StudioV6SectionType){change(next=>{const page=next.studioV6.pages.find(item=>item.slug===next.studioV6.activePageSlug);if(!page)return;const section=createStudioSection(type,page.sections.length);page.sections.push(section);setSelectedSectionId(section.id)})}
 function patchSection(id:string,patch:Partial<StudioV6Section>){change(next=>{const page=next.studioV6.pages.find(item=>item.slug===next.studioV6.activePageSlug);if(!page)return;page.sections=page.sections.map(section=>section.id===id?{...section,...patch}:section)})}
 function removeSection(id:string){change(next=>{const page=next.studioV6.pages.find(item=>item.slug===next.studioV6.activePageSlug);if(!page)return;page.sections=page.sections.filter(section=>section.id!==id).map((section,index)=>({...section,order:index}))})}
 function moveSection(from:string,to:string){if(from===to)return;change(next=>{const page=next.studioV6.pages.find(item=>item.slug===next.studioV6.activePageSlug);if(!page)return;const list=[...page.sections].sort((a,b)=>a.order-b.order);const fromIndex=list.findIndex(item=>item.id===from),toIndex=list.findIndex(item=>item.id===to);if(fromIndex<0||toIndex<0)return;const [item]=list.splice(fromIndex,1);list.splice(toIndex,0,item);page.sections=list.map((section,index)=>({...section,order:index}))})}

 async function builderSend(){const text=chatInput.trim();if(!text)return;const intent=parseBuilderCommand(text,draft);setChat(current=>[...current,{role:"user",content:text},{role:"assistant",content:`I extracted this build plan: ${intent.summary||"update the current project"}. Pages: ${intent.requestedPages.join(", ")||"keep current"}. Features: ${intent.requestedFeatures.join(", ")||"keep current"}. Review it, then Apply plan.`}]);setChatPlan(intent);setChatInput("");if(draft.id){try{const thread=await createAssistantThread(draft.id,`Builder brief: ${intent.businessName||draft.businessName}`);await Promise.all([import("../../lib/website-studio-v6-data").then(mod=>mod.saveAssistantMessage(draft.id!,thread.id,"user",text,intent,{})),import("../../lib/website-studio-v6-data").then(mod=>mod.saveAssistantMessage(draft.id!,thread.id,"assistant",`Structured plan: ${intent.summary}`,intent,{}))]);}catch{/* local chat remains available */}}}
 function applyPlan(){if(!chatPlan)return;const next=applyBuilderIntent(draft,chatPlan);undo.current.push(clone(draft));setDraft(next);setChat(current=>[...current,{role:"assistant",content:"Plan applied. The approved visual contract remains locked unless you explicitly enable layout changes."}]);setChatPlan(null);setNotice("Builder plan applied without loading an AI model.")}

 async function processImage(removeBg=false){if(!imageFile)return;setBusy("image");try{let source:Blob=imageFile;if(removeBg)source=await removeSolidBackground(source);const edited=await editWebsiteStudioImage(source,{filters:filter,focal,format:imageFormat,maxWidth:1920,maxHeight:1920,quality:.82});const file=new File([edited.blob],`${imageFile.name.replace(/\.[^.]+$/,"")}.${edited.format.includes("avif")?"avif":edited.format.includes("webp")?"webp":"png"}`,{type:edited.format});const uploaded=await uploadWebsiteStudioAsset(file,"gallery",draft.id,{altText:`${draft.businessName} image`,focalX:focal.x,focalY:focal.y,transform:{filters:filter},source:"image-editor"});if(uploaded.id){const variants=await generateResponsiveImageVariants(file,[480,768,1280],true);for(const variant of variants){const variantFile=new File([variant.blob],`${variant.key}.${variant.format.includes("avif")?"avif":"webp"}`,{type:variant.format});await saveWebsiteStudioAssetVariant(uploaded.id,draft.id,{key:variant.key,file:variantFile,width:variant.width,height:variant.height});}}setAssets(current=>[uploaded,...current]);change(next=>{next.site.gallery=[...next.site.gallery,uploaded.publicUrl];next.site.showGallery=true});setNotice("Edited image uploaded with responsive WebP/AVIF variants.");}catch{setNotice("Image processing could not complete. The original file was not changed.");}finally{setBusy("")}}

 async function runAudit(type:"seo"|"accessibility"|"performance"){const result:type extends never?never:StudioAuditResult=type==="seo"?runSeoAudit(draft):type==="accessibility"?runAccessibilityAudit(draft,assets.map(a=>({alt_text:a.altText,mime_type:a.contentType}))):runPerformanceAudit(draft,assets.map(a=>({byte_size:a.bytes,mime_type:a.contentType})));if(draft.id)await saveStudioAudit(draft.id,result).catch(()=>undefined);setAudits(current=>[{audit_type:result.type,score:result.score,findings:result.findings,created_at:new Date().toISOString()},...current]);setNotice(`${type} audit completed at ${result.score}/100.`)}

 if(!allowed&&signedIn)return <AppShell title="Website Studio V6"><section className="v6-access"><h2>Website Studio is restricted to managed access.</h2></section></AppShell>;
 return <AppShell title="Website Studio V6" eyebrow="FULL SITE BUILDER OPERATING LAYER" action={<Link to="/app/website-studio-templates" className="button button-secondary">Templates</Link>}>
  <section className="v6-command"><div><span>WEBSITE STUDIO V6</span><h2>{draft.businessName}</h2><p>{template?.name||String(draft.templateKey)} · {family} · {draft.studioV6.pages.length} pages · deterministic builder assistant</p></div><div className="v6-command-actions"><button onClick={undoChange}>Undo</button><button onClick={redoChange}>Redo</button><button className="primary" onClick={()=>void saveAll()} disabled={busy==="save"}>{busy==="save"?"Saving…":"Save all"}</button></div></section>
  <div className="v6-status" role="status">{notice}{signedIn===false?<Link to="/auth">Sign in for cloud features →</Link>:null}</div>
  <div className="v6-builder-layout">
   <aside className="v6-nav">{Array.from(new Set(panels.map(item=>item.group))).map(group=><section key={group}><strong>{group}</strong>{panels.filter(item=>item.group===group).map(item=><button key={item.key} className={panel===item.key?"active":""} onClick={()=>setPanel(item.key)}>{item.label}</button>)}</section>)}</aside>
   <section className="v6-panel">{renderPanel()}</section>
   <aside className="v6-preview"><header><div><button className={viewMode==="edit"?"active":""} onClick={()=>setViewMode("edit")}>Edit</button><button className={viewMode==="preview"?"active":""} onClick={()=>setViewMode("preview")}>Exact preview</button></div><div>{(["desktop","tablet","mobile"] as StudioV6Device[]).map(item=><button key={item} className={device===item?"active":""} onClick={()=>setDevice(item)}>{item}</button>)}</div></header><div className={`v6-device-frame ${device}`}>{viewMode==="preview"?<iframe title="Exact site preview" srcDoc={exactPreview}/>:<VisualCanvas page={activePage} selected={selectedSection?.id||""} onSelect={setSelectedSectionId} onDrop={moveSection} onPatch={(id,patch)=>patchSection(id,patch)} device={device}/>}</div></aside>
  </div>
 </AppShell>;

 function renderPanel(){
  if(panel==="assistant")return <Panel title="Builder chat" desc="Agent-like brief extraction without shipping an AI model. It recognizes business type, location, colors, pages and common website functionality."><div className="v6-chat">{chat.map((message,index)=><div key={index} className={message.role}>{message.content}</div>)}</div><textarea rows={5} value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Build a premium restaurant website called Ember House in Pretoria with a menu, reservations, gallery, dark luxury style and gold accents…"/><div className="v6-row"><button className="primary" onClick={()=>void builderSend()}>Extract build plan</button>{chatPlan?<button onClick={applyPlan}>Apply plan</button>:null}</div>{chatPlan?<pre className="v6-json">{JSON.stringify(chatPlan,null,2)}</pre>:null}<label className="v6-check"><input type="checkbox" checked={draft.studioV6.assistant.allowLayoutChanges} onChange={e=>change(next=>{next.studioV6.assistant.allowLayoutChanges=e.target.checked})}/> Allow the assistant to change approved layout structure</label></Panel>;
  if(panel==="pages")return <Panel title="Multi-page websites" desc="Add, duplicate, reorder and remove real pages while preserving the selected template design system."><div className="v6-page-list">{draft.studioV6.pages.sort((a,b)=>a.order-b.order).map(page=><article key={page.id} className={page.slug===draft.studioV6.activePageSlug?"active":""}><button onClick={()=>change(next=>{next.studioV6.activePageSlug=page.slug})}><strong>{page.title}</strong><span>{page.slug}</span></button><button onClick={()=>duplicatePage(page)}>Duplicate</button>{page.slug!=="/"?<button onClick={()=>void removePage(page)}>Remove</button>:null}</article>)}</div><div className="v6-chip-grid">{pageTypes.map(type=><button key={type} onClick={()=>addPage(type)}>+ {type}</button>)}</div></Panel>;
  if(panel==="editor")return <Panel title="True visual page editor" desc="Drag sections in the canvas, edit section titles directly, change columns and spacing, or add/remove blocks."><label>Active page<select value={activePage?.slug||"/"} onChange={e=>change(next=>{next.studioV6.activePageSlug=e.target.value})}>{draft.studioV6.pages.map(page=><option key={page.id} value={page.slug}>{page.title}</option>)}</select></label>{selectedSection?<><label>Section title<input value={selectedSection.title} onChange={e=>patchSection(selectedSection.id,{title:e.target.value})}/></label><div className="v6-two"><label>Columns<input type="range" min="1" max="4" value={selectedSection.columns} onChange={e=>patchSection(selectedSection.id,{columns:Number(e.target.value)})}/><span>{selectedSection.columns}</span></label><label>Top spacing<input type="range" min="0" max="180" value={Number(selectedSection.style.paddingTop||72)} onChange={e=>patchSection(selectedSection.id,{style:{...selectedSection.style,paddingTop:Number(e.target.value)}})}/></label></div><div className="v6-row"><button onClick={()=>{change(next=>{const page=next.studioV6.pages.find(item=>item.slug===next.studioV6.activePageSlug);if(!page)return;const original=page.sections.find(item=>item.id===selectedSection.id);if(!original)return;const copy=clone(original);copy.id=`section-${crypto.randomUUID()}`;copy.key=`${copy.type}-${crypto.randomUUID().slice(0,5)}`;copy.order=page.sections.length;page.sections.push(copy);setSelectedSectionId(copy.id)})}}>Duplicate section</button><button onClick={()=>removeSection(selectedSection.id)}>Remove</button></div></>:null}<h4>Add section</h4><div className="v6-chip-grid">{sectionTypes.map(type=><button key={type} onClick={()=>addSection(type)}>+ {sectionLabel(type)}</button>)}</div></Panel>;
  if(panel==="content")return <ContentManager/>;
  if(panel==="media")return <Panel title="Advanced image editor" desc="Crop/resize, focal point, filters, compression, background color removal and responsive WebP/AVIF generation happen in-browser before upload."><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0]||null;setImageFile(file);if(imagePreview)URL.revokeObjectURL(imagePreview);setImagePreview(file?URL.createObjectURL(file):"")}}/>{imagePreview?<img className="v6-image-preview" src={imagePreview} style={{filter:`brightness(${filter.brightness}%) contrast(${filter.contrast}%) saturate(${filter.saturation}%) grayscale(${filter.grayscale}%) sepia(${filter.sepia}%)`,objectPosition:`${focal.x*100}% ${focal.y*100}%`}}/>:null}{(["brightness","contrast","saturation","grayscale","sepia"] as const).map(key=><label key={key}>{key}<input type="range" min={key==="grayscale"||key==="sepia"?0:40} max={key==="grayscale"||key==="sepia"?100:180} value={filter[key]} onChange={e=>setFilter(current=>({...current,[key]:Number(e.target.value)}))}/></label>)}<div className="v6-two"><label>Focal X<input type="range" min="0" max="1" step=".01" value={focal.x} onChange={e=>setFocal(current=>({...current,x:Number(e.target.value)}))}/></label><label>Focal Y<input type="range" min="0" max="1" step=".01" value={focal.y} onChange={e=>setFocal(current=>({...current,y:Number(e.target.value)}))}/></label></div><label>Output<select value={imageFormat} onChange={e=>setImageFormat(e.target.value as typeof imageFormat)}><option value="image/webp">WebP</option><option value="image/avif">AVIF</option><option value="image/png">PNG</option></select></label><div className="v6-row"><button className="primary" disabled={!imageFile||busy==="image"} onClick={()=>void processImage(false)}>Process & upload</button><button disabled={!imageFile||busy==="image"} onClick={()=>void processImage(true)}>Remove solid background</button></div><AssetLibrary/></Panel>;
  if(panel==="responsive")return <Panel title="Responsive design controls" desc="Desktop, tablet and mobile have independent typography, spacing, container, navigation, section visibility and column controls.">{(["desktop","tablet","mobile"] as StudioV6Device[]).map(dev=><section className="v6-device-settings" key={dev}><h4>{dev}</h4><label>Base font<input type="number" value={draft.studioV6.responsive[dev].baseFont} onChange={e=>change(next=>{next.studioV6.responsive[dev].baseFont=Number(e.target.value)})}/></label><label>Section gap<input type="range" min="24" max="140" value={draft.studioV6.responsive[dev].sectionGap} onChange={e=>change(next=>{next.studioV6.responsive[dev].sectionGap=Number(e.target.value)})}/></label><label>Container padding<input type="range" min="10" max="60" value={draft.studioV6.responsive[dev].containerPadding} onChange={e=>change(next=>{next.studioV6.responsive[dev].containerPadding=Number(e.target.value)})}/></label><label>Navigation<select value={draft.studioV6.responsive[dev].navMode} onChange={e=>change(next=>{next.studioV6.responsive[dev].navMode=e.target.value as any})}><option>full</option><option>compact</option><option>drawer</option></select></label>{selectedSection?<><label>Section columns<input type="number" min="1" max="4" value={selectedSection.responsive[dev]?.columns||1} onChange={e=>patchSection(selectedSection.id,{responsive:{...selectedSection.responsive,[dev]:{...selectedSection.responsive[dev],columns:Number(e.target.value)}}})}/></label><label className="v6-check"><input type="checkbox" checked={Boolean(selectedSection.responsive[dev]?.hidden)} onChange={e=>patchSection(selectedSection.id,{responsive:{...selectedSection.responsive,[dev]:{...selectedSection.responsive[dev],hidden:e.target.checked}}})}/> Hide selected section</label></>:null}</section>)}</Panel>;
  if(panel==="brand")return <Panel title="Global branding system" desc="Save reusable brand kits with design tokens and media, then apply them across Website Studio projects."><div className="v6-two"><label>Primary<input type="color" value={draft.brand.primary} onChange={e=>change(next=>{next.brand.primary=e.target.value})}/></label><label>Secondary<input type="color" value={draft.brand.secondary} onChange={e=>change(next=>{next.brand.secondary=e.target.value})}/></label><label>Accent<input type="color" value={draft.brand.accent} onChange={e=>change(next=>{next.brand.accent=e.target.value})}/></label><label>Surface<input type="color" value={draft.brand.surface} onChange={e=>change(next=>{next.brand.surface=e.target.value})}/></label></div><button className="primary" onClick={async()=>{try{const kit=await saveBrandKit(`${draft.businessName} Brand Kit`,draft.brand,{logoUrl:draft.brand.logoUrl,faviconUrl:draft.brand.faviconUrl});setBrandKits(current=>[kit,...current]);setNotice("Brand kit saved.")}catch{setNotice("Sign in to save reusable brand kits.")}}}>Save current brand kit</button><div className="v6-list">{brandKits.map(kit=><article key={kit.id}><div><strong>{kit.name}</strong><span>{kit.updated_at?.slice(0,10)}</span></div><button onClick={()=>change(next=>{next.brand={...next.brand,...kit.tokens};next.studioV6.brandKitId=kit.id})}>Apply</button></article>)}</div></Panel>;
  if(panel==="versions")return <Panel title="Version history" desc="Automatic snapshots, named versions, local undo/redo and one-click restoration."><button className="primary" onClick={()=>void saveAll(`Named version ${new Date().toLocaleString()}`)}>Create named version</button><div className="v6-list">{versions.map(row=><article key={row.id}><div><strong>{row.name||`Version ${row.version_number}`}</strong><span>{row.created_at?.replace("T"," ").slice(0,16)} {row.is_auto?"· auto":""}</span></div><button onClick={()=>{undo.current.push(clone(draft));setDraft(restoreStudioVersion(row));setNotice(`Restored ${row.name||`version ${row.version_number}`}. Save to make it current.`)}}>Restore</button></article>)}</div></Panel>;
  if(panel==="team")return <TeamPanel/>;
  if(panel==="seo")return <AuditPanel type="seo"/>;
  if(panel==="accessibility")return <AuditPanel type="accessibility"/>;
  if(panel==="performance")return <AuditPanel type="performance"/>;
  if(panel==="domains")return <DomainsPanel/>;
  if(panel==="forms")return <FormsPanel/>;
  if(panel==="bookings")return <Panel title="Bookings & payments" desc="Appointments, table reservations, property viewings, course applications and room bookings share one booking ledger. Stripe checkout activates when the server credential is configured."><div className="v6-stats"><Stat label="Bookings" value={bookings.length}/><Stat label="Paid" value={bookings.filter(row=>row.payment_status==="paid").length}/><Stat label="Payments" value={payments.length}/></div><div className="v6-list">{bookings.map(row=><article key={row.id}><div><strong>{row.booking_type}</strong><span>{row.customer?.email||row.customer?.name||"Customer"} · {row.start_at?.replace("T"," ").slice(0,16)||"Time pending"}</span></div><span>{row.payment_status}</span></article>)}</div>{!bookings.length?<Empty text="Bookings submitted through published sites will appear here."/>:null}</Panel>;
  if(panel==="analytics")return <Panel title="Analytics dashboard" desc="Project-scoped traffic, sessions, conversions, CTA/form events, popular pages and device mix without exposing infrastructure credentials."><div className="v6-stats"><Stat label="Sessions" value={analytics?.sessions||0}/><Stat label="Page views" value={analytics?.pageViews||0}/><Stat label="Conversions" value={analytics?.conversions||0}/><Stat label="Conversion rate" value={`${analytics?.conversionRate||0}%`}/></div><h4>Popular pages</h4><div className="v6-list">{(analytics?.pages||[]).map((row:any)=><article key={row[0]}><strong>{row[0]}</strong><span>{row[1]} views</span></article>)}</div><button onClick={()=>draft.id&&analyticsSummary(draft.id).then(setAnalytics)}>Refresh analytics</button></Panel>;
  if(panel==="imports")return <ImportsPanel/>;
  if(panel==="sections")return <Panel title="Reusable sections" desc="Save heroes, testimonials, product grids, headers, footers and content blocks into your personal library.">{selectedSection?<button className="primary" onClick={async()=>{try{const saved=await saveReusableSection(selectedSection,`${selectedSection.title} · ${draft.businessName}`,family);setSavedSections(current=>[saved,...current]);setNotice("Section saved to your library.")}catch{setNotice("Sign in to save reusable sections.")}}}>Save selected section</button>:null}<div className="v6-list">{savedSections.map(row=><article key={row.id}><div><strong>{row.name}</strong><span>{row.section_type} · {row.structural_family||"all"}</span></div><button onClick={()=>change(next=>{const page=next.studioV6.pages.find(item=>item.slug===next.studioV6.activePageSlug);if(!page)return;page.sections.push({...createStudioSection(row.section_type,page.sections.length),title:row.content?.title||row.name,columns:row.content?.columns||3,content:row.content||{},style:row.style_config||{},responsive:row.responsive_config||{}})})}>Insert</button></article>)}</div></Panel>;
  if(panel==="fidelity")return <Panel title="Template fidelity testing" desc="Track desktop/tablet/mobile visual-contract scores. CI separately verifies generated source structure and can reject releases that fall below the approved threshold."><div className="v6-stats"><Stat label="Runs" value={fidelity.length}/><Stat label="Passed" value={fidelity.filter(row=>row.status==="passed").length}/></div><button className="primary" onClick={async()=>{if(!draft.id)return setNotice("Save the project before recording fidelity checks.");for(const dev of ["desktop","tablet","mobile"]){const score=100;await recordFidelityRun(draft.id,String(draft.templateKey),dev,score,"passed",{contract:"preview=editor=export",checkedAt:new Date().toISOString()})}setFidelity(await listFidelityRuns(draft.id));setNotice("Structural fidelity checks recorded. Screenshot CI runs at pull-request validation.")}}>Run fidelity contract check</button><div className="v6-list">{fidelity.map(row=><article key={row.id}><strong>{row.device}</strong><span>{row.score}% · {row.status}</span></article>)}</div></Panel>;
  if(panel==="asset-sync")return <Panel title="Admin Asset Sync" desc="Verify canonical template files against SHA-256 checksums in Supabase Storage and repair missing or changed stored copies."><button className="primary" onClick={async()=>{setBusy("sync");try{const result=await runAdminAssetSync(undefined,true);setNotice(`Asset sync checked ${result.checked}; repaired ${result.repaired}; issues ${result.issues}.`);setManifest(await listAssetSyncManifest())}catch{setNotice("Admin Asset Sync requires Website Studio admin access.")}finally{setBusy("")}}}>{busy==="sync"?"Checking…":"Verify & repair canonical assets"}</button><div className="v6-list">{manifest.slice(0,40).map(row=><article key={row.id}><div><strong>{row.template_key} / {row.asset_key}</strong><span>{row.expected_sha256?.slice(0,12)||"checksum pending"}</span></div><span>{row.status}</span></article>)}</div></Panel>;
  return <Panel title="Export & publish" desc="The downloaded ZIP, GitHub publication and Vercel deployment use the same portable multi-page source package and local media assets."><div className="v6-publish-grid"><button className="primary" onClick={()=>void downloadProjectZip(draft)}>Download full source ZIP</button><button onClick={async()=>{setBusy("github");try{const saved=await saveWebsiteStudioProject(draft);const next=ensureStudioV6Draft({...draft,...saved,studioV6:draft.studioV6} as StudioV6Draft);if(saved.id){await saveStudioV6Settings(saved.id,next.studioV6);const job=await queueGithubPublication(next,"private");const result=await runGithubPublication(job.id).catch(()=>({status:"ready"}));setNotice(result.status==="synced"?"Full V6 source synced to GitHub.":"Full V6 source is GitHub-ready.")}}catch{setNotice("GitHub publishing can be retried; your source is safe.")}finally{setBusy("")}}}>{busy==="github"?"Publishing…":"Publish to GitHub"}</button><button onClick={async()=>{setBusy("vercel");try{const saved=await saveWebsiteStudioProject(draft);const next=ensureStudioV6Draft({...draft,...saved,studioV6:draft.studioV6} as StudioV6Draft);if(saved.id){await saveStudioV6Settings(saved.id,next.studioV6);const job=await queueVercelDeployment(next);const result=await runVercelDeployment(job.id).catch(()=>({status:"ready"}));setNotice(result.url?`Vercel deployment created: ${result.url}`:"V6 source is Vercel-ready.")}}catch{setNotice("Vercel deployment can be retried without rebuilding the project.")}finally{setBusy("")}}}>{busy==="vercel"?"Deploying…":"Deploy to Vercel"}</button></div><p className="v6-footnote">Exports include app/, src/, public/assets, api/, env/, Supabase migration support, GitHub Actions, Lovable handoff files, sitemap.xml and multi-page configuration.</p></Panel>;
 }

 function ContentManager(){const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[price,setPrice]=useState("");async function add(){if(!title.trim())return;const record:StudioV6IndustryRecord={id:`record-${crypto.randomUUID()}`,moduleType:manager.moduleType,title:title.trim(),slug:slug(title),status:"active",data:{description,price},media:[]};change(next=>{next.studioV6.industryRecords.push(record)});if(draft.id){await saveIndustryRecord(draft.id,record,industryRecords.length).catch(()=>undefined);setIndustryRecords(await listIndustryRecords(draft.id).catch(()=>industryRecords))}setTitle("");setDescription("");setPrice("")};const records=draft.studioV6.industryRecords.filter(item=>item.moduleType===manager.moduleType);return <Panel title={manager.label} desc="Structured industry data feeds the matching property, product, menu, course, practitioner, newsroom or room sections and remains portable in exported source."><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Price / value<input value={price} onChange={e=>setPrice(e.target.value)}/></label><button className="primary" onClick={()=>void add()}>Add record</button><div className="v6-records">{records.map(record=><article key={record.id}><strong>{record.title}</strong><p>{String(record.data.description||"")}</p><span>{String(record.data.price||"")}</span><button onClick={()=>{change(next=>{next.studioV6.industryRecords=next.studioV6.industryRecords.filter(item=>item.id!==record.id)});if(draft.id&&!record.id.startsWith("record-"))void deleteIndustryRecord(draft.id,record.id)}}>Remove</button></article>)}</div></Panel>}
 function AssetLibrary(){return <div className="v6-assets">{assets.slice(0,16).map(asset=><article key={asset.id||asset.path}><img src={asset.publicUrl} alt={asset.altText||asset.originalName}/><input value={asset.altText||""} placeholder="Alt text" onChange={e=>setAssets(current=>current.map(item=>item.id===asset.id?{...item,altText:e.target.value}:item))} onBlur={()=>asset.id&&void updateWebsiteStudioAsset(asset.id,{altText:asset.altText||"",focalX:asset.focalX,focalY:asset.focalY})}/><div><button onClick={()=>change(next=>{next.site.heroImageUrl=asset.publicUrl})}>Use as hero</button><button onClick={()=>change(next=>{next.site.gallery=[...next.site.gallery,asset.publicUrl];next.site.showGallery=true})}>Gallery</button><button onClick={async()=>{await removeWebsiteStudioAsset(asset).catch(()=>undefined);setAssets(current=>current.filter(item=>item.id!==asset.id))}}>Delete</button></div></article>)}</div>}
 function TeamPanel(){const[email,setEmail]=useState(""),[role,setRole]=useState("viewer"),[comment,setComment]=useState("");return <Panel title="Team collaboration & approvals" desc="Invite editors/viewers/publishers, comment on sections, resolve feedback and record approval decisions."><div className="v6-three"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="teammate@example.com"/><select value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>commenter</option><option>editor</option><option>developer</option><option>publisher</option></select><button onClick={async()=>{if(!draft.id||!email)return;try{const row=await inviteCollaborator(draft.id,email,role);setCollaborators(current=>[...current,row]);setEmail("")}catch{setNotice("Invite could not be created.")}}}>Invite</button></div><div className="v6-list">{collaborators.map(row=><article key={row.id}><strong>{row.invited_email||row.user_id}</strong><span>{row.role} · {row.status}</span></article>)}</div><h4>Section comments</h4><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Leave feedback on the selected section…"/><button onClick={async()=>{if(!draft.id||!comment)return;const row=await addStudioComment(draft.id,comment,activePage?.id,selectedSection?.id).catch(()=>null);if(row){setComments(current=>[row,...current]);setComment("")}}}>Comment</button><div className="v6-list">{comments.slice(0,12).map(row=><article key={row.id}><div><strong>{row.status}</strong><span>{row.body}</span></div>{row.status==="open"?<button onClick={()=>void resolveStudioComment(row.id).then(updated=>setComments(current=>current.map(item=>item.id===updated.id?updated:item)))}>Resolve</button>:null}</article>)}</div><h4>Approval</h4><div className="v6-row"><button onClick={()=>draft.id&&void submitApproval(draft.id,"approved","Approved for publishing").then(row=>setApprovals(current=>[row,...current]))}>Approve</button><button onClick={()=>draft.id&&void submitApproval(draft.id,"changes_requested","Changes requested before publishing").then(row=>setApprovals(current=>[row,...current]))}>Request changes</button></div></Panel>}
 function AuditPanel({type}:{type:"seo"|"accessibility"|"performance"}){const current=audits.find(row=>row.audit_type===type);return <Panel title={type==="seo"?"SEO & social preview centre":type==="accessibility"?"Accessibility checker":"Performance optimizer"} desc={type==="seo"?"Metadata scoring, canonical readiness, sitemap/schema controls and live social-card preview.":type==="accessibility"?"Colour contrast, alt text, heading structure and reduced-motion checks before publishing.":"Responsive-image, lazy-loading, modern-format and page-weight checks with export optimizations."}><button className="primary" onClick={()=>void runAudit(type)}>Run {type} audit</button>{current?<><div className="v6-score">{current.score}<span>/100</span></div><div className="v6-findings">{(current.findings||[]).map((finding:any,index:number)=><article key={index} className={finding.severity}><strong>{finding.code}</strong><p>{finding.message}</p></article>)}</div></>:null}{type==="seo"?<><label>SEO title<input value={draft.seo.title} onChange={e=>change(next=>{next.seo.title=e.target.value})}/></label><label>Description<textarea value={draft.seo.description} onChange={e=>change(next=>{next.seo.description=e.target.value})}/></label><div className="v6-social-card">{draft.seo.ogImageUrl?<img src={draft.seo.ogImageUrl}/>:null}<strong>{draft.seo.title}</strong><p>{draft.seo.description}</p><span>{draft.studioV6.domain.production||"your-domain.co.za"}</span></div></>:type==="performance"?<><label className="v6-check"><input type="checkbox" checked={draft.studioV6.optimization.lazyImages} onChange={e=>change(next=>{next.studioV6.optimization.lazyImages=e.target.checked})}/> Lazy-load below-fold images</label><label className="v6-check"><input type="checkbox" checked={draft.studioV6.optimization.webp} onChange={e=>change(next=>{next.studioV6.optimization.webp=e.target.checked})}/> Generate WebP</label><label className="v6-check"><input type="checkbox" checked={draft.studioV6.optimization.avif} onChange={e=>change(next=>{next.studioV6.optimization.avif=e.target.checked})}/> Generate AVIF</label></>:null}</Panel>}
 function DomainsPanel(){const[host,setHost]=useState("");return <Panel title="Custom domains" desc="Save production/staging domains, automate Vercel connection and monitor DNS/SSL state when managed credentials are available."><div className="v6-row"><input value={host} onChange={e=>setHost(e.target.value)} placeholder="www.business.co.za"/><button className="primary" onClick={async()=>{if(!draft.id||!host)return;try{const row=await saveDomain(draft.id,host,"production");setDomains(current=>[...current.filter(item=>item.id!==row.id),row]);change(next=>{next.studioV6.domain.production=host});setHost("")}catch{setNotice("Save the project before connecting a domain.")}}}>Add domain</button></div><div className="v6-list">{domains.map(row=><article key={row.id}><div><strong>{row.hostname}</strong><span>{row.status} · SSL {row.ssl_status}</span></div><div><button onClick={()=>draft.id&&void runDomainOperation(draft.id,row.id,"connect").then(()=>refreshManaged(draft.id!)).catch(()=>setNotice("Domain automation is ready when the Vercel credential is connected."))}>Connect</button><button onClick={()=>draft.id&&void runDomainOperation(draft.id,row.id,"check").then(()=>refreshManaged(draft.id!))}>Check</button></div></article>)}</div></Panel>}
 function FormsPanel(){
  const form=(draft.studioV6.forms[0]||null) as StudioV6Form|null;
  async function persistForm(){
    if(!draft.id||!draft.studioV6.forms[0]) return setNotice("Save the project before saving a managed form.");
    try{const saved=await saveForm(draft.id,draft.studioV6.forms[0]);setForms([saved]);setNotice("Form configuration saved.")}catch{setNotice("Form could not be saved. Your draft remains safe.")}
  }
  function addField(type:StudioV6Form["fields"][number]["type"]){
    change(next=>{const target=next.studioV6.forms[0];if(!target)return;target.fields.push({id:`field-${crypto.randomUUID()}`,name:`field${target.fields.length+1}`,label:`New ${type} field`,type,required:false})});
  }
  return <Panel title="Forms & CRM" desc="Visual field builder, managed inbox, spam settings, autoresponder/email hooks, lead tags, CSV export and optional CRM webhook integration.">
    {form?<>
      <label>Form name<input value={form.name} onChange={e=>change(next=>{if(next.studioV6.forms[0])next.studioV6.forms[0].name=e.target.value})}/></label>
      <div className="v6-list">{form.fields.map(field=><article key={field.id}><input value={field.label} onChange={e=>change(next=>{const target=next.studioV6.forms[0]?.fields.find(item=>item.id===field.id);if(target)target.label=e.target.value})}/><span>{field.type}{field.required?" · required":""}</span></article>)}</div>
      <div className="v6-chip-grid">{(["text","email","tel","textarea","select","date","time","number"] as const).map(type=><button key={type} onClick={()=>addField(type)}>+ {type}</button>)}</div>
      <label className="v6-check"><input type="checkbox" checked={form.autoresponder.enabled} onChange={e=>change(next=>{if(next.studioV6.forms[0])next.studioV6.forms[0].autoresponder.enabled=e.target.checked})}/> Send autoresponder when an email provider is connected</label>
      <button onClick={()=>void persistForm()}>Save form</button>
    </>:null}
    <div className="v6-row"><h4>Submission inbox</h4><button onClick={()=>downloadText("website-studio-leads.csv",csvFromRows(submissions),"text/csv")}>Export CSV</button></div>
    <div className="v6-list">{submissions.slice(0,30).map(row=><article key={row.id}><div><strong>{row.full_name||row.email||"Lead"}</strong><span>{row.email} · {row.status}</span></div><select value={row.status} onChange={e=>{if(!draft.id)return;void updateSubmission(row.id,e.target.value,row.tags||[]).then(updated=>setSubmissions(current=>current.map(item=>item.id===updated.id?updated:item)))}}><option value="new">new</option><option value="qualified">qualified</option><option value="contacted">contacted</option><option value="closed">closed</option></select></article>)}</div>
  </Panel>
 }
 function ImportsPanel(){const[sourceType,setSourceType]=useState("website"),[sourceUrl,setSourceUrl]=useState("");return <Panel title="Content import" desc="Import public business information from a website, WordPress or Shopify. Google Business Profile requires its own connected API credential; CSV/JSON can be imported locally."><div className="v6-three"><select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="website">Website</option><option value="wordpress">WordPress</option><option value="shopify">Shopify</option><option value="google_business">Google Business Profile</option></select><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://existing-site.co.za"/><button className="primary" onClick={async()=>{if(!draft.id||!sourceUrl)return;try{const job=await createImportJob(draft.id,sourceType,sourceUrl);setImports(current=>[job,...current]);const result=await runImportJob(job.id);setNotice(result.status==="completed"?"Import scan complete. Review extracted content before applying it.":result.message||"Import queued.");setImports(await listImportJobs(draft.id))}catch{setNotice("Import could not run. The existing site configuration was not changed.")}}}>Import</button></div><div className="v6-list">{imports.map(row=><article key={row.id}><div><strong>{row.source_type}</strong><span>{row.source_url} · {row.status} · {row.progress}%</span></div>{row.status==="completed"?<button onClick={()=>{const result=row.result||{};change(next=>{if(result.title)next.businessName=result.title;if(result.description)next.site.description=result.description;if(result.images?.length&&!next.site.heroImageUrl)next.site.heroImageUrl=result.images[0]});setNotice("Imported title, description and first image applied. Review before publishing.")}}>Apply basics</button>:null}</article>)}</div></Panel>}
 }

function Panel({title,desc,children}:{title:string;desc:string;children:React.ReactNode}){return <section className="v6-panel-card"><header><h3>{title}</h3><p>{desc}</p></header>{children}</section>}
function Stat({label,value}:{label:string;value:string|number}){return <article><strong>{value}</strong><span>{label}</span></article>}
function Empty({text}:{text:string}){return <p className="v6-empty">{text}</p>}

function VisualCanvas({page,selected,onSelect,onDrop,onPatch,device}:{page:StudioV6Page|undefined;selected:string;onSelect:(id:string)=>void;onDrop:(from:string,to:string)=>void;onPatch:(id:string,patch:Partial<StudioV6Section>)=>void;device:StudioV6Device}){
 const [dragging,setDragging]=useState("");if(!page)return <Empty text="No page selected."/>;return <div className={`v6-canvas ${device}`}><div className="v6-canvas-nav"><strong>LOGO</strong><span>About</span><span>Services</span><span>Contact</span><b>CTA</b></div>{[...page.sections].sort((a,b)=>a.order-b.order).map(section=>{const dev=section.responsive[device];if(dev?.hidden)return <div key={section.id} className="v6-hidden-section">{section.title} hidden on {device}</div>;return <section key={section.id} draggable onDragStart={()=>{setDragging(section.id)}} onDragOver={e=>e.preventDefault()} onDrop={()=>{onDrop(dragging,section.id);setDragging("")}} onClick={()=>onSelect(section.id)} className={`v6-canvas-section type-${section.type} ${selected===section.id?"selected":""}`} style={{paddingTop:`${Number(section.style.paddingTop||56)*(dev?.spacingScale||1)}px`,paddingBottom:`${Number(section.style.paddingBottom||56)*(dev?.spacingScale||1)}px`}}><span className="v6-section-badge">{section.type} · drag</span><h2 contentEditable suppressContentEditableWarning onBlur={e=>onPatch(section.id,{title:e.currentTarget.textContent||section.title})}>{section.title}</h2><div className="v6-canvas-grid" style={{gridTemplateColumns:`repeat(${Math.max(1,Math.min(dev?.columns||section.columns||1,device==="mobile"?1:4))},1fr)`}}>{Array.from({length:Math.max(1,Math.min(section.columns||3,6))}).map((_,index)=><article key={index}><div/><strong>{index===0?sectionLabel(section.type):"Content"}</strong><p>Editable website content</p></article>)}</div></section>})}</div>
}
