import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.3";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const templates=["pulse-saas","neon-foundry","studio-north","habitat-property","campus-living","table-flame","atelier-mode","medica-clinic","edulaunch","newsroom-pro"];
const assetKeys=["preview.png","logo.png","hero.png"];
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
async function hash(bytes:Uint8Array){const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join("")}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRole)return json({error:"Service unavailable"},503);const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();const admin=createClient(url,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}});const{data:userData}=await admin.auth.getUser(token);if(!userData.user)return json({error:"Authentication required"},401);const{data:roles}=await admin.from("user_roles").select("role").eq("user_id",userData.user.id);if(!(roles||[]).some((row:any)=>["admin","super_admin"].includes(String(row.role))))return json({error:"Admin access required"},403);
 let input:any={};try{input=await req.json()}catch{}const requested=String(input?.templateKey||"");const repair=input?.repair!==false;const sourceOrigin=String(Deno.env.get("START_TO_UP_PUBLIC_ORIGIN")||"https://www.start-to-up.co.za").replace(/\/$/,"");const selected=requested?templates.filter(key=>key===requested):templates;if(requested&&!selected.length)return json({error:"Unknown template"},404);
 let checked=0,repaired=0,issues=0;const results:any[]=[];
 for(const template of selected){for(const asset of assetKeys){checked++;const sourcePath=`/website-studio/templates/${template}/${asset}`;const storagePath=`canonical/${template}/${asset}`;try{const response=await fetch(`${sourceOrigin}${sourcePath}`,{headers:{"cache-control":"no-cache"}});if(!response.ok)throw new Error(`SOURCE_${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());const sourceHash=await hash(bytes);let storedHash="";const downloaded=await admin.storage.from("website-studio-assets").download(storagePath);if(downloaded.data)storedHash=await hash(new Uint8Array(await downloaded.data.arrayBuffer()));let status=storedHash===sourceHash?"healthy":"missing_or_changed";if(status!=="healthy"&&repair){const contentType=response.headers.get("content-type")|| (asset.endsWith(".png")?"image/png":"application/octet-stream");const{error}=await admin.storage.from("website-studio-assets").upload(storagePath,bytes,{upsert:true,contentType,cacheControl:"31536000"});if(error)throw error;storedHash=sourceHash;status="repaired";repaired++;}else if(status!=="healthy")issues++;
 const publicUrl=admin.storage.from("website-studio-assets").getPublicUrl(storagePath).data.publicUrl;await admin.from("website_studio_asset_sync_manifest").upsert({template_key:template,asset_key:asset,source_path:sourcePath,storage_path:storagePath,expected_sha256:sourceHash,actual_sha256:storedHash||null,status,metadata:{public_url:publicUrl,source_origin:sourceOrigin,bytes:bytes.byteLength},last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"template_key,asset_key"});results.push({template,asset,status,checksum:sourceHash});
 }catch(error){issues++;console.error("Website Studio asset sync failed",template,asset,error);await admin.from("website_studio_asset_sync_manifest").upsert({template_key:template,asset_key:asset,source_path:sourcePath,storage_path:storagePath,status:"error",metadata:{message:"Canonical asset could not be verified"},last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"template_key,asset_key"});results.push({template,asset,status:"error"});}}
 }
 return json({checked,repaired,issues,results});
});
