import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.3";
import { getWebsiteStudioProviderCredential } from "../_shared/website-studio-provider-credential.ts";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
function cleanText(value:unknown,max=4000){return String(value??"").trim().slice(0,max)}
function safeUrl(value:unknown){try{const url=new URL(String(value||""));return ["http:","https:"].includes(url.protocol)?url.toString():""}catch{return""}}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join("")}
async function integration(admin:any,projectId:string,provider:string){const{data}=await admin.from("website_studio_integrations").select("config,status").eq("project_id",projectId).eq("provider",provider).maybeSingle();return data||null}
async function resend(key:string,from:string,to:string,subject:string,text:string){if(!key||!from||!to)return;const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[to],subject,text})});if(!response.ok)throw new Error("EMAIL_PROVIDER_FAILED")}
async function crm(url:string,secret:string,payload:unknown){if(!url)return;const headers:Record<string,string>={"Content-Type":"application/json"};if(secret)headers.Authorization=`Bearer ${secret}`;const response=await fetch(url,{method:"POST",headers,body:JSON.stringify(payload)});if(!response.ok)throw new Error("CRM_WEBHOOK_FAILED")}
async function stripeCheckout(secret:string,input:{projectId:string;bookingId:string;amount:number;currency:string;description:string;successUrl:string;cancelUrl:string}){const body=new URLSearchParams();body.set("mode","payment");body.set("success_url",`${input.successUrl}${input.successUrl.includes("?")?"&":"?"}checkout=success&checkout_session_id={CHECKOUT_SESSION_ID}`);body.set("cancel_url",`${input.cancelUrl}${input.cancelUrl.includes("?")?"&":"?"}checkout=cancelled`);body.set("client_reference_id",input.bookingId);body.set("metadata[project_id]",input.projectId);body.set("metadata[booking_id]",input.bookingId);body.set("line_items[0][quantity]","1");body.set("line_items[0][price_data][currency]",input.currency.toLowerCase());body.set("line_items[0][price_data][unit_amount]",String(Math.max(50,Math.round(input.amount*100))));body.set("line_items[0][price_data][product_data][name]",input.description||"Booking deposit");const response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body});const text=await response.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!response.ok||!data?.id)throw new Error("PAYMENT_PROVIDER_FAILED");return data}
async function stripeSession(secret:string,id:string){const response=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${secret}`}});const text=await response.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!response.ok)throw new Error("PAYMENT_VERIFY_FAILED");return data}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!supabaseUrl||!serviceRole)return json({error:"Service unavailable"},503);const admin=createClient(supabaseUrl,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}});
 let body:any;try{body=await req.json()}catch{return json({error:"Invalid request"},400)}const action=cleanText(body?.action,40);const token=cleanText(body?.projectToken||body?.analyticsToken,100);if(!token)return json({error:"Project token required"},401);
 const{data:project}=await admin.from("website_studio_projects").select("id,business_name,public_submit_token,contact_config,settings_config").eq("public_submit_token",token).maybeSingle();if(!project)return json({error:"Project not found"},404);
 const clientIp=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||req.headers.get("cf-connecting-ip")||"unknown";const ipHash=await sha256(`${project.id}:${clientIp}`);const now=new Date().toISOString();
 if(action==="analytics_event"){
   const minuteAgo=new Date(Date.now()-60000).toISOString();const{count}=await admin.from("website_studio_analytics_events").select("id",{count:"exact",head:true}).eq("project_id",project.id).gte("occurred_at",minuteAgo);if((count||0)>250)return json({ok:true});
   await admin.from("website_studio_analytics_events").insert({project_id:project.id,event_type:cleanText(body.eventType,80)||"event",page_path:cleanText(body.pagePath,500)||"/",session_id:cleanText(body.sessionId,120)||null,device:body.device&&typeof body.device==="object"?body.device:{},campaign:body.campaign&&typeof body.campaign==="object"?body.campaign:{},metadata:{...(body.metadata&&typeof body.metadata==="object"?body.metadata:{}),elementId:cleanText(body.elementId,160)||null},occurred_at:now});return json({ok:true});
 }
 if(action==="form_submit"){
   const values=body.values&&typeof body.values==="object"?body.values:{};if(cleanText(values.website,100))return json({ok:true});
   const twoMinutesAgo=new Date(Date.now()-120000).toISOString();const{count}=await admin.from("website_studio_form_submissions").select("id",{count:"exact",head:true}).eq("project_id",project.id).contains("metadata",{ip_hash:ipHash}).gte("created_at",twoMinutesAgo);if((count||0)>=5)return json({error:"Please wait before sending another form."},429);
   const formSlug=cleanText(body.formSlug,100)||"contact";const{data:form}=await admin.from("website_studio_forms").select("*").eq("project_id",project.id).eq("slug",formSlug).maybeSingle();const email=cleanText(values.email,320),fullName=cleanText(values.fullName||values.name,200),phone=cleanText(values.phone,80),message=cleanText(values.message||values.enquiry||values.details,8000);
   if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:"Enter a valid email address."},400);if(!message&&!Object.keys(values).length)return json({error:"Complete the form before submitting."},400);
   const{data:submission,error}=await admin.from("website_studio_form_submissions").insert({project_id:project.id,form_id:form?.id||null,full_name:fullName||null,email:email||null,phone:phone||null,message:message||"Form submission",source_url:safeUrl(body.sourceUrl)||null,payload:values,status:"new",tags:[],metadata:{ip_hash:ipHash,form_slug:formSlug},updated_at:now}).select("id,created_at").single();if(error)return json({error:"Form could not be submitted."},500);
   const [resendConfig,crmConfig]=await Promise.all([integration(admin,project.id,"resend"),integration(admin,project.id,"crm_webhook")]);
   const resendKey=(Deno.env.get("RESEND_API_KEY")||await getWebsiteStudioProviderCredential(admin,serviceRole,project.id,"resend"));const crmSecret=await getWebsiteStudioProviderCredential(admin,serviceRole,project.id,"crm_webhook");
   const notifyTo=cleanText((project.contact_config||{}).email,320);const fromEmail=cleanText(resendConfig?.config?.fromEmail||Deno.env.get("RESEND_FROM_EMAIL")||"",320);
   if(resendKey&&fromEmail){if(notifyTo)await resend(resendKey,fromEmail,notifyTo,`New website enquiry · ${project.business_name}`,`${fullName||"A visitor"} submitted a website form.\nEmail: ${email}\nPhone: ${phone}\n\n${message}`).catch(console.error);if(form?.autoresponder_config?.enabled&&email)await resend(resendKey,fromEmail,email,cleanText(form.autoresponder_config.subject,200)||`We received your enquiry`,cleanText(form.autoresponder_config.message,5000)||"Thank you for getting in touch. We will respond shortly.").catch(console.error)}
   if(crmConfig?.status==="connected"&&safeUrl(crmConfig.config?.webhookUrl))await crm(safeUrl(crmConfig.config.webhookUrl),crmSecret,{type:"website_lead",projectId:project.id,submissionId:submission.id,values,createdAt:submission.created_at}).catch(console.error);
   await admin.from("website_studio_analytics_events").insert({project_id:project.id,event_type:"form_submit",page_path:cleanText(new URL(safeUrl(body.sourceUrl)||"https://site.invalid").pathname,500),session_id:cleanText(body.sessionId,120)||null,device:{},campaign:{},metadata:{formSlug},occurred_at:now});return json({ok:true,submissionId:submission.id});
 }
 if(action==="booking_submit"){
   const customer=body.customer&&typeof body.customer==="object"?body.customer:{};const bookingType=cleanText(body.bookingType,100)||"appointment";const startAt=body.startAt?new Date(String(body.startAt)).toISOString():null;const endAt=body.endAt?new Date(String(body.endAt)).toISOString():null;const amount=Math.max(0,Number(body.amount||0));const currency=cleanText(body.currency,10).toLowerCase()||"zar";
   const{data:booking,error}=await admin.from("website_studio_bookings").insert({project_id:project.id,booking_type:bookingType,customer,start_at:startAt,end_at:endAt,status:"pending",payment_status:amount>0?"unpaid":"not_required",amount,currency,metadata:body.metadata&&typeof body.metadata==="object"?body.metadata:{}}).select("*").single();if(error)return json({error:"Booking could not be submitted."},500);
   await admin.from("website_studio_analytics_events").insert({project_id:project.id,event_type:"booking_submit",page_path:cleanText(new URL(safeUrl(body.sourceUrl)||"https://site.invalid").pathname,500),session_id:cleanText(body.sessionId,120)||null,device:{},campaign:{},metadata:{bookingType},occurred_at:now});
   if(amount>0&&body.checkout!==false){const stripeKey=Deno.env.get("STRIPE_SECRET_KEY")||await getWebsiteStudioProviderCredential(admin,serviceRole,project.id,"stripe");if(stripeKey){const returnUrl=safeUrl(body.returnUrl||body.sourceUrl)||"https://example.com";const session=await stripeCheckout(stripeKey,{projectId:project.id,bookingId:booking.id,amount,currency,description:cleanText(body.description,180)||`${project.business_name} · ${bookingType}`,successUrl:returnUrl,cancelUrl:returnUrl});await admin.from("website_studio_payments").insert({project_id:project.id,booking_id:booking.id,provider:"stripe",provider_payment_id:session.id,status:"checkout_created",amount,currency,metadata:{checkout_url:session.url}});await admin.from("website_studio_bookings").update({payment_status:"pending",updated_at:now}).eq("id",booking.id);return json({ok:true,bookingId:booking.id,checkoutUrl:session.url})}}
   return json({ok:true,bookingId:booking.id});
 }
 if(action==="checkout_verify"){
   const sessionId=cleanText(body.sessionId,200);if(!sessionId)return json({error:"Checkout session required"},400);const stripeKey=Deno.env.get("STRIPE_SECRET_KEY")||await getWebsiteStudioProviderCredential(admin,serviceRole,project.id,"stripe");if(!stripeKey)return json({error:"Payments are not connected."},409);const session=await stripeSession(stripeKey,sessionId);if(String(session?.metadata?.project_id||"")!==project.id)return json({error:"Checkout does not belong to this project."},403);const bookingId=String(session?.metadata?.booking_id||session?.client_reference_id||"");const paid=session.payment_status==="paid";await admin.from("website_studio_payments").update({status:paid?"paid":String(session.payment_status||"pending"),updated_at:now,metadata:{checkout_url:session.url||null,payment_status:session.payment_status}}).eq("project_id",project.id).eq("provider_payment_id",sessionId);if(bookingId)await admin.from("website_studio_bookings").update({payment_status:paid?"paid":"pending",status:paid?"confirmed":"pending",updated_at:now}).eq("project_id",project.id).eq("id",bookingId);return json({ok:true,paid,bookingId});
 }
 return json({error:"Unsupported action"},400);
});
