import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.3";
import { getWebsiteStudioProviderCredential } from "../_shared/website-studio-provider-credential.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
function textOnly(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim()}
function absolute(base:string,value:string){try{return new URL(value,base).href}catch{return""}}
function extractHtml(html:string,url:string){const title=textOnly(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"");const description=(html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)?.[1]||"").trim();const headings=[...html.matchAll(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/gi)].map(match=>textOnly(match[1])).filter(Boolean).slice(0,40);const images=[...html.matchAll(/<img[^>]+src=["']([^"']+)["']/gi)].map(match=>absolute(url,match[1])).filter(Boolean).filter((value,index,array)=>array.indexOf(value)===index).slice(0,40);const links=[...html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(match=>({url:absolute(url,match[1]),label:textOnly(match[2])})).filter(item=>item.url&&item.label).slice(0,80);return{title,description,headings,images,links,source:url}}
async function getJson(url:string,headers:Record<string,string>={}){const response=await fetch(url,{headers:{Accept:"application/json","User-Agent":"Start-To-Up-Website-Studio",...headers}});const text=await response.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{}if(!response.ok)throw new Error(`SOURCE_${response.status}`);return data}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);const url=Deno.env.get("SUPABASE_URL"),serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRole)return json({error:"Service unavailable"},503);const access=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();const admin=createClient(url,serviceRole,{auth:{persistSession:false,autoRefreshToken:false}});const{data:userData}=await admin.auth.getUser(access);if(!userData.user)return json({error:"Authentication required"},401);let body:any;try{body=await req.json()}catch{return json({error:"Invalid request"},400)}const jobId=String(body?.jobId||"");if(!jobId)return json({error:"Import job required"},400);
 const{data:job}=await admin.from("website_studio_import_jobs").select("*").eq("id",jobId).single();if(!job)return json({error:"Import not found"},404);const{data:project}=await admin.from("website_studio_projects").select("id,owner_id").eq("id",job.project_id).single();if(!project)return json({error:"Project not found"},404);const{data:roles}=await admin.from("user_roles").select("role").eq("user_id",userData.user.id);const isAdmin=(roles||[]).some((row:any)=>["admin","super_admin"].includes(String(row.role)));if(project.owner_id!==userData.user.id&&!isAdmin)return json({error:"Not authorized"},403);
 await admin.from("website_studio_import_jobs").update({status:"running",progress:10,error_message:null,updated_at:new Date().toISOString()}).eq("id",jobId);
 try{const sourceType=String(job.source_type||"website"),sourceUrl=String(job.source_url||"");let result:any={};
  if(sourceType==="website"){const parsed=new URL(sourceUrl);if(!["http:","https:"].includes(parsed.protocol))throw new Error("INVALID_SOURCE");const response=await fetch(parsed.href,{headers:{"User-Agent":"Start-To-Up-Website-Studio/1.0"},redirect:"follow"});if(!response.ok)throw new Error(`SOURCE_${response.status}`);const html=(await response.text()).slice(0,2_000_000);result=extractHtml(html,response.url)}
  else if(sourceType==="wordpress"){const base=sourceUrl.replace(/\/$/,"");const[posts,pages]=await Promise.all([getJson(`${base}/wp-json/wp/v2/posts?per_page=30&_fields=id,link,title,excerpt,date,featured_media`),getJson(`${base}/wp-json/wp/v2/pages?per_page=30&_fields=id,link,title,excerpt`)]);result={title:new URL(base).hostname,description:"WordPress content import",posts:(posts||[]).map((item:any)=>({id:item.id,title:textOnly(item.title?.rendered||""),summary:textOnly(item.excerpt?.rendered||""),url:item.link,date:item.date})),pages:(pages||[]).map((item:any)=>({id:item.id,title:textOnly(item.title?.rendered||""),summary:textOnly(item.excerpt?.rendered||""),url:item.link}))}}
  else if(sourceType==="shopify"){const base=sourceUrl.replace(/\/$/,"");const data=await getJson(`${base}/products.json?limit=250`);result={title:new URL(base).hostname,description:"Shopify public catalogue import",products:(data?.products||[]).map((item:any)=>({id:item.id,title:item.title,description:textOnly(item.body_html||""),handle:item.handle,productType:item.product_type,images:(item.images||[]).map((image:any)=>image.src),variants:(item.variants||[]).map((variant:any)=>({title:variant.title,price:variant.price,sku:variant.sku,available:variant.available}))}))}}
  else if(sourceType==="google_business"){const googleToken=await getWebsiteStudioProviderCredential(admin,serviceRole,project.id,"google_business");if(!googleToken){await admin.from("website_studio_import_jobs").update({status:"needs_connection",progress:0,error_message:null,updated_at:new Date().toISOString()}).eq("id",jobId);return json({status:"needs_connection",message:"Connect Google Business Profile in Website Studio Integrations, then retry."},202)}const accounts=await getJson("https://mybusinessaccountmanagement.googleapis.com/v1/accounts",{Authorization:`Bearer ${googleToken}`});const accountName=String(job.config?.accountName||accounts?.accounts?.[0]?.name||"");if(!accountName)throw new Error("GOOGLE_ACCOUNT_REQUIRED");let locations:any={locations:[]};try{locations=await getJson(`https://mybusinessbusinessinformation.googleapis.com/v1/${accountName}/locations?readMask=name,title,storefrontAddress,phoneNumbers,websiteUri,categories,regularHours&showAll=true`,{Authorization:`Bearer ${googleToken}`})}catch{}result={title:locations?.locations?.[0]?.title||"Google Business Profile",description:"Authorized Google Business Profile import",accounts:accounts?.accounts||[],locations:locations?.locations||[]}}
  else throw new Error("UNSUPPORTED_SOURCE");
  await admin.from("website_studio_import_jobs").update({status:"completed",progress:100,result,error_message:null,updated_at:new Date().toISOString()}).eq("id",jobId);return json({status:"completed",result});
 }catch(error){console.error("Website Studio import failed",error);await admin.from("website_studio_import_jobs").update({status:"failed",progress:0,error_message:"Import source could not be read",updated_at:new Date().toISOString()}).eq("id",jobId);return json({status:"failed",message:"The source could not be imported. Check that it is public and that the required integration is connected."},400)}
});
