import fs from "node:fs";import path from "node:path";import {buildCofounderAgreement,calculateChecklistProgress,calculateWeightedReadiness} from "../src/lib/startup-os-phase7";
const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8");
const required=["src/lib/startup-os-phase7.ts","src/routes/app/compliance.tsx","src/startup-os-phase7.css","src/routes/due-diligence.tsx","src/routes/sign-document.tsx","supabase/migrations/20260830170000_startup_os_phase7_legal_compliance.sql","supabase/functions/startup-os-legal-public/index.ts"];for(const p of required)if(!fs.existsSync(path.join(root,p)))throw new Error(`Phase 7 file missing: ${p}`);
const migration=read(required[5]);const tables=["legal_setup_items","legal_obligations","legal_documents","legal_contract_templates","legal_contracts","legal_contract_parties","legal_signature_requests","legal_signature_recipients","legal_signature_events","legal_tender_assessments","legal_tender_requirements","legal_supplier_assessments","legal_supplier_requirements","legal_due_diligence_shares","legal_share_access_log"];for(const t of tables){if(!migration.includes(`public.${t}`))throw new Error(`Missing Phase 7 table ${t}`);if(!migration.includes(`'${t}'`))throw new Error(`Phase 7 RLS loop missing ${t}`);}
for(const control of ["private.startup_workspace_member","private.workspace_has_permission","company.manage","enable row level security","legal-documents","public=false"])if(!migration.includes(control))throw new Error(`Phase 7 privacy/security control missing ${control}`);
for(const fn of ["legal_compliance_summary","legal_weighted_readiness"])if(!migration.includes(fn))throw new Error(`Phase 7 workflow missing ${fn}`);
const readiness=calculateWeightedReadiness([{weight:20,status:"met"},{weight:30,status:"missing"},{weight:50,status:"met"}]);if(Math.round(readiness)!==70)throw new Error("Weighted readiness regression");if(Math.round(calculateChecklistProgress([{status:"complete"},{status:"in_progress"},{status:"not_applicable"},{status:"not_started"}]))!==50)throw new Error("Checklist regression");
const draft=buildCofounderAgreement({company:"Example",founders:["A","B"],equity:"50/50",roles:"Defined roles",vesting:"4 years",ip:"Assigned",decisions:"Joint",exit:"Transfer process",disputes:"Mediation",noticeDays:30});if(!draft.includes("INTELLECTUAL PROPERTY")||!draft.includes("not a substitute for legal advice"))throw new Error("Co-founder draft safety regression");
const route=read(required[1]);for(const label of ["Compliance Dashboard","Company Setup Checklist","Private Document Vault","CO-FOUNDER AGREEMENT BUILDER","Contract Builder","E-signature Workflow","Tender Readiness Tool","Supplier Readiness Score","Compliance & Statutory Deadlines","VERIFICATION-DOCUMENT CENTRE","Private Due-Diligence Sharing"])if(!route.includes(label))throw new Error(`Phase 7 UI missing ${label}`);if(!route.includes("do not publish registration dates, certificate issue dates or certificate expiry dates"))throw new Error("Public verification-date privacy regression");
const gateway=read(required[6]);for(const marker of ["legal_due_diligence_shares","createSignedUrl","legal_share_access_log","signer_token","signature_hash","signed_ip_hash","CONSENT_REQUIRED","Cache-Control"])if(!gateway.includes(marker))throw new Error(`Legal public gateway missing ${marker}`);if(!gateway.includes("SUPABASE_SERVICE_ROLE_KEY"))throw new Error("Public legal gateway must mediate privileged operations server-side");
console.log(`Startup OS Phase 7 release contract passed: ${tables.length} private legal/compliance tables, secure document vault, e-sign audit workflow, weighted tender/supplier readiness, private dates and auditable due-diligence sharing.`);
