import fs from "node:fs";import path from "node:path";import {calculateDilutedCapTable,calculateFundingRound,revenueMultipleValuation,scoreFundingOpportunity,targetOwnershipValuation} from "../src/lib/startup-os-phase8";
const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8");const required=["src/lib/startup-os-phase8.ts","src/routes/app/funding.tsx","src/startup-os-phase8.css","src/routes/investor-room.tsx","supabase/migrations/20260830180000_startup_os_phase8_funding_investors.sql","supabase/functions/startup-os-funding-public/index.ts"];for(const p of required)if(!fs.existsSync(path.join(root,p)))throw new Error(`Phase 8 file missing: ${p}`);
const migration=read(required[4]);const tables=["funding_opportunities","funding_saved_opportunities","funding_investors","funding_investor_contacts","funding_investor_interactions","funding_pitch_decks","funding_pitch_slides","funding_readiness_snapshots","funding_data_rooms","funding_data_room_items","funding_data_room_shares","funding_data_room_access_log","funding_rounds","funding_round_scenarios","funding_cap_table_entries","funding_valuation_scenarios","funding_offers"];for(const t of tables)if(!migration.includes(`public.${t}`))throw new Error(`Missing Phase 8 table ${t}`);for(const t of tables.filter(t=>t!=="funding_opportunities"))if(!migration.includes(`'${t}'`))throw new Error(`Phase 8 RLS loop missing ${t}`);
for(const control of ["private.startup_workspace_member","private.workspace_has_permission","company.manage","enable row level security","source_scope='platform'","funding_readiness_summary"])if(!migration.includes(control))throw new Error(`Phase 8 security/evidence contract missing ${control}`);
for(const evidence of ["company_verification_records","legal_documents","legal_contracts","revenue_invoices","revenue_accounts","growth_kpi_measurements","ops_risks","funding_pitch_slides","funding_data_room_items","funding_cap_table_entries"])if(!migration.includes(evidence))throw new Error(`Investor readiness is missing real evidence source ${evidence}`);
const round=calculateFundingRound(4_000_000,1_000_000);if(round.postMoney!==5_000_000||Math.round(round.newInvestorOwnership)!==20||Math.round(round.existingHolderOwnership)!==80)throw new Error("Funding round math regression");const cap=calculateDilutedCapTable([{holder_name:"Founder A",ownership_percent:60},{holder_name:"Founder B",ownership_percent:40}],20);if(Math.round(cap[0].ownership_percent)!==48||Math.round(cap[1].ownership_percent)!==32||cap[2].ownership_percent!==20)throw new Error("Cap-table dilution regression");if(revenueMultipleValuation(1_000_000,3)!==3_000_000)throw new Error("Revenue multiple regression");const implied=targetOwnershipValuation(1_000_000,20);if(Math.round(implied.postMoney)!==5_000_000||Math.round(implied.preMoney)!==4_000_000)throw new Error("Target ownership valuation regression");const match=scoreFundingOpportunity({stage:"seed",industry:"technology",location:"South Africa",amount:500000},{stages:["seed"],industries:["technology"],locations:["South Africa"],min_amount:100000,max_amount:1000000});if(match<80)throw new Error("Funding match scoring regression");
const route=read(required[1]);for(const label of ["INVESTOR READINESS SCORE","FUNDING FINDER","Investor CRM","PITCH DECK BUILDER","SECURE DATA ROOM","FUNDING-ROUND MODELLING","Cap Table Manager","VALUATION SCENARIOS"])if(!route.includes(label))throw new Error(`Phase 8 UI missing ${label}`);if(!route.includes("actual workspace evidence"))throw new Error("Investor readiness evidence disclosure missing");if(!route.includes("do not guarantee eligibility, funding or current availability"))throw new Error("Funding Finder certainty disclosure missing");if(!route.includes("not accounting, tax, legal or investment advice"))throw new Error("Investment calculation disclaimer missing");
const gateway=read(required[5]);for(const marker of ["funding_data_room_shares","funding_data_room_access_log","legal_documents","createSignedUrl","allow_download","SUPABASE_SERVICE_ROLE_KEY","Cache-Control"])if(!gateway.includes(marker))throw new Error(`Investor data-room gateway missing ${marker}`);
console.log(`Startup OS Phase 8 release contract passed: ${tables.length} capital tables, evidence-derived readiness, Funding Finder, investor CRM, pitch deck, secure data room, round/cap-table modelling and valuation scenarios.`);
