import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const allowed=new Set(["general","business_plan","seo","proposal","pitch","translation","workflow"]);
const safeSystem=`You are Start To Up's business drafting assistant. Use only facts supplied in the request context. Clearly mark assumptions. Never claim legal, tax, accounting, investment, regulatory, SEO, advertising or financial outcomes are guaranteed. Do not instruct the system to apply database changes. Return suggestions for human review. If evidence is missing, say what is missing.`;
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405);
 const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!anon||!serviceKey)return json({error:"SERVICE_NOT_CONFIGURED"},503);
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return json({error:"AUTH_REQUIRED"},401);
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const {data:{user}}=await userClient.auth.getUser();if(!user)return json({error:"AUTH_REQUIRED"},401);
 let body:any;try{body=await req.json()}catch{return json({error:"INVALID_REQUEST"},400)}
 const organizationId=String(body?.organizationId||""),mode=String(body?.mode||"general"),prompt=String(body?.prompt||"").trim(),threadId=String(body?.threadId||"")||null;if(!organizationId||!allowed.has(mode)||!prompt||prompt.length>12000)return json({error:"INVALID_REQUEST"},400);
 const db=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const {data:member}=await db.from("organization_members").select("workspace_role").eq("organization_id",organizationId).eq("user_id",user.id).maybeSingle();if(!member)return json({error:"WORKSPACE_ACCESS_REQUIRED"},403);
 const [{data:profile},{data:verifications},{data:metrics},{data:tasks}]=await Promise.all([db.from("company_profiles").select("trading_name,legal_name,industry,description,website,city,province,country").eq("organization_id",organizationId).maybeSingle(),db.from("company_verification_records").select("kind,status,public_label").eq("organization_id",organizationId),db.from("company_metrics").select("metric_key,metric_value,unit,period_start,period_end").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(20),db.from("workspace_tasks").select("title,status,due_at").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(20)]);
 const context={company:profile||null,verifiedRecords:(verifications||[]).filter((x:any)=>x.status==="verified"),metrics:metrics||[],tasks:tasks||[]};
 const {data:thread,error:threadError}=threadId?await db.from("intelligence_threads").select("id").eq("id",threadId).eq("organization_id",organizationId).maybeSingle():await db.from("intelligence_threads").insert({organization_id:organizationId,title:prompt.slice(0,80),mode,created_by:user.id}).select("id").single();if(threadError||!thread)return json({error:"THREAD_UNAVAILABLE"},400);
 await db.from("intelligence_messages").insert({organization_id:organizationId,thread_id:thread.id,role:"user",content:prompt,created_by:user.id});const {data:run}=await db.from("intelligence_runs").insert({organization_id:organizationId,thread_id:thread.id,mode,input_summary:prompt.slice(0,500),status:"running",started_at:new Date().toISOString(),created_by:user.id}).select("id").single();
 const endpoint=Deno.env.get("STARTUP_OS_AI_ENDPOINT"),apiKey=Deno.env.get("STARTUP_OS_AI_API_KEY"),model=Deno.env.get("STARTUP_OS_AI_MODEL")||"configured-model";let response="";let provider="deterministic";
 if(endpoint&&apiKey){try{const upstream=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${apiKey}`},body:JSON.stringify({model,messages:[{role:"system",content:safeSystem},{role:"user",content:`Mode: ${mode}\nWorkspace evidence (JSON): ${JSON.stringify(context)}\nRequest: ${prompt}`}],temperature:.2})});if(!upstream.ok)throw new Error("provider request failed");const payload=await upstream.json();response=String(payload?.choices?.[0]?.message?.content||payload?.output_text||"").trim();provider="connected_ai";}catch{response="The connected assistant provider could not complete this request. Your workspace was not changed. Review the connection and try again.";provider="provider_error";}}
 else {response=`Assistant provider is not connected. No workspace data was changed. You can still use Start To Up's deterministic tools for navigation, SEO metadata scaffolding, business-plan outlines, next actions and approval-based automations.`;}
 const disclosure=mode==="business_plan"||mode==="proposal"||mode==="pitch"?"Drafting assistance only. Verify all claims and figures before external use.":mode==="seo"?"SEO suggestions are not ranking guarantees.":mode==="translation"?"Machine-assisted localisation requires human review before publication.":"Suggestions require human review; structured records are not automatically overwritten.";
 await db.from("intelligence_messages").insert({organization_id:organizationId,thread_id:thread.id,role:"assistant",content:response,evidence:[{type:"workspace_snapshot",verifiedRecords:context.verifiedRecords.length,metrics:context.metrics.length}],provider,model:provider==="connected_ai"?model:null,created_by:user.id});if(run)await db.from("intelligence_runs").update({status:"completed",provider,model:provider==="connected_ai"?model:null,completed_at:new Date().toISOString()}).eq("id",run.id);
 await db.from("intelligence_audit_log").insert({organization_id:organizationId,actor_id:user.id,event_type:"assistant.suggestion.generated",entity_type:"intelligence_thread",entity_id:thread.id,detail:{mode,provider,no_auto_apply:true}});
 return json({ok:true,threadId:thread.id,response,provider,disclosure,changeSet:null});
});