/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppCollaborationRouteImport } from './routes/app/collaboration'
import { Route as AppCreateRouteImport } from './routes/app/create'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppModerationRouteImport } from './routes/app/moderation'
import { Route as AppNetworkRouteImport } from './routes/app/network'
import { Route as AppOrganizationsRouteImport } from './routes/app/organizations'
import { Route as AppPlansRouteImport } from './routes/app/plans'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppProgramsRouteImport } from './routes/app/programs'
import { Route as AppSessionsRouteImport } from './routes/app/sessions'
import { Route as AppTrustRouteImport } from './routes/app/trust'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCollaborationRoute = AppCollaborationRouteImport.update({
  id: '/app/collaboration',
  path: '/app/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/app/create',
  path: '/app/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/app/explore',
  path: '/app/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/app/media',
  path: '/app/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/app/messages',
  path: '/app/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/app/moderation',
  path: '/app/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/app/network',
  path: '/app/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/app/organizations',
  path: '/app/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/app/plans',
  path: '/app/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgramsRoute = AppProgramsRouteImport.update({
  id: '/app/programs',
  path: '/app/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/app/sessions',
  path: '/app/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrustRoute = AppTrustRouteImport.update({
  id: '/app/trust',
  path: '/app/trust',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/collaboration': typeof AppCollaborationRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/media': typeof AppMediaRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/network': typeof AppNetworkRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/programs': typeof AppProgramsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/trust': typeof AppTrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/collaboration': typeof AppCollaborationRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/media': typeof AppMediaRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/network': typeof AppNetworkRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/programs': typeof AppProgramsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/trust': typeof AppTrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/collaboration': typeof AppCollaborationRoute
  '/app/create': typeof AppCreateRoute
  '/app/explore': typeof AppExploreRoute
  '/app/home': typeof AppHomeRoute
  '/app/media': typeof AppMediaRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/network': typeof AppNetworkRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/programs': typeof AppProgramsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/trust': typeof AppTrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/collaboration'
    | '/app/create'
    | '/app/explore'
    | '/app/home'
    | '/app/media'
    | '/app/messages'
    | '/app/moderation'
    | '/app/network'
    | '/app/organizations'
    | '/app/plans'
    | '/app/profile'
    | '/app/programs'
    | '/app/sessions'
    | '/app/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/collaboration'
    | '/app/create'
    | '/app/explore'
    | '/app/home'
    | '/app/media'
    | '/app/messages'
    | '/app/moderation'
    | '/app/network'
    | '/app/organizations'
    | '/app/plans'
    | '/app/profile'
    | '/app/programs'
    | '/app/sessions'
    | '/app/trust'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/collaboration'
    | '/app/create'
    | '/app/explore'
    | '/app/home'
    | '/app/media'
    | '/app/messages'
    | '/app/moderation'
    | '/app/network'
    | '/app/organizations'
    | '/app/plans'
    | '/app/profile'
    | '/app/programs'
    | '/app/sessions'
    | '/app/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  AppCollaborationRoute: typeof AppCollaborationRoute
  AppCreateRoute: typeof AppCreateRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMediaRoute: typeof AppMediaRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppModerationRoute: typeof AppModerationRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgramsRoute: typeof AppProgramsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppTrustRoute: typeof AppTrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/collaboration': {
      id: '/app/collaboration'
      path: '/app/collaboration'
      fullPath: '/app/collaboration'
      preLoaderRoute: typeof AppCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/create': {
      id: '/app/create'
      path: '/app/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/app/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/media': {
      id: '/app/media'
      path: '/app/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/app/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/moderation': {
      id: '/app/moderation'
      path: '/app/moderation'
      fullPath: '/app/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/network': {
      id: '/app/network'
      path: '/app/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/app/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/app/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/programs': {
      id: '/app/programs'
      path: '/app/programs'
      fullPath: '/app/programs'
      preLoaderRoute: typeof AppProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/app/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trust': {
      id: '/app/trust'
      path: '/app/trust'
      fullPath: '/app/trust'
      preLoaderRoute: typeof AppTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  AppCollaborationRoute: AppCollaborationRoute,
  AppCreateRoute: AppCreateRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppMediaRoute: AppMediaRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppModerationRoute: AppModerationRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgramsRoute: AppProgramsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppTrustRoute: AppTrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
