insert into public.website_studio_templates (key, name, description, source_repository, default_sections, is_active)
values
('pulse-saas','Pulse SaaS','High-conversion software landing system with polished glass UI and product-first hierarchy.',null,'["hero","trust","stats","services","about","process","testimonials","contact"]'::jsonb,true),
('neon-foundry','Neon Foundry','Dark developer-product layout for APIs, platforms, infrastructure and technical startups.',null,'["hero","trust","services","about","process","contact"]'::jsonb,true),
('orbit-ai','Orbit AI','Cinematic AI startup composition with soft depth, oversized type and investor-ready polish.',null,'["hero","trust","stats","services","about","testimonials","contact"]'::jsonb,true),
('studio-north','Studio North','Editorial agency system with strong type, restrained colour and premium portfolio energy.',null,'["hero","services","gallery","about","process","testimonials","contact"]'::jsonb,true),
('boldfolio','Boldfolio','Personal brand and studio portfolio with expressive type and highly visual work presentation.',null,'["hero","gallery","services","about","testimonials","contact"]'::jsonb,true),
('counsel-prime','Counsel Prime','Executive legal-services template with authoritative typography and trust-led conversion.',null,'["hero","trust","services","about","process","testimonials","contact"]'::jsonb,true),
('ledger-house','Ledger House','Clean financial-services template with data-forward credibility and conversion-focused service cards.',null,'["hero","stats","services","trust","about","process","contact"]'::jsonb,true),
('vertex-build','Vertex Build','Bold industrial layout for contractors, engineers and project businesses.',null,'["hero","trust","stats","services","gallery","about","process","contact"]'::jsonb,true),
('habitat-property','Habitat Property','Modern property-marketing site with enquiry conversion and clean listing-style rhythm.',null,'["hero","trust","stats","services","gallery","about","contact"]'::jsonb,true),
('campus-living','Campus Living','Youthful accommodation template built for residences, applications and campus proximity.',null,'["hero","trust","stats","services","gallery","process","testimonials","contact"]'::jsonb,true),
('table-flame','Table & Flame','Warm restaurant template with premium hospitality tone and booking-first calls to action.',null,'["hero","services","gallery","about","testimonials","contact"]'::jsonb,true),
('freshcart','FreshCart','Bright ecommerce starter with product-focused sections and friendly conversion cues.',null,'["hero","trust","services","gallery","stats","contact"]'::jsonb,true),
('atelier-mode','Atelier Mode','High-fashion editorial storefront with sharp monochrome structure and understated luxury detailing.',null,'["hero","gallery","services","about","contact"]'::jsonb,true),
('glow-beauty','Glow Beauty','Soft premium beauty template for salons, skincare, spa and personal care brands.',null,'["hero","services","gallery","testimonials","about","contact"]'::jsonb,true),
('medica-clinic','Medica Clinic','Calm healthcare template with accessible information architecture and booking-focused services.',null,'["hero","trust","services","process","about","contact"]'::jsonb,true),
('edulaunch','EduLaunch','Modern training and academy template for programmes, outcomes, admissions and learner progression.',null,'["hero","stats","services","process","testimonials","contact"]'::jsonb,true),
('tiny-futures','Tiny Futures','Playful premium preschool and early-learning system with bright trust cues.',null,'["hero","services","gallery","process","testimonials","contact"]'::jsonb,true),
('summit-travel','Summit Travel','Adventure-led travel template with cinematic hierarchy and itinerary storytelling.',null,'["hero","services","gallery","stats","testimonials","contact"]'::jsonb,true),
('eventspark','EventSpark','High-energy event and activation template for tickets, lineups, partners and audience conversion.',null,'["hero","stats","services","gallery","process","contact"]'::jsonb,true),
('secureline','SecureLine','High-trust security-services template with disciplined colour and clear response pathways.',null,'["hero","trust","stats","services","process","about","contact"]'::jsonb,true),
('civic-impact','Civic Impact','Public-value template for programmes, initiatives, resources and institutional credibility.',null,'["hero","stats","services","about","process","contact"]'::jsonb,true),
('newsroom-pro','Newsroom Pro','Editorial-first information template for publications, media companies and content-led organisations.',null,'["hero","services","gallery","about","contact"]'::jsonb,true),
('autodrive','AutoDrive','Performance automotive template for dealerships, workshops and mobility brands.',null,'["hero","stats","services","gallery","trust","contact"]'::jsonb,true),
('block-ledger','Block Ledger','Dark fintech and Web3 template with sharp interface styling and investor-ready positioning.',null,'["hero","stats","trust","services","about","contact"]'::jsonb,true),
('homecraft','HomeCraft','Refined architecture and interior template with calm typography and project-led storytelling.',null,'["hero","gallery","services","about","testimonials","contact"]'::jsonb,true),
('sportforge','SportForge','Energetic fitness template for gyms, coaches, sports brands and performance programmes.',null,'["hero","stats","services","gallery","process","contact"]'::jsonb,true)
on conflict (key) do update set
  name = excluded.name,
  description = excluded.description,
  default_sections = excluded.default_sections,
  is_active = excluded.is_active,
  updated_at = now();
